### ISSUE TITLE
Retirer un déguisement ne retourne pas le personnage à sa couleur de peau originale 

### ISSUE THREAD

**Issue by dyfduanyanfang** [Eowymos/TerraUo#100]
L'utilisation du .deguisementfin pour retirer le déguisement ne retourne pas le personnage à sa couleur de peau originale. 

**Expected behavior** : Le retour à la normal après l'utilisation d'un déguisement devrait redonner au personnage la même couleur de peau qu'il/elle avait avant celle-ci.

**Comment by dyfduanyanfang** [comment]
Petite note en rapport avec l'issue aussi : 
Meme quand le déguisement est raté, le joueur doit utiliser .deguisementfin

**Comment by GokuTerra** [comment]
Je regarde cela ce soir.

**Comment by Krashto** [comment]
J'ai posté la refonte
