### ISSUE TITLE
Craft de Spell, Etude ou Ecriture?

### ISSUE THREAD

**Issue by Zxithedead** [Eowymos/TerraUo#101]
Selon le siteweb, Etude est ce qui Unlock le craft de spell, mais après test IG, c'est Ecriture qui détermine le niveau de spell craftable.

**Comment by ElusivePanda** [comment]
Selon le siteweb en date d'aujourd'hui:

Écriture | Détermine le nombre de compétences (Skills) procuré par lecture d’un livre de compétences. **Accès au système d’écriture des sorts arcaniques.**

Étude | Détermine le maximum qu’un livre de compétences peut procurer au total.

Ça me semble OK à première vue. @Krashto fermé après avoir confirmé.

**Comment by ElusivePanda** [comment]
Voir: https://github.com/Eowymos/TerraUo/issues/125
