### ISSUE TITLE
Les sorts ne dismount pas

### ISSUE THREAD

**Issue by MaasUO** [Eowymos/TerraUo#103]
C'est simple, toutes les attaques dismount sauf les sorts. Donc dès que quelqu'un est à cheval, sans avoir besoin de monter équitation, il est hors d'atteinte des mages.

**Comment by Eowymos** [comment]
Maas veut parler du fait de quand tu reçois un sort, tu ne tombes pas du cheval, même si tu n'as pas d'équitation
