### ISSUE TITLE
Fondre - Or

### ISSUE THREAD

**Issue by Nebelpfade666** [Eowymos/TerraUo#104]
Je suis inapte à fondre de l'Or, mais je peux crafter avec... 
Des idées ?

**Comment by JasmineRoy** [comment]
fondre le minerais ou refondre les items?
Si c'est le minerais, tu as surement plus de blacksmith que de mining. C'est mining qui fait la fonte et blacksmith qui permet de craft.
Si c'est la refonte, issue #33
