### ISSUE TITLE
.fiche qui ne s'update pas après un reset

### ISSUE THREAD

**Issue by YsmeeIov** [Eowymos/TerraUo#105]
Bonjour,

juste avant la mise à jour du coût des resets, j'ai fait deux resets consécutifs. Depuis, mon .fiche ne se met pas à jour, je ne voyais plus mon % monter et maintenant avec la barre de progression, elle est toujours vide.

**Comment by Krashto** [comment]
Comme je t'ai expliqué sur discord, le probleme vient du fait que tu es sous le minimum requis pour le niveau. tant que tu n'auras pas atteint l'XP de ton niveau actuel, ta barre restera vide :(

Je t'invite a contacter un membre du staff, à voir s'ils peuvent t'aider vu la complexité du systeme et du risque d'erreur
