### ISSUE TITLE
Greater heal vs heal

### ISSUE THREAD

**Issue by Elevorn** [Eowymos/TerraUo#107]
J'ai 50 de magery, 45 healing, 50 anatomy, 2 en magie et 6 en medecine.

Heal soigne de 20 en moyenne
Greater heal soigne de 30 en moyenne.

GH prend 2 fois plus long a caster, 2 reg au lieu de 1.  Je le fizzle 1 fois sur 2.  Donc c'est pas mal inutile comme spell.

**Comment by Eowymos** [comment]
Tu n'es pas encore assez fort pour ce spell à mon avis. Ce sera mieux à haut niveau.
