### ISSUE TITLE
Reroll

### ISSUE THREAD

**Issue by Daak999** [Eowymos/TerraUo#108]
Lorsqu'on REROLL et qu'on était artisan avant, tout ce qu'on a créer devient marquer avec le nom de notre nouveau personnage.

[](https://cdn.discordapp.com/attachments/723027867985772574/728671007447187456/unknown.png)

**Comment by Eowymos** [comment]
Transformer la variable Mobile en string (Name)

**Comment by animatrice-hanson** [comment]
Fixed !
