### ISSUE TITLE
Impossible de monté Stealth en haut de 60

### ISSUE THREAD

**Issue by MBRND** [Eowymos/TerraUo#109]
On a regarder avec un GM ingame stealth semble buggé. Pas moyen de le faire passer plus loin que 60%
Acutellement mon cap individuel est a 61.5 et mon total cap 498.4/515

Tout les autres skills montent normalement.

**Comment by Krashto** [comment]
Est-ce que tu fail parfois ton stealth?

**Comment by MBRND** [comment]
J'ai pus l'impression non. Je vais esseyer en portant une armure pour voir. J'ajoute les infos dès que le test est fait.

**Comment by MBRND** [comment]
Bon ben j'ai l'impresion que c'était ca. Je vien de prendre .1 en portant une armure. 84 de AR. M'a permis de monté a 60.1. J'aurai cru que l'armure influencai la difficulté, mais pas de pouvoir monté ou pas stealth.

**Comment by Krashto** [comment]
Il faut porter une armure pour que le skill monte au dessus de 60
