### ISSUE TITLE
Item id

### ISSUE THREAD

**Issue by Ehthanas** [Eowymos/TerraUo#111]
J'ai vu qu'en utilisant itemid sur des mobs ou des gens ca montrait leurs noms (mobs) ou sur des players ca faisait écrire leurs noms et titres ( bob , hastane , hideux , gras ) . Je me demandais si c'étais un effet utile a quelque chose , possible admetton de découvrir une personne déguisée ?

**Comment by Krashto** [comment]
Item ID ne sert pas a découvrir une personne déguisée non.
