### ISSUE TITLE
Chant de force

### ISSUE THREAD

**Issue by Necromig** [Eowymos/TerraUo#112]
Le chant de force est castable à 4 de musique, dure environ 40 sec, mais ne semble pas augmenter mes dégâts. 

Degats sur des loups avec un arc Souplecorde exceptionnel

**Comment by chuck144** [comment]
EN party je n'ai pas reussi a augmenté les dmg des autres membres. (pas d'Anim sur les autres que sur moi et aucun dmg de plus)

**Comment by ElusivePanda** [comment]
Fixed, prochaine Maj

**Comment by Necromig** [comment]
Pour info, hier soir aux trolls, augmentation minimale du dégât mais on a surtout tous eu l'impression que ça augmentait jes chanses de toucher, ce qui rst génial si c'est le cas!
