### ISSUE TITLE
Dégâts avec arme pour mages

### ISSUE THREAD

**Issue by pocloutier87** [Eowymos/TerraUo#113]
Initialement les dégâts des mages ont été baissés avec les armes dès qu'ils avaient leur classe 1. Je ne sais trop qu'est-ce qui a motivé ceci, mais présentement certaines classes de mages sont prévues avoir des niveaux plus élevés que 0 en capacité d'arme (nécromancien 2, druid 2, les trois autres classes niveau 1 maximum).

Je ne peux pas tester autre chose que mon personnage, mais une arme à deux mains exceptionnelle, même avec 20 de force, ne devrait-elle pas faire plus que 1 de dégâts comme les poings ? Ce sont des griffes exceptionnelles niveau 1.

Est-ce que d'autres ici peuvent donner des chiffres ? Je ne sais pas si on a des mages avec 90 de force par exemple.

Je soulève surtout le point parce que l'inverse n'est pas identique : les guerriers qui prennent des sortilèges, en dehors de leur intelligence/magery/capacité-magie ne semblent pas pénalisés. Par exemple, familiar a les mêmes stats pour un mage et un guerrier (ou en tout cas très proche - à confirmer peut-être). Ce guerrier est donc drolement plus efficace que le mage à bas niveau puisqu'il peut aussi pleinement utiliser son arme ET le sortilège (oui, 5 PAs de plus, mais ça en vaut drôlement la chandelle).

Évidemment d'autres chiffres permettraient de dire si c'est OK ou c'est juste que 20 STR = oublie tout simplement les armes, même en dernier recours. Par comparaison, avant la réduction, je pouvais faire entre 16 et 22 par coup avec 20 de force 0 tactics 30 anatomy alors que 90 de force donnait (avant le rebalancement) 60 à 70 de mémoire sur la même arme. Je ne m'attends pas à refaire beaucoup de dégâts, mais disons que c'est plutôt drole frapper aussi fort avec une two-handed except qu'avec ses poings.

Selon les tests d'autres joueurs, peut-être revoir carrément les gains en capacité d'arme des mages ? Ou si avec + de force c'est OK, laisser pareil, à voir, c'est plus un topic qu'une demande directe.

**Comment by Krashto** [comment]
Nous avons rescale selon les capacités d'arme.

Ensuite, avec 20 de str, c'est tout a fait normal que tu fasses du 1 dégat. 

Un guerrier avec une capacité 1 et 20 de str fera autant que toi.
