### ISSUE TITLE
Le sort "Révélation" ne fonctionne tout simplement pas

### ISSUE THREAD

**Issue by MaasUO** [Eowymos/TerraUo#114]
Voilà, ce devrait normalement révéler une large zone autour de la case où tu lances le sort. Présentement, même si je fais le sort sur la case où quelqu'un est caché, il ne se produit rien. Si le sort nécessite du DH pour être effectif, il est drôlement pénalisant!

**Comment by Eowymos** [comment]
C'est un combat entre Magery et Hiding, avec un roll. Ce n'est juste pas un instant DH.

**Comment by ElusivePanda** [comment]
Après vérification, reveal est fonctionnel. Il possède sa propre twist pour le distingué de DH. Il a subit une légèrement modification principalement pour le QoL.
