### ISSUE TITLE
Lumberjack ( problème récolte de bois ) 

### ISSUE THREAD

**Issue by Jobarco** [Eowymos/TerraUo#119]
Avec max str, je récolte 12 buches d'un coup. Après, l'arbre est vide.

Avec 68 de str, je récoltais 7 buches. Mais une fois que je récolte mes 7 buches, je ne peux pluus bucher car l'arbre me dit qu'il est vide. Hors, je sais que les arbres sont 12 buches de disponibles. Se peut-il que le systeme calcule comme si je voulais recolter 7 buches supplémentaires et ne me premet pas de bucher ? 

Merci

**Comment by Eowymos** [comment]
Ça ne veut pas dire que l'arbre a 12, mais que quand tu bûches, STR te donne plus de bûches que ce que l'arbre a. Le bonus est calculé après la coupe, pas pendant.
