### ISSUE TITLE
Sort 714 - Chêne soigneur - Nature 6 - est un sort offencif

### ISSUE THREAD

**Issue by chatpoter** [Eowymos/TerraUo#124]
Le sort chêne soigneur est considéré comme un sort offensif , donc en groupe personne de peut piller dessus pour ce soigner.
Si nous ne sommes pas en groupe c'est considéré comme un acte criminel, mais quelqu'un d'autre peut piler dessus et recevoir le soin.

**Comment by ElusivePanda** [comment]
Fixed prochaine maj
