### ISSUE TITLE
Créer sort rang 8 impossible

### ISSUE THREAD

**Issue by Nanoyo** [Eowymos/TerraUo#125]
Bonjour, 

Après échange sur discord pour vérifier que ce ne soit pas une méconnaissance de ma part... Impossible de créer les sorts rang 8 et plus. Actuellement la création reste à 0%. Le skill min de création affiché est à 52,5%. J'ai testé avec un PA 7 en écriture, mais aussi un PA 7 en étude. Ca ne semble pas être lié puisque je parviens à faire les rang 7 (45% min) avec un PA 5 en écriture et PA 4 en étude. 

Merci d'avance :)

**Comment by Nanoyo** [comment]
Pour info, après échange avec Maexi, on a un peu mieux "déduit" la chose.

Pour crafter un spell, il ne faut pas "juste" de l'écriture, mais aussi des PA en étude. 
Avec 7 en écriture ET 7 en étude, c'est possible de craft rang 8 et 9. 

A noter que sur le site, seule écriture est indiqué comme ayant une influence sur le craft et rien ne permet de deviner cette astuce en jeu.

**Comment by Krashto** [comment]
![image](https://user-images.githubusercontent.com/67296022/86851112-615c3080-c080-11ea-957a-bfd937b740d1.png)

**Comment by ElusivePanda** [comment]
Écriture 5 devrait être suffisant pour les sorts niveau 8.
