### ISSUE TITLE
Deguisement

### ISSUE THREAD

**Issue by Ehthanas** [Eowymos/TerraUo#126]
Les titres pour déguisement ( métiers et classes ) ne fonctionnement pas , je suppose que c'est avec .titre que l'on dois changer ?

Un échec partiel est aussi considéré comme un échec ; J'ai échoué a changer par exemple mon nom et apparence , mais pas le métier et classe . Je dois attendre le meme temps de l'échec total au lieu de 5 minutes . Qui plus est le nom n'est plus inconnu mais reste identique et ne change pas .

**Comment by dyfduanyanfang** [comment]
Déjà filed mais le même ordre d'idée si on veut merge toutes les issues liées au déguisement : On ne retrouve pas sa couleur de peau originale en sortant d'un déguisement et les titres personalisés ne suivent/save pas.

**Comment by GokuTerra** [comment]
Pour ce qui est de la partie titre, je viens de le régler. Je m'attaque maintenant au problème de délais que tu apportes.

**Comment by Krashto** [comment]
Je vais clore tout les post sur déguisement actuel et regrouper le tout en un seul ce soir

**Comment by GokuTerra** [comment]
Ce problème n'en était pas vraiment un, puisque le délais ne peut réellement accroître en fonction du nombre d'échec. Par contre, pour ce qui est des titres, ça devrait être beau.
