### ISSUE TITLE
Nécromancie (suite)

### ISSUE THREAD

**Issue by Hazlith** [Eowymos/TerraUo#127]
- **Peau de mort** : Le message est encore pas synché avec le AR affiché. On se demandait aussi si le AR n'est pas mis à jour simplement quand le sort termine.

- **Serment de sang** : On ne peut "caster" sur soi, ça dit comme message : "You can't curse that" 

- **Strangulaire** : J'imagine que c'est voulu qu'on ne peut l'utiliser avant classe 3, le temps d'avoir 4 de natures et 8 de nécromancie ?

Merci !

**Comment by ElusivePanda** [comment]
Peau de mort, je vais revérifié.
Serment de sang doit être caster sur ton ennemi. C'est un curse qui cause de la réflexion de dommage physique.
Strangulaire, comme tout les summons, tu dois avoir les pré-requis en invocation/nécromancie, mais aussi en familier. Quelqu'un qui met tout ses points en invocation, sans familier, ne pourra pas invoquer un élémentaire de feu, par exemple.

**Comment by Hazlith** [comment]
Merci !

**Comment by ElusivePanda** [comment]
Peau de mort fonctionne, mais le AR n'est pas retiré à la fin du sort, tant que le AR n'est pas refresh.

**Comment by Hazlith** [comment]
Exact, je crois aussi que c'est ça qui se passe !
Merci pour le retour rapide.

**Comment by ElusivePanda** [comment]
Fixed prochaine maj.
