### ISSUE TITLE
Suggestion - Sculpture

### ISSUE THREAD

**Issue by JasmineRoy** [Eowymos/TerraUo#129]
La sculpture utilise des roches qui doivent être ramassées avec une fronde.

1. Il serait bien d'avoir un objet un peu plus général pour amasser les roches, comme la pelle par exemple, parce qu'utiliser une fronde pour amasser des cailloux dans la foret pour faire de la sculpture c'est un peu étrange

2. Personnellement j'aimerais beaucoup pouvoir également faire des sculptures en métal. Peut-être qu'en plus de la possibilité d'utiliser les pierres, on pourrais avoir possibilité d’utiliser des minerais/des lingots différents pour faire des statues? (parce que des statues en or, c'est cool) Je lance l'idée comme ça!

**Comment by animatrice-hanson** [comment]
De la part de @Hebius06 :
Rajout sur le sujet : 

1) les plus grosses statues nécessitent 250 roches (hors réduction de sagesse), pour une réussite de 15%  (hors boost d'intelligence) ce qui fait une moyenne de **1666 roches** pour une réussite. Sachant qu'il faut environ **6 secondes** pour ramasser entre 1 et 4 roches (soit **2,5 roches en moyenne**), cela nécessite **67 minutes** de farm de cailloux

2) les roches sont d'une seule couleur. la possibilité de récupérer diverses roches colorées (ou pouvoir peindre une création) serait un plus.

3) la possibilité de renommer ses créations serait appréciable.

4) un outil plus adapté d'une fronde serait justifié (pelle à argile, pioche a rochers, etc)

**Comment by animatrice-hanson** [comment]
Correction pour les sculptures prochaines mise à jour :
Fix des % de réussite
Teindre une sculpture disponible
Ajout d'une description disponible
Le nombre de roche ramassé a été fix dernièrement (artisan X2 sur la récolte)

Le seul outil pour amasser des roches reste la fronde.
