### ISSUE TITLE
Ajouter un bouton pour reroll de personnage avec coût

### ISSUE THREAD

**Issue by Eowymos** [Eowymos/TerraUo#13]

**Comment by Nebelpfade666** [comment]
**Version de Teilia**
.transfert 
Tu bank ton XP actuel et celle de ton personnage tombe à zéro. Aucun besoin de tuer le personnage, si exemple tu veux le garder. Si jamais tu te tuais deux fois de suite (assomage+mort), ton personnage était mort pour de bon. Tu pouvais le jouer en fantôme ou bien retourner à la case départ du jeu (zone de création) ce qui t'enlevait tout tes actifs. Autre choix plus facile était de le supprimer le personnage, en créer un neuf et récupérer l'XP en banque dans le .transfert, avant d'atteindre le niveau 10. À mes souvenirs, c'est environ 10% de Malus d'XP appliqué.
+ Pas besoin de MJ
- Fourre toi pas !

**Comment by Krashto** [comment]
![image](https://user-images.githubusercontent.com/67296022/85566696-46101080-b5fe-11ea-985d-3ce8dad981e9.png)
Je conserve mon XP, je me fais seulement retourner a la salle de creation

**Comment by Nebelpfade666** [comment]
Problèmes quand on utilise le Reroll :
Pouvoir renommer son personnage.
Lui faire perdre sa guilde s'il en fait parti d'une.

**Comment by Eowymos** [comment]
Une page sur la pierre de création a été ajoutée pour le nom. On perd bel et bien de l'expérience.
