### ISSUE TITLE
Monture lors d'un reroll de personnage

### ISSUE THREAD

**Issue by NorNorr** [Eowymos/TerraUo#130]
J'ai remarquer que lorsqu'on reroll un personnage tu garde ta vieille monture si elle est rester chez l'animalier j'ai eu une grande surprise quand j'ai remarquer que j'avais 2 montures apres avoir stabler ma nouvelle.

**Comment by GokuTerra** [comment]
Ça devrait être arrangé pour la prochaine mise à jour.

**Comment by GokuTerra** [comment]
Ça devrait être réglé d'ici la prochaine mise à jour.
