### ISSUE TITLE
Mages hommes lezards (legere modif a faire)

### ISSUE THREAD

**Issue by Koukcy** [Eowymos/TerraUo#131]
Petit oubli lors de la création des mobs, le script du mage ssins a été changé (copié) pour le mage homme lezard, je crois que seulement le nom du mob en vie a été changé.  Lorsqu'on le tue il deviens un corps de mage sinss et il donne les memes loot (cuir et os normal) au lieu des os de reptiles.

**Comment by Eowymos** [comment]
Ce sont des Ssins avec une modification de corps en jeu, avec le XML. C'est voulu ainsi.
