### ISSUE TITLE
Sort Créature (Nature 1) Vs Famillier (Nécro 1)

### ISSUE THREAD

**Issue by chatpoter** [Eowymos/TerraUo#132]
Pour le même nombre de Magery - Intel - capacité de magie  , les invocations de familier (Necro) dure vraiment plus longtemps que ceux d'invocation de créature (nature 1).

Je ne sais pas lequel devrait être a vérifié, mais je crois qu'il devrait avoir sensiblement la même duré.

Suggestion par le fait même, il serait intéressant que le cheval soit a duré indéterminée comme l'invocation de Horde qui a un Backpack.

**Comment by ElusivePanda** [comment]
Les sorts de nécro ont une durée respectable car ils ont déjà subit leur passe de balancing.
En ce qui concerne SummonCreature, il est une victime du bug qui empêche Int de scale la durée des sorts.
Voir: https://github.com/Eowymos/TerraUo/issues/35
C'est déjà corrigé, à venir dans la prochaine Maj. 
Summon creature ne sera pas permanent, mais avec suffisamment de INT, le cheval ne sera plus inutile.
