### ISSUE TITLE
[BUG] Canne macabre

### ISSUE THREAD

**Issue by GarukWyrmog** [Eowymos/TerraUo#134]
Problème avec la représentation IG de la canne macabre. Lorsqu'on la porte, elle apparait IG comme une tunique.
https://media.discordapp.net/attachments/408689088384729092/730499244724584448/bug_canne_macabre.png

**Comment by lefranco86** [comment]
La tunique change même de couleur selon le bois ! 
![canneMacabre1](https://user-images.githubusercontent.com/15695199/87387773-684bdd00-c571-11ea-913a-e8a2d3b933c8.png)
![canneMacabre2](https://user-images.githubusercontent.com/15695199/87387774-68e47380-c571-11ea-8046-9f312fc95b45.png)

**Comment by MissIelenia** [comment]
Réparé et testé 
![image](https://user-images.githubusercontent.com/59938483/88733176-a0bcf080-d105-11ea-9372-8b09fd9d493f.png)
