### ISSUE TITLE
Strangulaire

### ISSUE THREAD

**Issue by Ripdream** [Eowymos/TerraUo#136]
Necromancie 8.

Le strangulaire 8 est équivalent en force au vampire bat (famillier 1). 

Le strangulaire a plus de HP mais il frappe autant que le vampire bat, il est moins rapide (vitesse de frappe) et n'a pas de cool effet comme le leech que le vampire bat procure. 

Par plus de HP c'est 100 de plus. 

prend 3 famillier.

**Comment by ElusivePanda** [comment]
Je vais jeter un oeil, possiblement que le vampire bat est un peu overtuned comparer aux autres summons niveau 1 / 1 follower slot.
Et dans un même temps, je vais comparer le strangulaire aux summons d'invocation 3 follower slot.

**Comment by pocloutier87** [comment]
FYI le vampiric bat demande 2 de follower slot, pas 1. 

Peut-être plutôt comparer avec les sortilèges invocation de niveau similaire ou un peu inférieur les requis et la force, plutôt que les followers à 3 ?

**Comment by ElusivePanda** [comment]
Les summons ont eu une passe de balance générale, à voir dans la prochaine maj. En général, les invocations de bas niveau seront moins fort. Le strangulaire a reçu un peu d'amour.

Merci de continuer à donner votre feedback, on atteindra jamais la balance parfaite, mais on est en amélioration constante.
