### ISSUE TITLE
Coiffe (Tête de loup)

### ISSUE THREAD

**Issue by Daak999** [Eowymos/TerraUo#139]
Lorsque le personnage est une femme et qu'on lui met une tête de loup (principalement Nalkiri), le personnage se retrouve a avoir une barbe lorsqu'on le regarde IG. Par contre, son paperdoll est correct et ne montre pas de barbe.

**Comment by MissIelenia** [comment]
Testé et moi il est ok 
![image](https://user-images.githubusercontent.com/59938483/88740565-87b73e00-d10b-11ea-8e10-b66a9fa131ba.png)
