### ISSUE TITLE
Déguisement dans son ensemble.

### ISSUE THREAD

**Issue by MBRND** [Eowymos/TerraUo#14]
Déguisement en général ne semble pas fonctionner. Voici un résumé de mes observations:
1. Le titres ne changent pas même avec 100% de chance de réussite
2. Les classes ne changent pas même avec 100% de réussite.
3. (Probablement lier au problèmes 1 et 2) mais passé 4 de déguisement on recoit un message que notre déguisement est partiellement réussi. Sans aucuns effets a un actuel déguisement
4. Si le nom ne réussi pas le default Inconnu n'est pas appliqué (5 de déguisement +)
5. Pas un BUG, mais les timers devrait-être visible. Le 5 minutes entre les essait et le 1h30 de cool down après un déguisement réussit. Seulement pour des raisons de UX. Personnelement je pense que le 1h30 de cooldown après une réussite pourrait-être retiré. Le cooldown entre essait pourrait-être augmenté a 10 minutes. Je pense que les abus ne serai pas trop possible ainsi.
6. Le reboot server devrait permettre de garder son déguisement.
7. Lorsqu'on délog avec un déguisement, nos settings de personnages sont tous reseté (le changement de nom semble un hard change plustot qu'un nom par dessus notre vrai nom, ce qui fait que lors de la reconnection le jeu ne trouve pas notre dossier de settings et prend le default) Pour le moment on doit délogé avec notre vrai persona pour eviter le problème. (Les settings de perso ne sont pas perdu, seulement mal répertorié par le jeu)

**Comment by Krashto** [comment]
Ajout du systeme de connaissance selon les PA investis en déguisement afin de permettre au joueur espion de ne pas dependre de 2-3 autres joueurs

Doit prendre le skin de la race sélectionné.

**Comment by Krashto** [comment]
Le skin de race se fait toujours retiré, nous restons sans "couleur" (Skin blanc)
La sauvegarde fonctionne bien pour le déguisement

**Comment by MecheCourte** [comment]
Observations de ma part: 

1. Problème de Skin - Déguisement échoué 

- Le skin de race tombe dans le sac. et le Skin du personnage devient ''Blanc / gris''. 
- Faire la commande .deguisementfin remet le skin de race, mais il y a toujours une copie du skin dans le sac.

**Comment by MBRND** [comment]
J'ai testé le timer d'après un déguisement réussi. Il est maintenent de 1h. On peu reprendre un déguisement après une heure, que le déguisement actuel soit encore valide ou pas. C'est working as intended si vous voulez mon avis. J'ajouterai un timer dans le message qui nous dit qu'on ne peu pas refaire un déguisement malgrer tou.

La sauvegarde du déguisement lorsqu'on déconnecte ne fonctionne toujours pas malgrer la MAJ qui semblait dire que oui.

Il est toujours seulement possible de modifier son nom avec déguisement. 1-4 Inconnu 5-8 Nom custom. (Race pas encore esseiller) Tout les autres variables ne change pas même a 100% de reussite.

**Comment by MBRND** [comment]
Update avec 12 de déguisement:
- Le changement de race ne change pas autrechose que la couleur de peau. Le titre de race et la description au mouse over de race ne change pas.
- Les titres, classes et apparence ne change pas non plus.

Changement de nom fonctionne A1.
Changement de Sex fonctionne A1.
