### ISSUE TITLE
Talismans Mortanyss - Couture (suite)

### ISSUE THREAD

**Issue by Hazlith** [Eowymos/TerraUo#140]
On peut maintenant créer des talismans à partir des cuirs directement. 
Par contre, les talismans donnent 0 de AR (cuir normal, nordique, géant)

Merci !

**Comment by ElusivePanda** [comment]
Est-ce que tu as créé des nouveaux talisman ou tu utilises ceux existant?

**Comment by Hazlith** [comment]
Hier soir j'ai créé trois nouveaux talismans oui. 
1x niv 1 en peau nordique
1x niv 1 en peau de géant
1x niv1 en peau normale

**Comment by ElusivePanda** [comment]
Lorsque tu fais le test, est-ce sur toi-même? Et si oui, combien de dex a ton personnage?

**Comment by Hazlith** [comment]
20 de DEX avec Kahgi et 2ième ptit truc. J'ai été capable d'équiper mon propre talisman crafté.

**Comment by ElusivePanda** [comment]
Ah, voilà, avoir moins que 50 de Dex donne un malus de AR. À 20, tu vas avoir effectivement 0 de AR.
Je close, si le problème est toujours présent, laisse un commentaire et je vais réouvrir.
