### ISSUE TITLE
FISHING - Les truites ne donnent plus d'écailles?

### ISSUE THREAD

**Issue by pmduguay** [Eowymos/TerraUo#141]
Hier soir j'ai coupés 576 truites d'un coup et ça m'a fait 1152 filets et aucun écaille. J'ai cru que celles-ci avaient été _nerfed_, mais Eowymos semble dire que vous ne l'avez pas changé. Bug? Vous me devez 576 po! ;)

**Comment by naazz1992** [comment]
Es-tu sûr qu'elles ne sont pas tombé par terra à cause du poids? Ça m'arrive souvent.

**Comment by ElusivePanda** [comment]
Je suis incapable de reproduire le problème, vérifie de nouveau avec une ou deux truites S.V.P.

**Comment by Nebelpfade666** [comment]
Ça a dû tombé à terre, trop lourd.

**Comment by pmduguay** [comment]
Ah, merde, je n'avais jamais eu ce problème! Désolé du dérangement.
