### ISSUE TITLE
Flam Strike "Pet/prout sound"

### ISSUE THREAD

**Issue by Wruntak** [Eowymos/TerraUo#142]
Bonjour, bonsoir, je sais pas si c'est normal mais quand on réussit un flam strike, l'animation est belle et bien présente, mais il y a un bruit de "pet" au début de l'animation du sort, je sais pas si c'est voulu :)

**Comment by ElusivePanda** [comment]
C'est le cas de beaucoup d'autre sort aussi, tel que la majorité des sorts dans la branche Nature.
