### ISSUE TITLE
Reroll Guilde

### ISSUE THREAD

**Issue by NorNorr** [Eowymos/TerraUo#145]
Lorsque votre ancien personnage etait dans une sphère quelconque de son ancienne race il rest membre sous son nouveau nom dans celle-ci apres le reroll

**Comment by Krashto** [comment]
Le systeme de reroll sera retouché au complet

**Comment by animatrice-hanson** [comment]
Corrigé lors de la dernière maj : 
"- Un PJ doit quitter toutes ses guildes avant de pouvoir faire un Reroll."
