### ISSUE TITLE
Sort Dispell ne fonctionne pas avec les buffs/debuffs

### ISSUE THREAD

**Issue by MaasUO** [Eowymos/TerraUo#147]
Voilà, pour que ce sort soit réellement intéressant il devrait pouvoir retirer les buffs/débuffs qui affectent une cible.

**Comment by chatpoter** [comment]
Normalement dispel dans UO est fait pour faire disparaitre les summon / familier/ creature  invoquer.
Il pourrait être intéressant qu'il retire les malédictions effectivement.

**Comment by Krashto** [comment]
Ce serait beaucoup trop fort
