### ISSUE TITLE
Balance des summons

### ISSUE THREAD

**Issue by Mektor2** [Eowymos/TerraUo#150]
Bonjour,

J'ai beaucoup expérimenté avec les summons 1 à 5 depuis la MAJ.

À mon humble avis, le dégât d'Esprit animal a besoin d'être nerfé légèrement (20-25%?). Compte tenu de leur survivabilité, du fait qu'ils prennent seulement 2 slot de familier et ne requièrent que 2 en invocation, ils sont trop forts.

**Comment by ElusivePanda** [comment]
Les summons été déjà été rebalancé, à voir très bientôt. 
Je close pour l'instant, réouvrir un issue si quelque chose cloche suite à l'update.

Merci.
