### ISSUE TITLE
Protecteur - AP Protecteur

### ISSUE THREAD

**Issue by ETGLap** [Eowymos/TerraUo#154]
Protecteur.

Je pense que cette classe devrait être revu, du moins niveau PvE. Je n'ai pas le feeling d'être un Tank, l'habileté protecteur ne semble rien donner de plus que l'accès à des spells. Je l'aurais vue, du moins, booster le AR en PvE OU monter  le nombre de PV (je donne des exemples) pour le nombre de point dans protecteur. Le spell qui fait ceci est BouclierGardien et personnellement je trouve qu'il est cherrant pour le peu de AR reçu.

Je ne suis pas un berserker qui à des points dans tuer de monstre, je mange donc plus de dégât qu'eux en PvE. Ils sont plus Tank qu'une classe qui devrait être Tank. J'ai fait plusieurs test en PvE, Guerrier familier et se fut nerfer, Guerrier invoquer et se fut nerfer. Cela me permettait d'avoir un "tank" pour que je puisse faire un peu de Dps. Maintenant que ce n'est plus possible, je mange donc 100% des dégâts et n'a pas se feeling d'être un tank... je tombe plus rapidement qu'un berserk qui dlui, devrait frapper plus fort et avoir plus de pv niveua temporaire (quand y tombe berserk) plutot que permanent. 

Malgré mon inexpérience pour comparer réellement, j'ai quand même se feeling qu'il est non seulement soso en PvP mais soso en PvE. Est-ce vraiment une protecteur? Si ne peu survivre a plus de 6-7 coût d'un Hourtag, peut-il vraiment protéger?

Si vous avez des réponses, des informations secrète "cacher du jeu", stats inconnu, que je ne vois pas avec la mécanique du jeu qui me permettrait d'avoir un tout autre regard, merci de m'en informer. Je soulève la classe car je la joue, oui, mais je la compare à d'autre jeu dont un tank excite et je le trouve moyen résistant dans UO. 

Je ne pointerai pas d'autre classes pour faire des comparaisons, mais personnellement, il manque une saveur au Protecteur qui lui donne le feeling de Tank. Aider moi à voir plus claire, merci.

**Comment by pmduguay** [comment]
J'attends de pogner ma classe 3 en fin de semaine, mais j'ai le même feeling que toi. Je vais élaborer un texte avec des pistes de solution dès que j'aurai testé avec l'armure de plaque et le sort Stun. Pour l'instant, la classe est en tout point inférieur au tueur de monstre. Je frappe 20 dégâts de moins ET les monstres me font plus mal qu'un TdM de même niveau. J'anticipe être déçu de la différence entre Chainmail et Plaque aussi, puisqu'aucun forgeron ne peut faire de Full Plate exceptionnel avec un minerais de T3 tandis que les Chain, oui, ce qui rend, pour l'instant, l'avantage de la Plate insuffisante par rapport au gain majeur en damage reduction que procure les PAs en TdM. En plus que le site a affiché longtemps la mauvaise capacité en mélée, ce qui est était un argument pour la classe. Maintenant que je sais que je vais garder la même arme entre les niveaux 29 à 71, ça vient ça aussi s'ajouter aux nombreux débalancements que j'ai pu noter. La différence de 20 dégats que j'avais va sans doute se transformer en 40, quand les TdM auront leur capacité 4.

Bref, je vous reviens avec un texte plus étoffé dès ce week-end lorsque j'aurai atteint la classe de Gardien.

**Comment by pmduguay** [comment]
Alors c'est fait, je suis classe 3 : Gardien. Voici mes stats, pour référence:

Force: 90
Dex: 50
Int: 50
Con: 90 (345 HP)
Viva: 20
Sag: 50 (150 de mana)

J'ai une armure de Plaque en Mythril (T3, le max accessible) à moitié excep (aucun forgeron ne peut les faire totalement except), ce qui donne 132 d'AR (casque et bouclier compris). Si tout était except ça ferait 140. 156 avec le max'd bouclier gardien (ou 164 si tout était except). J'ai aussi 12 de PA Protection, donc accès à tous les sorts. J'ai un Gourpic avec 65 de Mace Fighting, Parrying, Tactics, Anatomy, Healing...

Je frappe un Morgalin d'environ 49-52, et eux me frappe d'environ 15-17. Mon bouclier gardien, mon Sacrifice et moi Stun coûtent 40 de mana.

À titre comparatif, une Brute a 119 d'AR (son armure peut être fait 100% except dès maintenant, ce qui n'est pas le cas de la plate) et peut porter une catégorie d'arme supérieur, en plus de ne pas avoir à monter Sagesse, ce qui lui ajouter du DPS encore plus.

- Avec 150 de mana, je manque très souvent de mana. Celui-ci remonte très lentement, et du fait que je dois enlever mon bouclier pour soigner, ça fait que je dois constamment recaster mon bouclier gardien. Tout ça tenant compte que j'ai du sacrifier 30 de stats que j'aurais pu mettre dans Dex et Intel pour améliorer mon DPS.

- À part bouclier gardien, tous les autres sort n'ont aucune utilité en PvE. Je comprends de plus en plus qu'il s'agisse d'une classe beaucoup plus PvP, mais les occasions de PvP sont extrêmement rares dans le cas d'une race neutre comme les Kardars. Je vais donc parler pour ce que je connais, le PvE: .sacrifice donne 40 HP pour 40 HP perdu. Étant donné que le Protecteur devrait être le tank, je ne comprends pas comment il peut en bénéficier, puisque c'est lui qui prend les dégats. .taunt permet de changer de cible, mais honnêtement, avec le système de combat d'UO, il suffit de se mettre dans les coins du monstres pour arrêter de se faire cibler, donc c'est beaucoup plus efficace pour changer de cible que d'avoir un sort qui coûte du mana. Finalement, le .stun dont j'avais grand espoir, ne sert qu'à freeze pendant 10 secs. Si on attaque la cible, il defreeze. Ce qui rend le sort uniquement utile dans des situations de fuite ou pour sauver quelqu'un. Bref, les 12 PAs en protection donnent 24 de AR (aussi bon en PvP que PvE) et une certaine utilité spécifique en PvP (qui peut s'avérer très très utile, j'en conviens).

- Donc, par rapport à un TdM qui a 119 d'AR, j'ai donc 37 AR de plus. Ce 37 d'AR de plus n'égale pas (je suis pas mal certain) le _damage reduction_ que procure 12 de PAs en TdM contre les monstres. Donc, pour résumer, je tank moins, et je frappe presque 40% de moins (à confirmer) contre les monstres. En PvP, j'imagine que je l'emporte haut la main, mais en PvE, il n'y a aucune comparaison. Je vais frapper du même nombre de dégâts entre les niveaux 29 et 71, ce qui est un énorme _gap_. Évidemment, ça l'aurait été moins pire si Gardien donnait 4 de _melee_ comme il était écrit sur le site depuis le début.

Voilà mes observations! :) Mon perso est vraiment plus orienté RP, et j'ai choisi cette classe strictement en fonction de ça, mais j'aurais cru qu'elle serait quand même un peu plus utile. Peut-être que ça pourrait être légèrement tweaked? Quelques pistes de solutions: 

- Faire que l'on peut se guérir sans enlever son bouclier;
- Faire que les points en sagesse OU les PAs en Protecteur augmente la _mana regeneration_;
- Remettre la capacité _melee_ 4 à partir de classe 3;
- Donner la capacité d'armure 4 à la classe 2;
- Faire que .stun empêche l'ennemie d'attaquer pendant x sec.
- Rendre .sacrifice meilleur, genre perdre 20 HP pour en donner 40 HP.
- Changer le sort .taunt et .tauntall par quelque chose d'autre ou bien augmenter son range, au moins.

Mes 2 cennes! 

Au plaisir et merci :)

Turin

**Comment by hysil** [comment]
Je suis dA'ccord, je viens d'ailleur de changer classe a cause de cela, je pensais en effet faire un tank en pve meme avec 4 point en tdm j'en étais loin... enfin si cest vraiment pvp ca peut aller mais bon étant Drakan... 0 utile haha. donc bien content de mon changement de classe

**Comment by animatrice-hanson** [comment]
Les habiletés des protecteurs a été revu en entier
