### ISSUE TITLE
Sorts d'AOE sont tous désormais inutiles 

### ISSUE THREAD

**Issue by MaasUO** [Eowymos/TerraUo#155]
Avec la récente mise à jour, les dégâts des sorts d'AOE semblent fixés à 8-9, il y a explosion qui va même plus bas encore. Tout les sorts de masse à l'exception de tremblement (sort #1) ne servent plus à rien. Je soupçonne même que vortex est désormais aussi mauvais que tout les autres, mais je ne peux pas le tester celui-là! Sur une cible unique, le dégât semble "correct" mais dès que tu utilises le sort pour sa raison d'être (attaquer plusieurs cibles) ça devient un gouffre en mana/regs/temps.

**Comment by DorianDeBeauffort** [comment]
Le degat devrait pas autant se diviser pour devenir mauvais.... Ca devrait etre un gros degat sur cible unique et faire comme UO de base et doubler voir tripler les degat quand plus que 2-3 cible et le diviser par le nombre de cible avec un degat minimum pour pas que ca devienne rédiculement mauvais.

C'est un des avantages de la classe élémentaliste ce serait bien que cela serve a quelque chose d'affecter plus d'un ennemi
