### ISSUE TITLE
Detachercheveux et les cheveux en général

### ISSUE THREAD

**Issue by MBRND** [Eowymos/TerraUo#158]
- Lors qu'on attache nos cheveux avec une ficelle. Si on change notre coupe de cheveux après, la couleur de nos cheveux devient le default blanc.

- .Détacher cheveux ne fonctionne pas. Il faut acheter des ficelles en quantité et reseter nos cheveux a "long"

- Je pense aussi qu'il y a un bug que j'ai pas encore trouver comment reproduire qui reset mes cheveux a une couette blanche (donc changement de couleur ET de coupe).

- QoL Change que je pense serai utile: Faire un menu de coupes lvl 0 avec les 3 coupes suivantes: Long, Queux de Cheval, Crane rasé. Rendre les LvL 0 accèssible a tout le monde via l'outils de coupes de cheveux. Retiré la commande .detachercheveux et les ficelles completement.

- La coupe Mohawk et Tresse Courte sont inversés.

**Comment by Krashto** [comment]
La ficelle sera fixé, nous savons deja quel est le probleme
