### ISSUE TITLE
Skin Visuel

### ISSUE THREAD

**Issue by kean34** [Eowymos/TerraUo#160]
J'ai choisi rapidement le skin d'entré 'elf' sur le serveur. Ce qui semble m'apporter plusieurs problème visuel pour moi et les autres.  On ma dit que de changé de 'elf' a 'human' regèlerais le problème? 
Je cru que c'étais un problème dans mon installation. ce qui n'a rien changé après plusieurs tentative de réinstaller 

Ce n'est vraiment pas un urgence =) seulement, si vous avez idée d'un façon de le regler facilement

Merci 
Bon jeu! 

Joueur: Kean'ef Yavanaa

**Comment by Krashto** [comment]
Il faudrait voir avec un GM pour te changer ta race en humain, te tuer et te rez, ça devrait "fixer" le probleme

**Comment by Krashto** [comment]
Est-ce que ton probleme est regler?

**Comment by Krashto** [comment]
Derniere tentative. Est-ce que ton personnage souffre toujours de ce bug ou c'est regler? Je ferme le sujet dans 24 heure

**Comment by kean34** [comment]
Je fais la demande a l'instant auprès d'un Gm.  je vous confirme bientôt. merci

**Comment by kean34** [comment]
Réglé merci!!
