### ISSUE TITLE
Classe Rôdeur - Pet / Pièges

### ISSUE THREAD

**Issue by DraevenUO** [Eowymos/TerraUo#162]
Salut,

Petit commentaire sur la classe rôdeur à laquelle j'ai récemment re-roll entre autre pour le pet et les pièges. 

Le pet fait 1 de dommage actuellement aux Ettins. Ça me semble plutôt bas comme dmg pour un Pet de classe. Ne tough pas non plus plus qu'un Mob de cette classe actuellement. 

Les pièges ne sont pas actifs présentement, ce qui diminue grandement l'appeal de la classe. Je me demandais s'ils allaient être scripté someday.

Merci!

**Comment by ElusivePanda** [comment]
Les pièges ont été retiré car ils sont très difficile à balancer techniquement, le pet est la feature qui prend sa place.
Son dommage très léger est voulu comme il possède beaucoup d'HP et un "taunt".

**Comment by Krashto** [comment]
Nous comptons possiblement offrir des pieges au chasseur, mais il faut bien playtester la classe avant. elle est deja tres forte. un Taunt c'est magique. Je clos pour l'instant.
