### ISSUE TITLE
Herding

### ISSUE THREAD

**Issue by Ehthanas** [Eowymos/TerraUo#163]
J'ai joué un peu avec le herding et j'ai trouvé des choses  : 

Le skill utilise animal lore et est utilisable avec le bâton classique herding et animal lore monte avec chaque utilisation d'essait .
Il est possible d'utiliser le skill a bas niveau (20%) sur des montures de joueurs ou animaux tamé.
Si un animal doit se rendre sur une destination et qu'il y a un obstacle , celui ci va juste tourner autour ( ex: cibler un cheval et se cibler , le cheval va tourner autour de toi car la cible au sol est inateignable. ) ou bugger et se déplacer près de l'obstacle ( ex:  mouton cible l'autre coté d'un enclos , il va rester coller sur la cloture et marcher de gauche a droite indéfiniment. )

**Comment by animatrice-hanson** [comment]
Quelques changements à ce sujet pour la prochaine patch, entre autres, herding est remplacé par animal taming, on ne peut plus utiliser le skill sur des montures de joueurs ou animaux tamés, le reste est prévu pour rester tel quel.
