### ISSUE TITLE
Balancement des Ossements pour les Armures d'Os

### ISSUE THREAD

**Issue by GarukWyrmog** [Eowymos/TerraUo#166]
![Os balancement](https://user-images.githubusercontent.com/67527780/87610543-e9d47400-c705-11ea-842e-d3cc97f72cbb.png)

Je vous laisse ce message car je pense qu'il y a un problème au niveau des ossements que j'ai détaillé dans le tableau ci dessus.

Je vous apporte les différentes conclusion que j'ai établi bien que la difficulté de certains monstres pourrait être ressentit légèrement différemment par certains joueurs mais c'est un constat général.

Aussi au niveau des armures d'os je trouve regrettable qu'une armure de tiers supérieur soit égal en terme d'AR à l'armure inférieur en except. Cela donne l'obligation d'avoir une armure excepte ou rien (il vaut mieux rester à l'armure inf except tant que l'artisant ne sais pas faire l'armure supérieur except). 
Même si ce n'est pas grand chose je pense qu'une différente de 6 à 10 d'AR pourraient marquer le coup et changer la donne.

**Comment by ElusivePanda** [comment]
Le tableau est erroné en plusieurs points, donc je ne commenterai pas cette partie, sauf dire que le niveau des ossements, cuir, etc à été ajusté pour que tout les matériaux du même tier unlock sur le même palier de skill. Oui certain matériaux sont plus rare que d'autre, même s'ils donnent le même AR. Certains voudront quand même avoir une couleur en particulier.
Une armure non except est plutôt un échec qu'une qualité régulière.

**Comment by GarukWyrmog** [comment]
Effectivement je n'avais pas vu que le gating des craft avait été ajusé il y a 4 jours. j'avais fait le tableau avant et prit un peu de temps a le poster: 

Il n’empêche que le fait de dire qu'une armure normale soit un échec d'armure except me laisse très perplexe...

Les Os de morcith laissé tier 1 alors que l'on ne les attrape uniquement sur des mort vivant spéciaux et bien coriace a soloter fait que cette belle armure sera uniquement utilisé pour l'apparat... fort domage.

Et on parle des 100 minerais différents alors qu'on a que 10 os et que le centirius n'est pas disponible?

Pour en venir également aux cuirs, certain cuirs ne sont pas encore disponibles (pas le monstre implantés) alors que des monstres de tiers supérieur sont déjà là. 
Les cuir qui sont non implantés ne seront même pas encore là qu'ils seront déjà dépassé. Ca fait sauter les étapes.

Je ne suis pas en train de râler au pleurnicher ou je ne sais pas quelle expression il me sera donné mais je souhaiterai juste participer au fait de donner au craft des ossements ou des cuirs un sentiment d'achever.

**Comment by HoboKingCarpenter** [comment]
"Et on parle des 100 minerais différents alors qu'on a que 10 os et que le centirius n'est pas disponible?"

38 métaux (en prenant en compte les Alliages qui doivent etre crafter ) Qui sont divisé à coup de 7 - 8 métaux de meme tier ? Exemple : Fer, Cuivre, Bronze, Boréal, Argent, Chrystelliar, Lithiar , tous des tier 1 qui donne pas de bonus, outre la couleur VS os normal ( compte tenu que selon ton tableau a partir de Reptilien il y a un bonus d'AR ?)
  
Sinon, pour ce qui est des métaux tier 3 on parle de 50 - 55 Mining les sortir ( a ce que j'ai vu so far) puis probablement minimum 60 pour les fondre. Encore là, ca semble suivre les chiffres "pré maj" de ton tableau.  

Va rester a voir vers la fin des classes si les Alliages font ou pas une enorme différence, mais en meme temps, au nombre de ressources qui vont être nécessaire pour un Kit en alliage Complet, faut esperer que ca aie un avantage. 
Surtout que rien nous dit que les Métaux "tier 5" ( equivalent aux os anciens) seront pas uniquement des alliages, Donc probablement aussi chiant sinon plus à ramasser que les Os anciens.

**Comment by Krashto** [comment]
Je clos le sujet, pour ce qui est du AR donner par les capacités vs le tier, il faut comprendre que toute la base du PVP et du PVE est le AR. la moindre modification à cette valeur, c'est le systeme au complet qui débarque. C'est la dernière valeur que nous souhaitons toucher. Le fait d'obliger d'avoir de l'excep, c'est pas vraiment un probleme. ça ne prend que quelques jours souvent entre "Je peux crafter l'armure" et "Je vais te la faire excep"
