### ISSUE TITLE
Vigie Val' 

### ISSUE THREAD

**Issue by UnKreated** [Eowymos/TerraUo#167]
La vigie de Val'Arak semble fonctionner sur d'ancien point qui n'ont plus rapport plus a l'ouest et au sud. Un Gorlak peu entrer en ville par l'entrer droite et on le saura jamais.

**Comment by karlsc** [comment]
+1
Nous avons quelques fois des gens qui abusent de ce problème, et avec la situation présente IG, il serait bien que celle-ci soit fixé une bonne fois pour toute.

**Comment by Nebelpfade666** [comment]
Ça fait déjà deux mois qu'on a avisé en plus...

**Comment by Ariakan82** [comment]
Je plussoie !

+1 ... surtout avec les attaques répétées dernièrement.

**Comment by Ariakan82** [comment]
Je plussoie !

+1 ... surtout avec les attaques répétées dernièrement.

**Comment by Krashto** [comment]
![image](https://user-images.githubusercontent.com/67296022/88115825-11539280-cb85-11ea-9184-bf21115c0ec1.png)

**Comment by Krashto** [comment]
faut etre dans la ville pour déclencher la vigie encore
