### ISSUE TITLE
Chêne soigneur et Healing

### ISSUE THREAD

**Issue by pocloutier87** [Eowymos/TerraUo#168]
J'ai lu sur le discord par Eow que Healing devrait avoir un impact sur les sorts de healing. Cependant, entre 0 et 38% healing je ne vois pas encore d'impact sur chêne soigneur. Rien sur la quantité par tic, ni la quantité de tic.

Je vais refaire le test quand j'aurai les livres pour dépasser le 60%+ mais peut-être est-ce déja suffisant pour déterminer si 1) c'est relié ou non au sort et 2) est-ce que le scaling est prévu pour des valeurs plus hautes.

Merci de confirmer !

**Comment by ElusivePanda** [comment]
Healing s'applique sur les sorts de healing du thaumaturge, mais pas sur chêne soigneur de mémoire.

**Comment by pocloutier87** [comment]
@ElusivePanda Est-ce que ce serait possible de confirmer ce qui s'applique au chêne soigneur alors ?

Magery
Intel
Nature
Druide/Necromancien (classes)
Capacité magie
Autre skill?

Merci beaucoup !

**Comment by pocloutier87** [comment]
@krashto @Eowymos Tentative de tag pour une réponse à mon commentaire ci-dessus. Merci !

**Comment by Krashto** [comment]
Je ne connais pas assez les détails de chaque sort pour répondre

**Comment by ElusivePanda** [comment]
Les mêmes skills que pour les autres sorts. Donc oui ceux que tu as listé. Eval int scale les sorts aussi.
À noter qu'il sera rebalancé dans une prochaine Maj.
