### ISSUE TITLE
Bug Arm/Disarm et Last Object/Last target sur UOClassic. 

### ISSUE THREAD

**Issue by Purps32** [Eowymos/TerraUo#172]
Lorsque j'ai commencé a jouer a Terra, j'utilisais le client avec le nom Terra et ce jusqu'à la dernière mise a jour. 
Je n'avais aucun problème avec arm/disarm ou les macros last object + last target, ils fonctionnaient, comme ils ont toujours fonctionné sur UO. 

Depuis que j'ai fait la dernière mise a jour et que j'utilise le client UOclassic Arm/Disarm bug a mort et ne fonctionne plus si tu fais l'erreur de caster un sort, ça te dé-équipe ton arme comme ça devrait, mais en refaisant le macro, rien ne se passe. 
C'est terriblement agaçant en combat surtout quand tu joue sans souris sur un portable comme moi. 
Le système semble se souvenir de la main qui n'était pas équipée (du genre il oublie le arm/disarm de la main dans laquelle mon arme était seulement si j'invoque un sort).
Et le même système bug aussi lorsque tu veux changer d'une arme a l'autre dans la même main. 
Par là je veux dire que si j'ai déjà mis une lance en arm/disarm, si je veux la changer pour une dague en arm/disarm, le système essaie plutôt de ré-équiper la lance alors que j'ai la dague en main. 
Et il y a aussi le fait que au lieu de désarmer, ça fait flasher l'arme et dit "you must wait before you perform another action" en boucle. 

Last Object Last Target quant a lui, le problème c'est que comme tout les autres macros (incluant last skill last target) ne le font pas comme ça l'a toujours fait depuis mille ans c'est a dire, tenir le bouton. Faut re-cliquer le macro une 2e fois pour faire last target, avec un skill ça marche, donc si j'ai animal taming + last target, ça le fait en deux clics, mais si j'ai last object last target, il me redemande sans cesse sur quoi je veux utiliser. 

Je ne connais pas Razor du tout (on m'a dit de prendre ça mais j'ai une erreur quand je dis quel data utiliser donc fonctionne pas) et de la vieille école j'utilisais UOLoop mais sur UOClassic, Uoloop ne démarre pas quand je fais start et avec ces bugs de macro, il est complètement inutile de toute façon pour plusieurs trucs. Pas moyen de pratiquer un skill sans cliquer partout non stop à moins d'acheter un livre et c'est ennuyant parce qu'en mode RP c'est le fun de pratiquer. 

Merci!

**Comment by chatpoter** [comment]
Il faut des wait entre tes commandes , du genre last object , wait for target, last target.
Pour ce qui est du disarm , je peu pas dire , mais le principe semble un peu similaire dans le pluspart des macros que j'ai tenté de faire.

**Comment by Krashto** [comment]
Ajoute "Wait for target" Entre ton last object et last target

Classic UO gere les macros trop rapidement, et donc, avant que ton jeu aie le temps de faire pop la target, la macro est deja executé
