### ISSUE TITLE
une nouvelle commande ? le .Flip

### ISSUE THREAD

**Issue by GalvarCorbac** [Eowymos/TerraUo#177]
dans certains autres server, j'ai vu qu'il existait des commandes pour faire flipper les objets en jeux (meubles, armes, items en tout genre etc...)  je me doute que la commande est déjà accessible aux GMS par ce qu'ils peuvent le faire IG, je me demandais si c'étais possible de le rendre disponible pour les joueurs ? ca aiderais les gm surtout pour les objets a locker en jeux!

**Comment by Nebelpfade666** [comment]
Je pense que mettre disponible le _house decoration tool_, serais nécessaire ;)
