### ISSUE TITLE
Coiffure - Aucun

### ISSUE THREAD

**Issue by Nebelpfade666** [Eowymos/TerraUo#179]
Ajouter l'option : Aucun
Pour retirer les cheveux ou la barbe.

**Comment by Mektor2** [comment]
Je crois que tu peux le faire avec une paire de sciseaux normaux utilisés directement sur ta tête?

**Comment by Nebelpfade666** [comment]
> Je crois que tu peux le faire avec une paire de sciseaux normaux utilisés directement sur ta tête?

Non, on a essayer et ça marche pas.

**Comment by ElusivePanda** [comment]
Prochaine maj, oui, avec les scissors régulier.
