### ISSUE TITLE
Couleurs des Peaux/Ossements transférables? [Suggestion]

### ISSUE THREAD

**Issue by MaasUO** [Eowymos/TerraUo#181]
--
Puisque  tout le monde évolue tranquillement vers les meilleurs cuirs et les  meilleurs ossements, on se retrouvera bientôt tous pareil. C'est déjà  franchement le cas avec le cuir d'ophidiens, pour demeure compétitif, il  faut avoir ce qu'il y a de mieux et bien souvent ces cuirs/peaux ne  viennent pas en plusieurs variétés de couleurs. Je propose donc un  "extracteur" de couleurs afin d'extraire admettons la couleur bleutée du  cuir marin pour pouvoir l'appliquer sur une armure de cuir ophidien. Ça  ne change pas le travail technique qui a été réalisé mais ça ajoute un  plus de variétés esthétiques.

**Comment by animatrice-hanson** [comment]
Depuis le nouveau système d'alliages de cuirs et d'os, tous les tiers ont plusieurs couleurs différentes ce qui permet maintenant un certain choix. Ajouter de nouvelles ressources (donc plus de couleurs encore) est plus une solution que l'équipe technique aimerait entreprendre.
