### ISSUE TITLE
Alliages

### ISSUE THREAD

**Issue by Jobarco** [Eowymos/TerraUo#182]
Bonjour.

J'ai 9 de métallurgie et 65 de blacksmith/ming.

Still, ca indique 0% de chance de réussir de l'alliage.

Est-ce normal ? Merci.

**Comment by Krashto** [comment]
As-tu "Lingot de fer" de choisis en bas?

**Comment by Jobarco** [comment]
Tu as raison ... Ça règle le problème dès qu'on choisit fer. Est-ce que c'est normal ? Merci encore.

**Comment by Krashto** [comment]
Oui c'est normal, lorsque tu n'as pas le bon lingot de choisit, le jeu calcule comme les armures (Bref, augmentation selon le minerai choisit).
