### ISSUE TITLE
Un .decrire

### ISSUE THREAD

**Issue by NChab** [Eowymos/TerraUo#184]
Allo!

Une commande qui rajouterait -beaucoup- de jeu. C'était utilisé sur Crépuscule. C'est essentiellement une commande qui ajoute une description personnalisée aux objets. Ça permettrait d'ajouter des détails sur par exemple des vêtements, les effets Roleplay d'une potion, une peinture craftée etc.

Merci beaucoup! :+1:

**Comment by Eowymos** [comment]
Vous pouvez utiliser la commande .renommer
