### ISSUE TITLE
Locker des objets pour les joueurs

### ISSUE THREAD

**Issue by FlaminBear** [Eowymos/TerraUo#189]
Ce serait très bien de pouvoir locker des objets en tant que joueur, par exemple pour les évents créé par les joueurs justement (Fêtes avec des décorations, tables pour le commerce, boites cachées sur la map, etc)

**Comment by animatrice-hanson** [comment]
Ce n'est pas dans les plans de l'équipe de donner accès à toute la map à tous les joueurs. Par contre, le nouveau système de Knives' Houses permet de créer des zones de type "Maison" à n'importe quel endroit sur la map static. Ces zones pourront être mises en location par les joueurs et ils pourront ensuite jouer dedans comme une maison normale (Locked down, Secure, etc).
