### ISSUE TITLE
Hiding

### ISSUE THREAD

**Issue by Krashto** [Eowymos/TerraUo#19]
Possibilité de Whisper en étant hide
Possibilité d'Emote en étant hide
Possibilité de se reveal à un/des joueurs du party
(La permission doit se retirer si le joueur quitte le groupe)

**Comment by ElusivePanda** [comment]
La possibilité de whisper/emote à été implanté, est-ce qu'on veut la feature de se reveal à un joueur?
Soit un .reveal avec une cible qui te rend "dh" au joueur cible.
Soit un reveal automatique à ton party.

**Comment by Krashto** [comment]
Il manquerait seulement la possibilité de se reveal avec .reveal, le reste est complet

**Comment by Legareto** [comment]
Ce billet n'est pas déjà réglé? Il y a la commande suivante sur le site :

.reveler  -- Permet de se révéler à une cible en restant caché.
