### ISSUE TITLE
.pet svp confirmer abus ou non. Release = Full health

### ISSUE THREAD

**Issue by SaelMir** [Eowymos/TerraUo#191]
Salut ! À valider si Abus. Si c'est pas compréhensible plus bas, svp venir me demander via discord :)

Je suis rodeur ; le .pet est une bonne manière de tank, c'est pas mal la seul chose efficace si nous ne voulons pas toujours voir nos familiers décéder et toujours pleurer nos morts :P 

Hier j'ai réalisé que nous pouvions ''Release'' le pet et refaire .pet immédiatement. 
Lorsqu'un de nos pet décèdes, il y a un timer avant de réutiliser le .pet, mais si nous faisons disparaitre le pet avec ''release'' et qu'aucun n'est mort ; la commande .pet est utilisable.

Donc j'ai 10 de familiers, je peux avoir 2 pet.
Séquence
.pet 1x
.pet 2x 
pet1 10% vie < Release < .pet
pet 2 continue de tanker < 10% vie < release < .pet
pet 1 prend la relève < 10% vie < release < .pet
Etc

Solution : 
1. Accepté par l'équipe. En Solo c'est fort, mais pas assez pour dominer les ophidiens, orgre, géants etc, toutes les créatures qui nécessitent un vrai groupe pour dominer. Les temps de respawn des MOB sont rapides donc on se faire rapidement prendre.
2. Empêcher utilisation .pet lorsque en combat actifs.
3. Avoir 4 commandes .pet ( .pet1 .pet2 .pet3 .pet4)
- Mettre un timer sur chaque .pet comme à la mort, mais aussitôt qu'il est casté, pour éviter la séquence rapide.
- Le faire en se moment limiterait l'apparition d'un 2 et 3 ieme pet. 

Ils sont solides, mais pas devant des mobs qui en valent la peine (et c'est normal, on est max classe 3). 

Donc c'est voulu ou bug abus ?

**Comment by SaelMir** [comment]
@Eowymos

**Comment by Krashto** [comment]
C'est un bug abus. le timer devrait aussi s'appliquer sur le release. L'abus de cette facon de faire sera traité comme tel.
