### ISSUE TITLE
Problème alliage, deuxième prise

### ISSUE THREAD

**Issue by Jobarco** [Eowymos/TerraUo#193]
Bonjour! J'ai fait de multiples tests et voici ma conclusion sur les alliages.

Tous les alliages semblent prendre 5 minérais à faire et non 4 tel qu'il est indiqué dans le menu crafting. Quand je rassemble les 4 minérais affichés et que je tente d'en faire un, il m'affiche le minérais manquant. 

Heptazion prend de l'acier qui n'est pas affiché
Bioottite prend de l'agapite non affiché
Océanis prend du Zircoonium non affiché

Et malheureusement, le Pyxorène et l'Heliothope eux, ne veulent pas me dire le 5ieme minerais qui manque. Au lieu d'indiquer "Il vous manque des minérais de xxx sorte" il dit " vous n'avez pas suffisamment de lingots " 

C'est donc un problème double. 

Merci !

**Comment by ElusivePanda** [comment]
C'est un problème d'affichage, le menu n'est pas assez grand pour lister tout les matériaux.

**Comment by Nebelpfade666** [comment]
Ça me marque : "You don't have the required skills to attempt this item."
Ça prend 60% j'ai 65% _*shrugs*_

**Comment by ElusivePanda** [comment]
Les alliages utilisent Mining comme skill et metallurgie comme PA.

**Comment by Nebelpfade666** [comment]
11 en métallurgie ?

**Comment by Krashto** [comment]
Pas 11 non, comme le blacksmith. assure toi que tu aies lingot de fer de choisis en bas.
