### ISSUE TITLE
Classe Rôdeur

### ISSUE THREAD

**Issue by DraevenUO** [Eowymos/TerraUo#194]
Salut, voici quelques constatations personnelles sur la classe Rôdeur. 

Pour info, j'ai changé de classe récemment de Archer à Rôdeur. Mes stats sont 90 STR et 90 Intel. Je suis cappé en Archery, Tactics, Anatomy, Animal Taming et Animal Lore, soit 70 ish. 

- Feature pièges pas activée, feature passage sylvestre et stam bonus ne semblant pas l'être non plus 
- Aptitude Chasseur qui donne 20 HP de plus au Pet de classe par niveau présentement comme seul bonus apparant (et probablement un peu plus de resist)
- Pet de classe qui ne fait aucun dommage. Donc, sa seule utilité est de tanker. À Chasseur niveau 4, le Pet meurt après très peu de hits de Guerrier Troll des Glaces. 
- Le taunt du pet de classe ne donne pas grand chose en solo car tu peux kiter comme archer. De plus, dès que tu as un party dans le sens du monde, tu peux facilement contrôler l'aggro avec le positionnement des players, mécanique pve du jeu oblige. 
- Impossible d'avoir un pet tamable viable car les pets viables sont 8 slots et +, et encore là. Pré Level 60, il faut maxer Familier pour pouvoir avoir le pet de classe et un pet à 8 slots. Pas de place pour un horse. Ce faisant, aucun point n'est allouable ailleurs car TOUT va dans Familier. 
- Dans la situation précédente, même avec 90 d'intel, max familier, je suis de retour à la situation où je manque 3 arrows sur 5 vs des Ogres. La raison de ça est que je ne peux pas mettre aucun point dans Combat au sol si je veux avoir un avantage quelconque au niveau des pets. 
- Pour avoir un build de pet décent, il faut investir largement dans Taming, Lore et Veterinary. On a déjà Lumberjack, Bowcraft, DH et Tracking à monter hors combat. 
- Veterinary ne monte pas en essyant de Rez une créature 
- Une créature morte te suit, mais elle est pas en mode ghost, donc elle bloque le chemin aux autres et n'est pas stablable par la suite. Donc, sans Veterinary adéquat, il faut release la créature et en retame une autre (à 70 ish, un tigre m'a pris 45 minutes à tame environ)
- Un tigre blanc, créature à 9 slots, ne fait rien sur un mob classe 3, puis pour l'avoir, on doit sacrifier trop de notre force comme ranged. Je n'ai pas testé si les pets plus bas niveau répondaient mieux aux commandes qu'un tigre, mais cependant, si un tigre ne fais rien contre des mob classe 3, ça ne vaut pas la peine d'amener des pets inférieurs. À savoir si entraînés ils seront meilleurs, oui probablement. Le constat est post-tame directement. 
- On se trouve donc, à pareil niveau, avoir un liability au niveau des pets (classe ou tamable) et être moins efficace qu'un archer au même niveau, qui lui est à vocation pvp en raison de la différence de classe d'arc et le pouvoir de mettre plus de PA dans la force ranged (tel que CAS). Les pets tamed, comme pet de classe, ne semblant pas donner aucun avantage actuellement pour contrebalancer. 

Qu'en pensez-vous? 

Merci! :)

**Comment by Koukcy** [comment]
totalement pour tout ce qui est la dedans,  j'ai egalement tout mis dans familier pour les animaux, mon grizzli a 8 de slot se fais descendre a 50% de vie par une harpie de pierre...ce n'est simplement pas viable pour 60 Pa investit..

**Comment by chatpoter** [comment]
Je ne peux pas dire pour les trucs de rôdeurs, étant Druide , mais effectivement les animaux tammer qui commence a devenir bon coûte beaucoup de PA  et demande un bon investissement. 

Il sont souvent moins fort que ce qu'une invocation est si on compare les point de familier de chacun et nous limite a en avoir un maximum de 1 (car il coute 8-9).

1 tigre blanc vs 3 earth elemental (9 family slot), la question se pause même pas.

Je ne sais pas concrètement ce qui serait le plus souhaitable pour ajuster tout sa , c'est quand même complexe et comprend plusieurs créatures. (on ne veut pas avoir peur de sortir dans le bois non plus)

**Comment by ElusivePanda** [comment]
Le pet demande un investissement en chasseur pour vraiment briller.
Le pet de classe qui ne sert qu'à tanker est by design, on ne veut pas qu'il soit capable de solo (le pet), le rodeur doit faire le dommage lui-même.
L'aggro est effectivement facile à gérer en groupe, mais le taunt reste une façon d'aider le pet qui peu être plus tannant à positionner.
Investir en pet vs investir en combat personnelle est un choix, c'est by design.
Les features manquantes sont dans le pipeline, mais comme vous savez, on en a beaucoup à faire.


Maintenant, 
Prochaine maj, on a revu le rodeur, une grande partie des problèmes listés ici devrait être réglé. Que ce soit l'investissement en skill ou l'accès aux familiers.
