### ISSUE TITLE
Commandes Mortanyss non fonctionnelles

### ISSUE THREAD

**Issue by ryder2** [Eowymos/TerraUo#195]
Toutes les commandes pour les évolutions ne sont présentement pas fonctionnelles

.faux --> Affiche qu'on doit être faucheur ou bien ange déchu pour la faire même si on l'est.
.necrocheval et .necrodragon --> Affiche : L'aptitude nécessaire pour ce sort n'est pas assez développée. (Doit fonctionner pour chevalier de la mort pour le nécrocheval et seigneur des abysses pour le nécrodragon)
.chauvesouris --> La commande fonctionne si on est cryptique, mais elle ne produit aucun changement (Rien ne se passe, doit être fonctionnel pour cryptique seulement)
.chauvesouris2 --> La commande fonctionne si on est nécro-garou, mais elle ne produit aucun changement. Si on est cryptique, elle affiche qu'on doit être cryptique pour nous transformer en chauve-souris. (J'imagine qu'elle est sensé fonctionné seulement quand on est nécro-garou, à confirmer)

Ajout: Il n'est présentement pas possible de mettre un vêtement en étant vampire. Doit être possible pour vampire force, dex et intel et vampire ancien force dex intel.

Ajout 2: Pouvoir que le vampire et vampire ancien (force dex intel) puissent monter sur un cheval régulier étant donné qu'en jeu, c'est un gump d'humain, ça ne fait pas disparaître la monture (suggestion)

**Comment by ElusivePanda** [comment]
Les chauve souris ont-ils un avantage à être sous cette forme ou est-ce purement RP ?

Quel est la fonction de la faux techniquement ?
