### ISSUE TITLE
Chêne soigneur.

### ISSUE THREAD

**Issue by Bsx-the-Wise** [Eowymos/TerraUo#196]
La nerf est justifiée mais il faut savoir mesure garder.
Cela reste un spell exprémement lourd à utiliser et peut être pris par un adversaire.

En l'état, c'est au mieux un sort d'appoint.
Comme Heal over Time il n'est pas viable.
Un HoT doit avoir assez de sustain pour faire la différence en PvP. (Et je ne parlerais pas des dégats PvE.)
Si une arme médiane tape à X toutes les Y secondes.
Alors un HoT devrait rendre X/2 ou X/3 toutes les Y ou Z secondes. Traditionnellement plus le heal et petit, plus la durée est longue.

A titre comparatif :
En l'état un Fine Lame tape à 35-45 en one handed toutes les 0,8-1.5s secondes.
Une two handed, 50-60 toutes les 2-3s.
Une dague, 20+ toutes les 0.7-0.8s, sans compter le poison, auquel cas on ajoute 12dmg/s x8-9.
**Le HoT ? 5-13hp/s x8-9. Plz...**

Quelques pistes de réflexion :
- doubler la fréquence des tics, petit mais rapides
- doubler le soin 
- réduire "largement "le coup de mana
- AoE ?

**Comment by ElusivePanda** [comment]
Le chêne soigneur a été nerf car il était simplement une meilleurs option que greater heal. 
C'est un sort de sustain, il n'est pas supposé te tenir debout face à un fine lame qui te frappe. 
Nature est une branche complémentaire pour le druide qui est principalement une classe PvM et le necro qui a d'autre sorts complémentaire qui lui permettent de survivre (boost AR, reflect damage, spell leech, etc).

Le nécro va peut-être avoir besoin d'un peu plus de self healing, à voir avec le feedback.

Si le but est de tenir quelqu'un en vie vs un finelame, Defense et Medecine devrait être les options considéré, pas Nature.

Je vais refaire des tests, mais si on augmente le healing, on parle de peut-être 1hp/s de plus.

**Comment by pocloutier87** [comment]
En fait ça recadre le spell. Ce n'est plus un burst heal, c'est vraiment un HoT à lancer rapidement en début de combat ou qui exige de sortir de l'aggro un temps, et perso je pense que j'aime bien l'idée. Selon la cible, l'effet est différent: plus tu as d'armure, plus chaque point de heal vaut beaucoup donc lvl 100 ca peut devenir super efficace sur les guerriers très tanky.

Il est vrai que le sort a plus de contraintes que le greater heal : devoir marcher dessus, risque de caster sur une place où il est inaccessible (petits couloirs avec grands murs ou décorations qui bloquent la vue), peut être pris par un adversaire en pvp, ne fonctionne pas sur les summons/pets, s'étale sur beaucoup de temps maintenant au lieu de burst, reste pas en place longtemps (donc difficile de laisser des "mine-heals" en pvm), scale pas avec le skill healing, valeur par tic varie beaucoup (le minimum fait très mal des fois).

J'aime l'idée d'allonger la durée totale du sort, le rendre moins immédiat que greater heal et recadrer son utilisation/fonction. Je trouve même ça très cool. Je voyais l'idée d'un heal plus fort mais beaucoup moins rapide que greater heal comme une bonne façon de pallier aux limites du sortilège, tout en l'empêchant de carrément remplacer la versatilité et l'instantanéité de greater heal. L'idée étant de rendre les 2 viables à leur manière, et ensemble avoir 2 roles à l'intérieur de la fonction healer : sustain ou burst.

**Comment by ElusivePanda** [comment]
Je peux voir pour réduire un peu la variance des ticks, qu'ils soient plus régulier au moins.

**Comment by pocloutier87** [comment]
Juste pour illustrer les différences (exemples théoriques). 
Je mets les 2 avec le même casting time dans mon exemple pour simplifier.

Chene soigneur : 10 tics total, 8-10 à 14-16 par tic selon magery/intel/classe/capacité magie/skill X. Gros heal au total mais lent.
Total cappé : 150 par heal de moyenne avec les contraintes actuelles, sauf
Durée du chene sans être consommé : 1 minute

Greater heal : instant, 50 à 60 jusqu'à 80 à 90 selon magery/intel/classe/capacité magie/skill healing. Rapide et quand même puissant, pas de contraintes particulières.
Total cappé : 85 par heal de moyenne par cast

2 greater heal = toujours meilleur que 1 chêne au total, mais pour compenser sa flexibilité et rapidité, ca prend 2 casts.

Le meilleur heal reste greater heal, mais le chene soigneur peut être viable quand même et surtout complémentaire à greater heal dans un gros groupe. Le thaumaturge a la capacité de healer rapidement et beaucoup plus en castant plus de spells, alors que les chênes ne se stack pas. Par contre les chênes peuvent quand même soigner plusieurs personnes avec plusieurs casts eux aussi.

À challenger bien entendu ! Juste pour brasser ça ensemble :)

**Comment by Bsx-the-Wise** [comment]
Le mécanique du chène posé au sol est une volonté de faire le champignon d'Albion.
Donc quitte à s'inspirer autant le faire vraiment.

Ce qui donnerait ceci : 
AoE heal lorsqu'un **allié** marche dessus. 
Durée du chène posé : 15-30s.
Radius du heal:  2 tiles. 
Limite à trois joueurs.
Durée du heal : 3-4s. 
Nombre de tics : 2/s ou 1.7/s
Heal/Tic : 15-16-17-18-19-20 en fonction du lvl. 
**Aucune** variance sur le heal
Là on a un gros sustain PvP et PvE. (Oui sur Albion mes HoT healaient à 40hp/s)

Autre option, venant d'Archeage :
Chène soigneur ne depop pas lorsque que l'on marche dessus mais dispose de points de vie. 
L'idéal serait 3hp, tout coup porté à l'arbre infligerait 1 de dmg.
AoE heal lorsqu'un **allié** est proche. 
Durée du chène posé : 10-15s.
Pas de limites de joueurs.
Radius du heal:  3 tiles. 
Nombre de tics : 1/s
Heal/Tic : 8-10-12-14-16 en fonction du lvl. 
**Aucune** variance sur le heal
Là on a un sustain de temporisation, efficace sur un groupe entier. Donnant une utilité aux archers face à la classe en teamfight.

Le heal direct et le heal indirect sont deux options qui ont été testées dans bon nombre de jeux depuis des années.
On y retouve deux grandes distinctions :
- HoT > Direct Heal : parti prit car un heal direct était jugé trop fort. Favorisant les combats sur la durée et la cumulation de HoT.
- HoT < Direct Heal : combo avec heal direct pour en augmenter l'efficacité , 
exemple donc : Si HoT up sur Target alors Direct Heal = Direct Heal + 20%(Direct Heal)

P.S. :
J'ai l'impression que l'idée de ne pouvoir tuer un healer effrait par ici. 
Pour rappel le poison est là pour cela, ainsi que la capa 2 en armure sur le healer qui reste squishy.
N'ayez pas peur de donner des bons heals aux joueurs, cela n'empêchera jamais qui que ce soit de compétent de tuer qui que ce soit. Un heal ça se zone, ça se contrôle, ça ne s'outdmg pas nécessairement.
Si vous êtes curieux, je peux vous envoyer des records de heals à 37k sur un perso à 50k hp là où le joueur normal en a 20k et le hit moyen à 2k-4k. 
**Si les heals ont un cast time, ce n'est pas par hasard. Et ici un delay entre deux spells, qui plus est.**
Si certains ont peur de ne pas pouvoir tout tuer avec une classe dps, too bad. Faites vous des potes comme dans tout jeu en ligne, ce qui par ailleurs est le principal intérêt de ces jeux. Si vous vous basez sur Diablo, vous avez raté une branche.

**Comment by ElusivePanda** [comment]
Ce sont des idées intéressantes, mais ce sont carrément de nouveaux sorts. Je t'invite à poster dans le post de brainstorm pour que cela ne se perde pas. 
Chêne soigneur risque de rester ainsi (hormi ajustement mineur si nécessaire) pour l'instant, beaucoup de classes ont des lacunes qui doivent être vue et ici, ça me semble Ok.

**Comment by Bsx-the-Wise** [comment]
Comme c'est joliment dit.
Vous êtes libre de copier coller, je cède les copyrights.
Cya.
