### ISSUE TITLE
boost alchimique

### ISSUE THREAD

**Issue by Hebius06** [Eowymos/TerraUo#199]
une potion (normale, standard, de 25% de skill) en for, int, dex, etc donne +2 à la skill.
Une potion supérieure (50%) donne un bonus de +3 , et +5 avec 50% de taste ID.

Est-ce normal que l'augmentation soit si peu élevée ou bien un petit bug?

Si c'est volontaire, peut-être envisager d'améliorer un peu ce score serait profitable pour les alchimistes, les rendant un peu plus utile qu'actuellement.

De même, de nombeux objets IG ne semblent pas avoir d'utilité (roche de pierre, huile de poisson, cheveux de trolls, etc). Serait-il possible d'envisager, là encore, de nouvelles potions, permettant d'utiliser ce type d'ingrédients ?

Voilà, c'est tout... pour le moment

**Comment by Krashto** [comment]
un +5 de stats, c'est vraiment pas négligeable. si on fait que les potions donnent +10 ou +20, on vient de completement aller contre notre systeme de stat.

**Comment by Hebius06** [comment]
+3 pour un utilisateur lambda (genre guerrier).  pas grande monde monte taste id :)

Et si je vais plus loin, en craft par exemple, +5 en int, c'est 1,3% de chances de réussite en plus, en passant de 95 à 100, c'est pas foufou non plus :)

**Comment by OromisLorgex** [comment]
Je tiens aussi à mentionner que le Taste ID n'a aucun effet sur les potions de soins, ce qui le rend encore moins intéressant. C'est un bug ou feature?

EDIT : J'sais pas si j'ai dépassé un certain threshold ou si une modification a été faite aux potions, mais la quantité de soins des potions a finalement augmentée.
