### ISSUE TITLE
Revamp du Rodeur

### ISSUE THREAD

**Issue by Krashto** [Eowymos/TerraUo#20]
Terminer l'ajout de la nouvelle feature du Rodeur
(Vous pensiez avoir des détails hein! ahah!)

**Comment by Eowymos** [comment]
Commande .pet et les pièges!

**Comment by Krashto** [comment]
Baisse du gain de AR du pet
Baisse de l'effet du bleed
Les pieges ont une animation, mais aucun effet (Je recois le message par contre)
