### ISSUE TITLE
Ajout pour les classes magiciennes

### ISSUE THREAD

**Issue by Tetine88** [Eowymos/TerraUo#205]
Ça fait un moment que je pense que les classe magiciennes pourrait bénéficier d'un objet qui aurait des niveau a l'image des guerriers, soit des baguettes magique qui pourrait attaquer et dealer des degats ( A moindre niveau que les arcs ) Mais demanderais de la mana en retour.

Les baguettes auraient des niveau et des ''essences'' qui créerait le type de dégat ( Feu, Froid, poison ect )

Le bricoleur serait celui qui fabriquerais les baguettes magiques!

Ça pourrait permettre a certaines classes de mage moin offensif d'avoir une arme ( Thaumaturge ) Ou plus varié ( Necro )

**Comment by HoboKingCarpenter** [comment]
Donc si je comprends bien, tu demandes une arme a distance, qui tappe automatiquement dans le MR (donc usually les defenses plus basses des guerriers / mobs compte tenu que les minerais / cuirs / os donnent aucun AR élementaire) et qui necessite pas de munitions, outre des points de mana ? 

Considérant que la plupart des classes ont uniquement accès a la Fronde / arc niveau 0 pour attaquer a distance (qui viennent tout les deux avec des degats ridiculement bas) ca me semble vachement puissant comme "armes" de mage ...

**Comment by MBRND** [comment]
Nope. Magicien est déjà le top PvE et quasiment top PVP, pas besoin de plus. Le grimoir sert bien de arm/disarm.
