### ISSUE TITLE
Assassina et classes roublards.

### ISSUE THREAD

**Issue by MBRND** [Eowymos/TerraUo#206]
On peu investir en assassina même en étant espion. Ce que je trouvai interessant. Ceci-dit quand on fait l'assassina ca nous dit que seul la classe assassin peu assassiner.

Je propose donc que ceux qui sont "green lighté" pour être assassin puisse investir dans le skill même s'il ne sont pas directement la classe assassin. Je limiterai ca au classes roublardes (eventuellement si ya un Voleur, ou autre, etc)

Ca permettrerai des buils différent avec des options différentes dans les deux classes.

TLDR:
- Si tu veux aller assassin tu doit te faire green lighté
- Si tu vas espion tu a pas besoin
- Si tu vas espion et que tu veux monté assassina tu doit être green lighté
- Si on ajoute d'autres classes roublardes celle-ci fonctionnerai comme espion.

Sinon, enlever l'option simplement au autres classes de monter assassina, ce qui n'est pas le cas actuellement. Je préfère évidemment l'option qui donne plus de choix au joueur.

**Comment by MBRND** [comment]
Le tag "En discution" à été retiré. Est-ce que j'en comprend que l'idée sera integrée? Merci.

**Comment by animatrice-hanson** [comment]
La classe Espion a été revu et la classe Assassin n'est plus.
