### ISSUE TITLE
Sort necro-> Desarm

### ISSUE THREAD

**Issue by Corbeau95** [Eowymos/TerraUo#207]
Liste de sort du nécro qui désarm : 

1-Summon familliar
2-Corpse skins
3-poison field

Je vais ajouter, a mesure que mes niveaux vont monter, les sorts qui ne sont pas inscrit, sont ceux qui ne désarm pas.

**Comment by ElusivePanda** [comment]
C'est normal que les sorts te disarm, tu ne peux pas caster avec une arme dans les mains.
Il y a une seule et unique exception, le sort Calamité et lorsqu'il est actif, tu pourras caster avec une arme dans les mains.

**Comment by ElusivePanda** [comment]
Confirmé avec Eo, le comportement actuel est normal.
Merci
