### ISSUE TITLE
Artwork du jeu d'échecs manquants

### ISSUE THREAD

**Issue by Alckor** [Eowymos/TerraUo#208]
Les pièces d'échecs n'ont pas d'image in game ce qui rend le jeu quasi impossible a jouer. Voir Screenshot en dessous.

J'utilise la derniere version du client qui est sur discord, j'ai deja vérifier et d'autres joueurs ont le même problème.

[https://cdn.discordapp.com/attachments/733304358778699788/736756808068366426/unknown.png](https://cdn.discordapp.com/attachments/733304358778699788/736756808068366426/unknown.png)

Je sais que ce n'est pas très prioritaire comme problème. 

Peut-être retirer le jeu des vendor le temps que ce soit réglé.

**Comment by MissIelenia** [comment]
Fait
