### ISSUE TITLE
La connaissance peinture

### ISSUE THREAD

**Issue by Solid05** [Eowymos/TerraUo#210]
Elle semble buggé car j'ai 8% de chance de faire une toile lvl 1 malgré mes 2 en connaissance peinture.

**Comment by HoboKingCarpenter** [comment]
En fait ca semble etre toute les connaissances qui offre du craft ( sculpture à le meme genre de problème de ce que j'ai vu quand j'ai testé) 

Peut-etre que mettre des explications sur la page des connaissances pourraient aider

**Comment by Eowymos** [comment]
Les chances sont en lien avec la connaissance, aucun skill requis.

**Comment by Solid05** [comment]
Oui mais 14% de chance de reussite avec 6/6 en peinture cest low me semble non? :\
