### ISSUE TITLE
Durabilité bouclier

### ISSUE THREAD

**Issue by Daak999** [Eowymos/TerraUo#211]
J'ai cru remarquer que la durabilité de l'armure semble diminuer lors des combats, mais pas celle du bouclier? J'ai perdu 30 durabilités sur ma ring mail et mon bouclier est encore intact.

**Comment by pmduguay** [comment]
Je confirme, je n'ai toujours pas perdu de durabilité sur mon bouclier.

**Comment by animatrice-hanson** [comment]
Corrigé prochaine maj !
