### ISSUE TITLE
Animation Bâton/Lance/Hache longue

### ISSUE THREAD

**Issue by Wruntak** [Eowymos/TerraUo#215]
Je reviens sur le sujet, après avoir échangé avec plusieurs joueurs  il s'avère que nous sommes très souvent sur la même longueur d'onde. Il faut aussi remarquer que beaucoup des joueurs préfères favoriser un bâton bien particulier la "Canne de Luxe" et cela car l'animation IG se prête plus à un bâton pour s'aider à marcher. Cela est bien dommage, car nous avons la possibilité d'utiliser d'autres bâton, mais l’esthétique visuelle prend le dessus, résultat: ils sont délaissés. 

Ma question est la suivante est-il vraiment compliqué de faire en sorte que les autres bâtons adoptent  la même animation IG quand on marche telle que la  "Canne de Luxe" ? 

Et je pense également que les guerriers utilisant les bardiches, hallebarde ou encore des lances se verront certainement ravis d'avoir la même animation que la "Canne de Luxe"

Je vais donner l'exemple de deux Screens. 

![Bâton move bof](https://user-images.githubusercontent.com/67340950/88923620-4c834f00-d272-11ea-8895-227f45343d0d.jpg)

![Bâton good](https://user-images.githubusercontent.com/67340950/88923646-54db8a00-d272-11ea-92c5-a7fc05620893.jpg)

Merci d'avance.

**Comment by Ezotrix** [comment]
Probablement realigné le baton sur chacune des sprites de l'animation  , c'est pas super compliquer mais plus long que l'on pense. Du moin c'est ma supposition :)

**Comment by Wruntak** [comment]
Je viens d'essayer aussi la canne macabre elle semble ok également. 
![Bâton](https://user-images.githubusercontent.com/67340950/89803091-afa69880-db32-11ea-8065-c34f8eecfffe.jpg)

**Comment by Eowymos** [comment]
Ça a déjà été analysé, et nous le laisserons ainsi. Merci de votre compréhension.
