### ISSUE TITLE
Probleme de craft ossements / cuir

### ISSUE THREAD

**Issue by GarukWyrmog** [Eowymos/TerraUo#216]
Mon précédent message n’était peut être pas suffisamment prit au sérieux car j'avais fait quelques erreurs dans mon tableau.

Il y a un enorme problème de craft avec les ossements et les cuir bien que certains niveaux de skill ai été ajusté pour correspondre: niveau d'armure équivalent =  niveau de craft équivalent.

Nous avons un problème sur le fait que les os de géant sont disponible depuis le niveau de craft 45 donc en vérité absolument TOUT les guerrier qui portent de l'os ont la meilleur armure (en os de géant pour la plupart) depuis leur classe 2.
Dans quelques jours certains vont passer classe 4 et donc seront en armure level 5 ou 6.
Étant donné que des os intermédiaires que pourraient être l'os de centirius ou l'os de dragon (65 de skill de craft) ne sont pas disponible IG, il faut absolument attendre l'os de démon (75 de skill de craft?) alors que les races autorisant les armures de métal sont déjà sur de la plaques en alliage.
Donc les Gorlak ont actuellement un désavantage sur les autres races en terme d'AR.

Le plus gros problème ce n'est pas qu'il faille attendre 75 pour craft du démon c'est surtout qu'une bonne partie des os sont passé totalement inutile étant donné que le géant à été dispo très rapidement et donc d'un point de vue d'optimisation de son AR, les os Reptilien / Nordique / Morcith / Désertique n'ont fait que de la figuration. 
Il aurait été plus judicieux d'étaler les niveau de skill de craft de façon plus régulière. 
Le centirius ainsi que le dragon ne sont même pas encore dispo qu'ils vont être "has been".

L'os de géant aura été au top pendant 47 niveaux, du niveau 18 (45 skill) au 65 (75 skill) et on passera au démon qui sera top que pendant 14 niveaux, du niveau 65 (75 skill) au 79 (85 skill) et on finira par l'ancien.

Il en est de même pour les cuirs, le démoniaque sera dispo qu'on aura loupé le Rautour / Térathan / Pierre. 
Et pour le cas des cuir tout le monde ne jure que par l'ophidien, reléguant le Nordique / Lupus / Reptilien / Géant / Gargouillien / Maritime à une utilité purement esthétique. 

En tant que Bricoleur je trouve ces aberrations frustrantes pour vraiment pourvoir explorer toutes les facettes de cette classe. Et en gros le seul intérêt de cette classe se relègue alors à la couture. 
Je suis vraiment frustré de jouer cette classe que j'avais exploré de long en large sur ZYX et Teilia, quand je vois qu'en jouant Forgeron nous avons accès a tout un panel de métaux raciaux, aux alliages et qu'il y a le coté exploration, Minage que l'on peut faire seul. 
Nous les bricoleurs on attend que les classe de combat nous apportent les matières premières qui sont pour le moment très limité en terme de diversités

En espérant sincèrement que ce message aboutisse à des résultats concrets je suis à votre disposition pour toutes questions / discussion / besoin de test.

**Comment by ElusivePanda** [comment]
Nous sommes au courant des lacunes des armures dans le système de craft des Os/Cuir vs Métaux et des changements sont déjà planifiés. 
Par contre, pour l'instant, nous n'avons pas de plan de rendre les ossements/cuir récoltable par l'artisan directement sans tuer les créatures associés.

**Comment by GarukWyrmog** [comment]
Merci pour cette réponse, mais 
"rendre les ossements/cuir récoltable par l'artisan directement sans tuer les créatures associés." 
n’était aucunement dans une de mes recommandations je voulais juste mettre en avant que les bricoleur n'avaient pas la possibilité de trouver un plaisir ailleurs quand dans le craft (RP mis a part mais le RP est a la disposition de tout le monde)

Par contre je voulais vous dire que c'est bien de savoir qu'il y a des lacunes mais d'ici environ 3 semaines, cela ne servira plus à rien car beaucoup de bricoleur auront au moins atteint le skill 80.

**Comment by HoboKingCarpenter** [comment]
Point de vue d'un forgeron a propos de ca : 

"quand je vois qu'en jouant Forgeron nous avons accès a tout un panel de métaux raciaux, aux alliages et qu'il y a le coté exploration, Minage que l'on peut faire seul."

Je te dirais que ca dépends de la race pour aller miner seul. 
A titre de Mortanyss, a pars les Mines au Nord je me risque pas a sortir sans escorte donc je suis amplement dépendant des guerriers, surtout considérant que plusieurs mines nécessaires pour les alliages sont a proximitée / en pleine terres ennemies. 

Pour les alliages, oui techniquement un forgeron peut se fournir seul, mais Le Metal tier 4 se craft de base avec un ration 10 - 12 lingots Pour 1 Lingot d'alliage et vont demander autour de 80 % pour crafter le lingot sans perte. 
Alors que les Ossements Niveau 4 tes warriors vont probablement finir par les farmer sans probleme (Y'a deja des groupes de chasses qui petent des demons sans trop de trouble IG apres tout )  

je te dirais que certains forgerons ont des problemes similaires a ce que tu decrit chez le bricoleur. C,est différent, mais pas necessairement plus rose :)

**Comment by Wruntak** [comment]
Je vais donner mon point de vue à la question, me semble que vous ne cernez par ce que veux dire Garuk. 
Il ne remet pas en question le fait qu'aller miner dans des mines soient compliqués dangereux, il dit juste que la classe "Forgeron" permet d'avoir du jeu via la technique et les nombreuses ressources (minerais) disponibles et donc par définition vous pouvez explorer votre classe, prendre du plaisir. Cela à juste titre. 

Il fait que dire:  la classe bricoleur actuellement est "broken" Car oui un bon % des ressources pour faire des armures de cuir ou d'ossement ne sont pas encore dispo, ou pas atteignable certainement lié en l’absence des moyens nous permettant d'aller explorer les différentes îles sur la map. 
Il explique également que d'ici la les joueurs étant "Obligés de porter de l'ossement en jeu" cause RP, se verront directement attribués des crafts d'ossement en Démon ou ossement anciens, car les artisans HL seront capables de les travailler mais également que les ressources ont été ou sont encore actuellement disponibles (Os Démon, Os ancien) ce qui va bypass beaucoup de ressources intermédiaires. 

Exemple concret depuis le début du serveur ( Nous avons vu les ossements de bas niveau, reptilien, nordique. L'ossement de géant est rapidement arrivé et depuis plusieurs semaines sa stagne et dans 2 semaines maximum nous allons voir le Démon, mais les ressources entre le géant et le Démon ? Non car elles seront inférieures)

Car oui les autres ressources intermédiaires sont existantes les bricoleurs peuvent les travailler, mais les ressources ne sont pas atteignables en jeu. 

Le comble de la situation: grands nombre des joueurs ont déjà récoltés les deux dernières ressources d'ossement, l'os de Démon et l'os ancien donc utiliseront jamais ou très rarement (Peut-être pour le cosmétique) les ossements intermédiaire actuellement existant, mais encore une fois pas atteignable pour le moment. 

Pour conclure et cela n'engage que ma personne. Oui je peux comprendre la frustration des bricoleurs pour le dit sujet  ou encore l'attachement d'un joueur envers la classe qu'il joue et  également le temps qu'il met dans Terra, car oui nous avons un staff qui œuvrent bénévolement que tout n'est pas parfait, mais il faut retenir que le sujet fût amené déjà une fois, espérant pour les bricoleurs que cela s'arrange.

**Comment by ElusivePanda** [comment]
Nous savons tout ça et le système pour les bricoleurs qui va venir devrait réglé le problème des ossements de haut niveau. Les ressources de bas niveau seront mises à profit et ceux qui ont déjà 3000 Os de démon/ancient dans leur banque, n'auront pas tout cuit dans le bec.

**Comment by animatrice-hanson** [comment]
Les alliages de cuirs et d'ossements sont intégrés.
