### ISSUE TITLE
Mode du Critique original du fencing disparu.

### ISSUE THREAD

**Issue by ETGLap** [Eowymos/TerraUo#217]
Avec le changement du mode de critique, j'ai remarqué que l'arme Lysardese (Rapière/Fencing) ne fait plus son critique originale (Block)

De plus, son menu affiche maintenant Double Frappe comme par exemple la Prisienne (Lame/Swordmanship)

Je n'ai pas vérifier les masse tel le gourais.

**Comment by pmduguay** [comment]
Le Gourpic donne l'option de Coup écrasant, mais n'ayant pas de PA en Coup Critique et seulement 20 en Vivacité, je ne pourrais pas en dire plus.

**Comment by ETGLap** [comment]
J'ai entendu dire que s'est normal. Que maintenant les armes fencing feront également du double frappe et que seul les bâtons font le block.

**Comment by Eowymos** [comment]
La rapière de Fencing a Block.
