### ISSUE TITLE
Bug dans les tranferts

### ISSUE THREAD

**Issue by ConteurShadow** [Eowymos/TerraUo#219]
Il semblerait que lorque certains joueurs transfère il y a un bug avec le changement de sexe : Si je ne m'abuse c'est de male vers femelle et les cheveux ne se sauvegardent pas également une fois en jeu. Merci ^^

**Comment by JasmineRoy** [comment]
J'ai eu ce problème lors de mon reroll, mon sexe et mes cheveux ont été changé dans la salle de création mais semblaient pas vouloir rester et se resettaient quand je touchait la pierre. Une fois arrivé dans la ville ça s'était replacé (pas eu besoin de rechanger le sexe ni les cheveux malgré qu'ils étaient plus bon en touchant la pierre). Après j'ai pas eu de problème de ce côté là

**Comment by animatrice-hanson** [comment]
Corrigé !
