### ISSUE TITLE
Armes de jet, crit

### ISSUE THREAD

**Issue by Necromig** [Eowymos/TerraUo#220]
Allô!

Je ne sais pas si c'est un bug, mais je n'ai plus Double lancer dans mes crit d'Armes de jet..
J'ai maintenant :

- Faire tomber ce cheval
- Fleche forcée
- Fleche enflammée (dit que ca fait une fleche forcée quand ça touche)
- Coup sauté (?) (dit que c'est une fleche forcée aussi quand ça touche)

Pour info les 3 crits du bas semblent faire la même chose.

Voila! Cheers and love

**Comment by Necromig** [comment]
Plus d'info : c'est les memes crits que bow finalement

**Comment by Eowymos** [comment]
Ce devrait être réglé en temps normal
