### ISSUE TITLE
Ajustement Vigie Sud Luk'Maar

### ISSUE THREAD

**Issue by UnKreated** [Eowymos/TerraUo#223]
Avec la palissade au sud qui es construite a une certaine distance de la ville, la vigie se retrouve a etre déclancher une fois le visage directement dans le mur. La palissade semblant etre un endroit bien garder et controler par les Gorlaks, je crois qu'il devrais etre capable de repérer les ennemis aussitot qu'on sort du chemin au niveau de la riviere.
![20200803_085316](https://user-images.githubusercontent.com/68382699/89184447-cd8a6100-d566-11ea-9d22-e6e28e2191ca.png)

**Comment by Eowymos** [comment]
Toutes les vigies seront revues éventuellement. Merci.
