### ISSUE TITLE
Débalancement classe 4 Barbare

### ISSUE THREAD

**Issue by Mytrix87** [Eowymos/TerraUo#224]
Donc voilà, je crois qu'il y a actuellement un dé-balancement pour la classe 4 du Barbare (Tueur de monstres). J'attendais de voir si le nouveau système allait être accepté puisque cela aurait réglé le problème automatiquement.

Les classes chevaucheur et fine lame n'atteindront que la capacité 5 en armure à leur classe 5, alors que le barbare lui atteindra cette capacité à la classe 4. Cela les rendra alors toujours très efficace en PVM, mais en plus, cela va également les rend efficace en PVP. Actuellement, un fine lame qui combat un barbare en classe 3, il aura généralement toujours l'avantage grâce à duelliste, s'ils sont les deux dans une armure semblable. Mais cette avantage disparaît pratiquement complètement lorsque le barbare à une armure d'un matériau d'un tier plus haut.

Donc si on prend un barbare en chain mail d'Abyssium versus un fine lame en chain mail d'Acier, l'avantage de dégât de Duelliste disparaît pratiquement complètement avec le bonus de AR que donne l'Abyssium. C'est correct, c'est normal. Par contre, le problème va être encore plus grand lorsqu'on atteindra les classes 4 maintenant... Le barbare sera en plaque alors que le fine lame (Et le chevaucheur) resteront dans les chain mails... Ce qui fera qu'à ce moment, et ce jusqu'à la classe 5, le barbare deviendra autant efficace en PVP sinon plus efficace que le chevaucheur et le fine lame, le tout en gardant son ÉNORME avantage en PVM en plus.

Personnellement, Barbare, Fine Lame et Chevaucheur devrait donner les même capacités au même niveau de classe, la seule chose qui devrait les différencier, ce sont les skills requis et les aptitudes que donnent chacune d'elle, le reste devrait être identique pour ne pas donner d'avantage à l'un ou à l'autre. Le Protecteur est dans une classe à part puisque lui n'atteindra jamais le capacité 5 en arme, ce qui fait qu'il reste toujours équilibré. En gros, ce serait donc 3 classes guerriers pas mal pareil mais qui sont spécialisé différemment. En tout temps, le fine lame devrait avoir le dessus en PVP sur le Barbare s'ils ont des armes et armures semblable et du même niveau, puisque le Barbare lui a l'avantage en PVM. Même chose pour le Fine Lame face au Chevaucheur s'ils se font face à face sans bouger (Et encore plus si le Chevaucheur est à pied!)

Je crois que le Barbare, Fine Lame et Chevaucheur devrait atteindre le capacité 5 en protection tous ensemble à la classe 4, comme le Protecteur atteint la capacité 6 à la classe 4 également, ainsi, tous les guerriers atteindrait leur "dernière" armure en même temps et personne ne serait laisser derrière! Mais sinon, Barbare, Fine Lame et Chevaucheur devrait alors rester tous ensemble à la capacité 4 en classe 4 et tous atteindre la capacité 5 en classe 5 ensemble. Sinon, à la classe 4, il va y avoir un dé-balancement et le barbare deviendra LA classe guerrière à avoir jusqu'à la classe 5, Chevaucheur et Fine Lame seront alors désavantagé pour un assez long moment puisque la classe 5 est quand même assez long à avoir!

En gros, si le nouveau système aurait été accepté, en ce moment, c'est comme si le Barbare avait un point de bonus dans ces capacités (Il a 5 en arme, 5 en protection, donc il aurait investi 8 points dans ses capacités), même chose pour le protecteur (4 en arme et 6 en protection, donc encore une fois 8 points dans ses capacités) mais le Fine Lame et le Chevaucheur eux, en classe 4 ils ont seulement 5 en arme et 4 en protection, donc 7 points.

**Comment by ElusivePanda** [comment]
Que le finelame reste en chain est voulu, ça fait parti de la balance de classe considérant que son aptitude Duelliste fait très, très mal.

Le chevalier doit avoir sa capacité 5 à la classe 4 par contre. Ce sera fix.

**Comment by Mytrix87** [comment]
J'ai en ce moment 8 en duelliste, face à quelqu'un sans duelliste avec la même arme et la même armure, je fais entre 8-10 de dégats de plus. Face à quelqu'un avec une armure d'un materiau d'un tier plus solide (Donc acier tier 2 contre abyssium tier 3), la différence est presque entièrement absorbé... Et le combat est pratiquemment égale... Donc j'imagine même pas quand les chevaucheurs et les barbares vont avoir leur plaque et que les fine lames vont être encore en chaine, je suis pas mal sur que notre bonus de duelliste sera alors contrer par la différence de AR des armures... Et donc notre avantage PVP sera pratiquemment inexistant et l'écart en PVM sera encore plus ridicule!

Je trouve juste pas normal qu'un fine lame qui est une classe axé PVP va se retrouver à surment perdre des duels face à des barbares qui sont complèment axé sur le PVM.. ou du moins, le barbare aura ses chances.

Également, toutes les classes guerrière va avoir un gros boost de performance à la classe 4 puisque tout le monde va atteindre une nouvelle armure. Mais les fine lames? Un gros 2 en combat au sol et 2 de duelliste, that's it.

**Comment by ElusivePanda** [comment]
Les classes ont été revus
