### ISSUE TITLE
Savant classe 4 et sacrifice de PAs?

### ISSUE THREAD

**Issue by NChab** [Eowymos/TerraUo#230]
Allo,

Je viens soulever un problème de game design que je constate avec la classe Savant après la classe 3. 

Bon déjà, en tant que telle la classe Savant est assez restrictive. L'alchimie est basique et offre que très peu de couleurs techniques, alors ça va de soi que la classe s'appui aussi sur le scribe et l'écriture de livres de skills pour «survivre». C'est un bon mélange homogène qui se complète bien.

Jusqu'à la classe 3 (Savant), il était possible pour moi d'être auto-suffisant en terme de PA, c'est-à-dire d'avoir autant de points en études qu'en chimie pour pouvoir progresser naturellement jusqu'à 65% dans mes skills. Autrement dit, **j'étais autant efficace en scribe qu'en alchimiste.**

Or, passé le cap de classe 3 et pour atteindre la classe 4, je me retrouve à devoir **sacrifier** des PAs déjà investi en étude et de devoir prioriser chimie. Ça n'a pas de sens, aucun jeu ne demanderait de régresser pour avancer, de devoir sacrifier quelque chose de déjà investi pour aller plus loin.

Je suis niveau 60 et parmi les PAs modulaires j'ai:

Chimie 8
Étude 6
Écriture 3

Si je veux un jour atteindre Érudit, je vais devoir enlever 3 points en étude pour pouvoir avoir 11 en chimie (80% de skill)... 

Sauf que ça implique que mon étude va tomber **plus bas qu'elle l'ait jamais été pendant toute ma progression jusqu'ici**, donc un downgrade de mes compétences. Je ne serai plus en mesure d'écrire des livres de 65% de skill, sauf si je me mets à baisser mes PAs en chimie ensuite pour remonter Étude à 7 une fois que chimie va être maxée... Et rendu là ça devient super maladroit.

Et d'ailleurs, être Classe 4 érudit et Classe 5 sage demande 80-100% d'alchimie, mais y'a aucune potion qui demande autant (le plus haut étant 75%), ce qui donne l'impression de gaspiller des PAs pour un système qui stagne à classe 4.

Je sais que l'idée derrière c'est d'offrir un choix pour éviter d'avoir un savant bon dans «toutes les sphères», mais d'imposer un choix si tardivement dans l'évolution du personnage et que ce choix amène une régression, c'est moyen... Et deuxio, les savants ne sont pas aussi flexibles et versatiles que le reste des classes en terme de revenu donc c'est un peu dommage de devoir choisir en fait, je n'ai pas l'impression que ça amène quelque chose autre que limiter pour limiter. Je ne pense pas qu'un savant serait OP de faire des potions ET des livres de skills équitablement. 

Advenant que ce soit vraiment indésirable de maxer les deux, alors j'imposerais un choix plus tôt dans l'évolution. C'est un peu cruel de nous faire avancer équitablement dans les deux pendant des semaines pour finalement à la dernière minute nous demander de détruire les compétences de notre personnage lol.

Merci de m'avoir lu. :-)

**Comment by Zxithedead** [comment]
J'ai l'impression que le % requis pour les potions ne fait pas vraiment de sens. Entre 0 et 5 PA, chimie ne fait rien de différent. Même chose pour entre 5 et 10. Le fait qu'il y a 3 aptitudes différentes pour l'écriture de livres, ta fonction primaire, fait en sorte que même si c'est chimie demande juste un investissement de 2-3 points, c'est assez énorme.

C'est sans parler des potions qui demande 10 PA (75% skill), vraiment innaccessible avant la classe 4 malgré que tu as le % requis 6-7 niveaux avant ça. Encore là tu dois sacrifier ailleurs pour les atteindres.

Je verais classe 4 donner 1 PA de plus en étude, et 1 PA de plus en chimie. Cela permetterait d'avoir le choix Alchimie ou Sort à la classe 4 sans pénaliser les livres d'études, plutôt qu'avoir le choix niv 80 quand tu gagnes 1 PA de plus et entre temps être "nul" dans l'un ou l'autre.
Pour classe 3, je sais pas si la question d'alchimie peut vraiment être fixer, de toute les manières que je le regarde monter alchimie jusqu'a 10 pour obtenir les explosifs supérieur et pouvoir avoir assez de PA pour les livres demanderaient trop de PA sur la classe. Ça demanderait au moins chimie a 4 ce qui voudrait dire un avantage sur le chemin des Parchemins, et qu'en allant jusqu'à classe 5 tu as un boost de 1PA donc aucun vrai gain de pouvoir sur 2 classe va pas sentir bien non plus. Et si classe 5 offre plus de PA, tu te retrouves avec des scribes qui peuvent tout faire.

Je pourrais aussi voir un plus grand dégradé dans les potions, que ce ne soit pas juste 0%, 25%, 50%, 75%. Peut-être rajouter un pallier entre moyen et forte, ou des nouvelles sortes de potions, comme plusieurs qui ont été suggéré sur le github.

**Comment by ElusivePanda** [comment]
Nous sommes présentement à rebalancer le système de classe, vous avez peut-être vue le premier jet qui se voulait une refonte du système, mais trop de joueur étaient inquiet d'un si gros changement. 
La deuxième itération utilise le système actuel, mais réduit les restrictions imposés aux classes. Nonobstant le système d'alchimie lui même qui manque de profondeur, les problèmes décrits ici devraient normalement être réglé lorsque nous relâcherons cette patch.

ps: Le tag wontfix veut seulement dire qu'il n'y aura pas de travail supplémentaire accordé ici, comme les changements sont déjà effectué sur le build interne.

**Comment by ElusivePanda** [comment]
Si vous avez des suggestions suite à la patch, ouvrir une autre issue, merci.
