### ISSUE TITLE
Mineraux a flanc de montagne

### ISSUE THREAD

**Issue by hysil** [Eowymos/TerraUo#231]
depuis quelques jours lorsqu'on mine sur des flanc de montagnes la récolte est très minime parfois même nul...

**Comment by Ing240** [comment]
Je ne sais pas comment c'était avant mais maintenant le muscovite j'en récupère 3 fois pour toute la montagne. 

Peut-etre rajouter un % de chance d'en avoir après avoir franchit la valeur min. Cela augmenterais sur 50 skill

**Comment by Eowymos** [comment]
Les chiffres sont ce qui est désiré. Votre seule avantage que vous pouvez faire est de maxer la stat Force.
