### ISSUE TITLE
Titres de la classe Savant

### ISSUE THREAD

**Issue by Adalrick** [Eowymos/TerraUo#233]
Les deux premiers échelons sont "Élève" et "Apprenti", qui sont deux termes assez synonymes, aussi on ne peut pas vraiment savoir à l'aveugle, lequel est supérieur à l'autre.
Peut-être qu'un titre comme "Lettré" en second échelon serait plus approprié

**Comment by ElusivePanda** [comment]
Il s'agit d'un bug car le nom de la 2e classe de savant est déjà "Lettré", apprenti est la premier classe de mage.
