### ISSUE TITLE
Ébénisterie - Craft des coffres

### ISSUE THREAD

**Issue by lefranco86** [Eowymos/TerraUo#237]
Tous les coffres, peut importe le skill ou le nombre de ressources requis ont la même "profondeur", soit 125 items maximum et un poids maximum de 400 stones. Donc, une small, medium ou large crate donne le même résultat outre le gump. Un personnage qui a un peu de Constitution peut porter plus de chose dans son sac qu'une caisse de bois...
Est-ce que c'est un bug ou est-ce que c'est voulu?

**Comment by GalvarCorbac** [comment]
Faudrais revoir tout le système de container en fait je crois. la cale des bateaux possède les même paramètres que un sac de cuire en ce moment et c'est vrai pour tout les types de container?
