### ISSUE TITLE
.renommer, brisé

### ISSUE THREAD

**Issue by NChab** [Eowymos/TerraUo#238]
Allo,

Juste mentionner que ma commande préférée du jeu ne fonctionne plus sur les trucs que je «craft» (potions, livres). Ça dit qu'il faut que je sois le propriétaire de l'objet pour le renommer.

De ce que j'ai cru comprendre, l'équipe était inconfortable face à la liberté de pouvoir autant .renommer les choses et par le fait même, les choses qui se «stackent» aussi (e.g. potions) car si un objet a un nom différent de son «stack», il ne se stacke plus...

Bref, un simple rappel pour dire que cette commande amenait beaucoup de jeu, de bonheur, et que ça ajoute beaucoup de couleur dans le jeu.

Merci! <3

**Comment by Selenedortan** [comment]
Ça semble banal mais effectivement ce genre de petite fonction apporte beaucoup de profondeur. J'approuve ce qui est dit plus haut et j'ai hâte que cela soit à nouveau actif ^^.

**Comment by Eowymos** [comment]
Pour les livres, ce sera fait.

**Comment by animatrice-hanson** [comment]
Description ajouté sur tous les objets pour la prochaine patch!
