### ISSUE TITLE
Les armure et les capacités (suggestion)

### ISSUE THREAD

**Issue by DorianDeBeauffort** [Eowymos/TerraUo#242]
Ce serait intéressant que l'artisan puisse craft une armure de n'importe quel capacité? Il devrait choisir a la création de la piece, celle donnerait de la diversité et meme du travail de plus pour les couturier, une cuir capacité 5 ca pourrait surprendre un ennemi qui voit un dael juste en cuir exemple :P

Ca permetterait plus de diversité rp genre mage de bataille sans etre plus fort, juste l'apparance

Dans le fond, énormément de diversité dans les looks possibles et aucun véritable changement technique. Bref, comme c'était sur Teilia.

**Comment by hysil** [comment]
bha je suis contre, juste parce que une armure de cuir pourrais pas etre aussi forte qu'une armure en métaux... selon moi c'est pas rp

**Comment by DorianDeBeauffort** [comment]
Dans un monde ou la magie existe ya pas grand chose de pas possible hahaha. Mais je respect les avis contraire !

**Comment by MBRND** [comment]
J'aime l'idée. Ca éviterai aussi l'espèce d'exception au espion qui peuvent porter du niveau 6 mais en fait cap l'ar a l'équivalent d'un niveau 4. Ca permetterai a tout le monde de jouer avec les designs d'armures.

Pour le réalisme, honnêtement selon la qualité et la quantité de matériel, une "plate" fait en cannes de pepsi versus un cuir épais...

De plus, entre vous et moi, RP+RuleOfCool > réalisme. Particulièrement dans un fantasy.

**Comment by HoboKingCarpenter** [comment]
Si je ne m'abuses teilia avait ce systeme et ca prenait un second sous systeme de crafting via les connaissances Affutage pour les armes et Solidité (ou un truc du genre) pour les armures. 

C'était plutot lourd honnêtement. 

Surtout que niveau technique, comment tu proposes de gérer les limitations de skills autant pour craft que pour certains "malus" inherent de UO (exemple Meditation / Hiding ) 

genre, e craft de toute les armes / armures devraient donc devenir au meme niveau . Parce que théoriquement, ce serait du stuff "niveau 1" de base, mais en faisant ca, cest pas trop "simple" de sortir automatiquement de l'except ?

exemple je craft mon armure de cuir de demon niveau 1, elle pope except parce que j'ai 100 en couture, puis bang, je la claque niveau 6 pour un protecteur ? est ce qu'il y a une possibilité d'échouer après le craft initial ?

je serais curieux de voir le systeme qui va etre proposé derriere ca , honestly. 

Sinon sidenote comme, ca je srais plus poussé a croire qu'un bon Gambison va mieux proteger qu'une actuelle armure de cuir en general (genre tout ce qui est pas Cuir bouilli at least cest pas si efficace mettons :P )

**Comment by Eowymos** [comment]
Le système restera comme il est présentement. Merci de votre compréhension.
