### ISSUE TITLE
Création de Bottle[Tout] ne marche plus

### ISSUE THREAD

**Issue by BigOrteil** [Eowymos/TerraUo#243]
La création de ''Bottle [Tout]'' dans l'outil de Tinkering ne fonctionne plus après la mise à jour. De plus, créé une bouteille utilise seulement 1 lingot de fer plutôt que 2 comme indiqué.
![image](https://user-images.githubusercontent.com/69661428/90209789-4769e800-ddba-11ea-8688-934cfab5daf6.png)

**Comment by ElusivePanda** [comment]
As tu sélectionné "Iron Ingot" dans la sélection du bas?
Deplus, la sagesse réduit le nombre de ressource consumé
