### ISSUE TITLE
.tip, le nom en haut du parchemin change suivant le déguisement, même une fois ouvert

### ISSUE THREAD

**Issue by MirageNebulix** [Eowymos/TerraUo#249]
J'ai reçu un .tip d'un personnage 'inconnu' il y a peu et plus tard j'avais oublié de faire disparaître le .tip alors je l'ai ouvert à nouveau en cherchant comment faire et en haut au lieu d'être 'Inconnu' j'avais maintenant le nom du personnage.

**Comment by MirageNebulix** [comment]
Je viens de refaire l'essai et c'est toujours le cas. Si je .tip sous un nom déguisé, si on garde le .tip ouvert, le nom changera quand j'enleverai le déguisement.

**Comment by animatrice-hanson** [comment]
Corrigé prochaine mise à jour !
