### ISSUE TITLE
Chances d'armes exceptionelles. 

### ISSUE THREAD

**Issue by Jobarco** [Eowymos/TerraUo#250]
Mes skills sont cappés à 75.5 ( Carpentry et Blacksmith ) 

Mes chances de faire une arme lvl 5 à 74.5 de blacksmith sont de 14.3 % et 0 % except.

Mes chances de faire un arc lvl 5 à 74.5 de carpententry sont de 14.3 et 10.5 % except. 

Pourquoi ? X)

**Comment by lefranco86** [comment]
Je commente afin de remonter ce bug puisque les guerriers atteignent de plus en plus leur classe 4 et que les artisans ne peuvent pas fournir la demande. Il est possible de faire les armures capacités 5 exceptionnelles mais pas les armes.
J'ai 79,5% en BlackSmith et voici mes chances pour une Claymore (capacité 5 à 74,5%)
![image](https://user-images.githubusercontent.com/15695199/90817032-39a4ed00-e2fb-11ea-945e-315da1c19b25.png)

**Comment by Nebelpfade666** [comment]
Sagesse peut-être ?

**Comment by lefranco86** [comment]
> Sagesse peut-être ?

Intelligence et Sagesse max.

**Comment by Jobarco** [comment]
C'est clairement bug, pcq les armes a distance ont des chances d'être except.

________________________________
De : lefranco86 <notifications@github.com>
Envoyé : 20 août 2020 18:15
À : Eowymos/TerraUo <TerraUo@noreply.github.com>
Cc : Jobarco <micheljr.lachapelle@hotmail.com>; Author <author@noreply.github.com>
Objet : Re: [Eowymos/TerraUo] Chances d'armes exceptionelles. (#250)


Sagesse peut-être ?

Intelligence et Sagesse max.

**Comment by GalvarCorbac** [comment]
![screenshot_2020-09-02_04-00-06](https://user-images.githubusercontent.com/67514003/92035263-6d8d0300-ed3c-11ea-8ecb-07eba15b8a71.png)
![screenshot_2020-09-02_04-00-19](https://user-images.githubusercontent.com/67514003/92035274-7251b700-ed3c-11ea-8fde-53db364bfd09.png)

voilà ce que ca donne

**Comment by animatrice-hanson** [comment]
Corrigé pour la prochaine mise à jour !
