### ISSUE TITLE
.renommer les aliments que l'on crée

### ISSUE THREAD

**Issue by Richcoeur** [Eowymos/TerraUo#255]
Salut,

Les aliments créés via le cooking ne peuvent pas être renommés. 

C'est utile pour décrire une recette. Exemple pour décrire la pizza à la Richcoeur :)

Merci

**Comment by MirageNebulix** [comment]
Il FAUT qu'on puisse! Parole de Gorlak XD

**Comment by animatrice-hanson** [comment]
Corrigé prochain maj !
