### ISSUE TITLE
Dueliste VS Tueur de monstre

### ISSUE THREAD

**Issue by Ripdream** [Eowymos/TerraUo#257]
Classe 4- Le dueliste obtient les capacités d'armes 5 et demeure a capacité armure 4.
               Le Tueur de monstre obtiens 5 en armements et 5 en armures.

Suite à la dernière patch, cette ligne en particulier : - Retrait des bonus que les classes donnaient aux aptitudes

Un tueur de monstre qui se build en duelisme et coup critique devient plus éfficaces en PVP qu'un dueliste avec le même build. 

Tout ca simplement a cause de capactié 5 en armure. 

J'ai donc quelques suggestions a faire si sa peux peut-être vous lancer sur une piste ! 

A: remettre le bonus que duelisme procure au dueliste (soit en dmg soit en chance d'esquive )
B: donne capacité 5 d'armure au Dueliste
C: donne du coups critique ou d'avantage de duelisme au dueliste

**Comment by ElusivePanda** [comment]
Une passe de balance est déjà en cours, ce point à été revu.
