### ISSUE TITLE
.Renommer peintures et sculptures

### ISSUE THREAD

**Issue by Richcoeur** [Eowymos/TerraUo#258]
On ne peut plus renommer les toiles et les sculptures que l'on crée en jeu. C'est écrit qu'on doit avoir créé l'objet pour le renommer alors que c'est le cas.

**Comment by lefranco86** [comment]
Même chose pour les bijoux !!

**Comment by animatrice-hanson** [comment]
Description disponible pour les peintures, sculptures et bijoux pour la prochaine patch !
