### ISSUE TITLE
Runebook pas trop fonctionnel

### ISSUE THREAD

**Issue by SteinVeldeson** [Eowymos/TerraUo#259]
On peut y rangé ses runes mais ca semble a peu près tout ce qui est fonctionnel. On ne peut pas utilisé les runes qui y sont par contre, puisque ca prendrait "recall" ou "gate travel" a caster pour que ca fonctionne :P

**Comment by Legareto** [comment]
Je ne suis pas sûr de comprendre... il ne faut pas justement marquer une rune puis la placer dans runebook seulement une fois que c'est fait pour que ça devienne fonctionnel? (j'essai de comprendre)

**Comment by SteinVeldeson** [comment]
Il faut marqué sa rune oui, mais ca ne s'arrete pas la après ca.

![image](https://user-images.githubusercontent.com/67364453/90719985-aed4db80-e283-11ea-8ca2-8212d32f78f1.png)

Pour s'en servir, il faut tourné les pages pour aller voir a la bonne rune et choisir une des deux options en dessous, a gauche c'est "recall" mais ce qui arrive quand je clique dessus...

![image](https://user-images.githubusercontent.com/67364453/90720039-d2982180-e283-11ea-8572-5437d8137144.png)

**Comment by Legareto** [comment]
Ho! Okay ouais ... semble bien y avoir un problème alors !

**Comment by ElusivePanda** [comment]
Le runebook est déjà réglé dans la prochaine patch
