### ISSUE TITLE
Tonnelet

### ISSUE THREAD

**Issue by Hebius06** [Eowymos/TerraUo#260]
Bonjour,

On peut crafter des kegs, qui servent de container, via le menu carpentry
On peut crafter des robinet, des couvercles, des cerclages de tonneau via tinker

Par contre, il semblerait qu'on ne puisse pas fabriquer de tonnelets, permettant de stocker le contenu des potions.

Est-il prévu que ça arrive en jeu ?

Merci

**Comment by animatrice-hanson** [comment]
Nouvelle fonctionnalité disponible dans la prochaine mise à jour !
