### ISSUE TITLE
Duelisme

### ISSUE THREAD

**Issue by Ripdream** [Eowymos/TerraUo#265]
C'est normal que la différence de dmg entre arme lvl 4 et 5 c'est 10 de dmg ? 

Genre j'ai arme lvl 5 et 119 armure 
mon adversaire a lvl 4 arme et 130 ar. 
 J,ai 10 duelisme et 10 et encoups critique
 mon adversaire a 10 en coups critique 4 en duelisme. 

la différence de dégat entre les deux c'est 10
J,ai 6 pts de plus que mon adversaire en duelisme et une arme lvl 5 et sa me donne seulement 10 de dmg de plus

est-ce un bug ?

**Comment by Eowymos** [comment]
Oui c'est normal avec les chiffres que tu me montres. Duelliste fait plus de dégâts, mais ton adversaire a plus d'AR que toi. Si tu veux être plus constant, je te suggère de mettre 5 en duelliste et 5 en perforation.
