### ISSUE TITLE
Coiffe de loup sur femme

### ISSUE THREAD

**Issue by ErikaArthass** [Eowymos/TerraUo#267]
Bonjour. Je veux rappeler ce bug au staff, car depuis l'ouverture nous avons ce bug visuel. La coiffe de loup donne une barbe sur le jeu. Le reste est nickel. J'aimerais juste le rappeler en espérant que vous regardiez ça bientôt, Merci ! :)

![bug](https://user-images.githubusercontent.com/70193491/91282164-fb725800-e756-11ea-9a9f-6bfaab654aa5.JPG)

**Comment by MissIelenia** [comment]
Fix pour la prochaine MAJ (Désolé pour le temps)
