### ISSUE TITLE
Aptitude tueur de monstre vs mage joueur

### ISSUE THREAD

**Issue by DorianDeBeauffort** [Eowymos/TerraUo#268]
Bonjour,

J'ai cru remarqué que je semblais faire moins de dégat sur quelqu'un avec de l'aptitude Tueur de monstre. Est-ce un bug puisqu'il est marqué dans l'aptitude : Réduction des dégâts magiques en PvM. Donc, cela ne devrait pas s'appliquer vs joueurs?

**Comment by Eowymos** [comment]
Rien ne porte à croire dans le code que ça peut s'appliquer aux joueurs. L'attaquant doit être une BaseCreature (Mob) et le défenseur un Joueur.
