### ISSUE TITLE
Robe de soirée/Robe Pure

### ISSUE THREAD

**Issue by FlaminBear** [Eowymos/TerraUo#269]
Une des deux robes de soirées dans le menu de craft a pas le bon gump. Son gump est un doublon de la Robe des bois et est pas du tout la même chose que le art.

La robe s'appelle aussi Robe Pure au lieu de s'appeller Robe de soirée comme dans le menu de craft. (C'est probablement le nom dans le menu de craft qui est pas bon)

![RobePure](https://user-images.githubusercontent.com/67613351/91379693-42149080-e7f1-11ea-9417-1cedda611c57.png)

**Comment by MissIelenia** [comment]
Corrigé
