### ISSUE TITLE
Revoir les matériels requis pour les armes de jets

### ISSUE THREAD

**Issue by Krashto** [Eowymos/TerraUo#27]
Hache | 1 lingot 1 buche |  
Javelot | 2 lingot 1 buche |  
Etoile | 4 Lingot |  
Shuriken | 5 Lingot |

**Comment by Hermne** [comment]
Autant supprimer les armes de jet. :)
Je pense que cela rendrait encore MOINS viable les armes de jet qu'elles ne le sont déjà.

1 flèche / 1 carreau = 1 buche + 3 plumes
Prérequis d'aptitude: 0
Prérequis de skill: grosso modo 30.
Que ce soit pour une arme 0 ou une arme 5 le coût du consommable est identique.

Là avec le coût en buche actuel d'un shuriken (5) il faudrait **5000** buches pour **1000** shuriken SANS avoir l'option de faire cela en quelques clicks comme les flèches.
Il faudrait faire 1000 clicks.
ET avoir beaucoup dans l'aptitude de fabrication d'arc
ET avoir beaucoup dans bowcraft.

Donc un acrobate qui n'aurait pas investi énormément de PA dans l'aptitude bowcraft ne pourra pas faire ses propres projectiles, et faire ses projectiles même de bas niveau est déjà plus douloureux que pour faire une flèche ou un carreau qui, soit dit en passant, fait plus de dégâts.

**Comment by ElusivePanda** [comment]
Cout rebalancer, option créé tout ajouté.
