### ISSUE TITLE
Summons necromancie 

### ISSUE THREAD

**Issue by pocloutier87** [Eowymos/TerraUo#271]
Je ne peux pas comparer avec les invocations car je ne connais que necromancie, mais voici quelques constats sur les summons des necromanciens. Je parle ici de :

- Familiers
- Strangulaires
- Liches
- Corps réanimés

Mes constats sont faits avec 85 intel, max magery/eval intel. **Je me concentre surtout sur le PVE (oui, je sais), donc peut-être que je n'ai pas tout dans le portrait.**

- Magery ne semble avoir aucune influence sur leurs stats. Intel et eval intel non plus.
- Leurs skills (wrestling, tactics, magic resist) sont statiques, peu importe l'aptitude.
- Le reste semble monter très lentement (Hp, Str, Dex, Intel, dégâts, AR - s'ils en ont)
- Seule la liche fait des spells même si le strangulaire a du magery.
- Familiers demande 2 slots, strangulaire 3, liche 4 et corps réanimés 6 (peu importe la créature pour ce dernier on dirait).
- Seuls des niveaux supplémentaires dans l'aptitude font scaler quoi que ce soit.
- Leur durée est, en générale, très courte.

Familier

Bien correct honnêtement. Les petits effets spéciaux sont cools. Rien à redire, en groupe ils peuvent remplir leur fonction sur les premiers dongeons. Le scaling est correct mais évidemment devient peu utile avec le prochain summon.

Strangulaire

Super quand on l'obtient. Malheureusement, entre 4 et 12 de necromancie, très peu de choses vont changer. Son scaling est faible, mais quand on peut en avoir 2, il devient vraiment un frontline difficile à briser. Comme il n'utilise pas son magery, son damage est cependant assez mediocre même avec 12 en necromancie.

Liche

Apparemment plus pour le pvp en raison du casting. Dégâts par sortilège en pve pas meilleurs que le strangulaire, voire pire selon ce qu'il cast, et en raison de son très faible wrestling n'en vaut pas la peine du tout car tombera bien plus vite malgré de meilleurs Hp et AR. Trop peu de wrestling pour tirer partie de ses dégâts en melee aussi.

Corps réanimé

N'arrive pas à la cheville d'un strangulaire, pour le double des slots et 6 niveaux de plus en aptitude. En ce moment, carrément inutile en dehors de fonctions RP.

**Suggestions**

- Améliorer le scaling du strangulaire légèrement par niveau. J'irais avec quelques points de dégâts OU du HP de plus, mais pas les deux. Entre 10 et 20%, juste pour rendre le scaling un peu plus apparant. Ou bien l'augmenter davantage sur les deux fronts et le monter à 4 slots requises lui aussi, quitte à le remonter dans le niveau d'aptitude ?
- Buffer la liche en PVE seulement. Si pas possible de différencier pvp et pve, lui donner du wrestling pour la peine et donc qu'elle ait vraiment sa place en pve aussi ? En fonction du point précédent j'imagine.
- Réanimation est vraiment trop faible et trop couteux. Ça me dérange pas qu'elle coûte 6 slots mais faudrait au moins que ca en vaille la chandelle. Déjà trouver un corps qui le mérite c'est une chose, mais après ca donne rien car 2 strangulaires vont l'écraser anytime (même slots). Je sais pas trop comment le revoir. Soit un 3e summon gratis mais plus faible, soit un coût a 6 mais fort, soit à 8 mais vraiment plus fort. Je sais pas !

Voilà, Je sais que necro est très tendance mais c'est ma classe depuis le début du serveur, alors je partage que ce que je sais (encore une fois, je suis très PVE et pas PVP).

**Comment by ElusivePanda** [comment]
Les summons du nécro sont déjà très fort et trivialize le contenu PvM du jeu dans l'état qu'ils sont.
Comme tu as bien remarqué, ils ont chacun leur particularité qui donne un choix du summon à utiliser selon la situation.
Le familier est principalement utilitaire.
Le strangulaire est un frontline tank.
La liche est le summon à utiliser en PvP et comme deuxième summon, protégé par un strangulaire, il est efficace.
Reanimation a pour but d'inciter le necromancien à aller trouver la créature la plus forte possible pour la réanimer et avec un puissant compagnon. Si tu reanimes des Morlasks, c'est effectivement inutile, mais réanime un dragon et je te garantie que c'est une autre histoire.
La durée des summons me semble largement suffisante, ils durent en moyenne 5 minutes.

**Comment by pocloutier87** [comment]
Une fois que je l'ai réanimer, je peux le conserver éternellement même avec un delog ? Ou c'est juste pour sécuriser la sortie du dongeon après le boss ?

Faudra vraiment vérifier les stats de réanimation car même sur des boss j'ai rien trouvé de wow qui méritait de pas prendre un seul strangulaire à sa place.

**Comment by ElusivePanda** [comment]
Tu peux le conserver un temps très raisonnable, on parle + d'une heure facilement, mais pas infini non.
Merci de tes impressions!
