### ISSUE TITLE
Talisman vs Amure

### ISSUE THREAD

**Issue by Ing240** [Eowymos/TerraUo#272]
Bonjour je voudrais savoir si cela est normal que le talisman prend plus de lingots qu'une armure de même niveau

ex
Talisman/Armure
Niv6 96/80
Niv5 84/69
Niv4 72/63
Niv3 60/57

Et ce qui est différent est que le bouclier fait toujours la différence en nombre de lingot. 
ex
Delta/Nb lingot requis
Niv6 16/16
Niv5 15/15

du moins pour les 2 plus haut niveau

**Comment by animatrice-hanson** [comment]
Ajusté pour la prochaine mise à jour !
