### ISSUE TITLE
GUMP percecoeur

### ISSUE THREAD

**Issue by tordinforgefeu** [Eowymos/TerraUo#273]
Il me semble que le gump de la Percecoeur était comme l'arme dans le sac. C'est-à-dire une lance blanche. Or, lorsque je prends celle-ci, elle ressemble présentement à une lance de jouteur du médieval. J'ai rien contre mais le gump de la vrai Percecoeur était wayyyy more nice. Je me demandais donc si c'était un erreur.

Merci

**Comment by MissIelenia** [comment]
Fait
