### ISSUE TITLE
GUMP "Robe de soirée"

### ISSUE THREAD

**Issue by Mytrix87** [Eowymos/TerraUo#274]
Bonjour!

Simplement pour dire, quand on teint la "Robe de soirée", elle devient tout plein de pixel.

Voici une image pour voir le résultat quand on la teint en rouge! 

![BugRobe](https://user-images.githubusercontent.com/69155746/91676291-5c11e400-eb0d-11ea-8a78-0381804858ed.PNG)

Merci!

**Comment by MirageNebulix** [comment]
Il y a plusieurs vêtements qui font cet effet, pas que celle là.

**Comment by MissIelenia** [comment]
Fix à la prochaine MAJ
