### ISSUE TITLE
Suggestion - déplacement de ressources

### ISSUE THREAD

**Issue by JasmineRoy** [Eowymos/TerraUo#275]
Avec le nombre de ressources demandées pour faire les différents projet, je trouve qu'on se murent un peut tous au problème qu'un cheval porteur peut porter 1600 stones (ou 1066 de fer/bois). C'est vraiment peu et ça a un effet dissuasif sur le commerce de ressources et les dons aux projets. 

J'ai donc deux suggestions :

- Créer un "familier" qui ressemble à une charrette et qui saurait traîner plus de ressources (peut être pour un peu plus de familiers, 2-4 pour que ce soit quand même envisageable pour ceux qui iraient pas nécessairement chercher plus de familiers). Il pourrait être plus lent qu'un cheval à la limite (vitesse de marche au sol par exemple), mais pourrais traîner pas mal plus de stock (jusqu'à 10k stones par exemple). Il pourrais également être créé par les artisans, le charpentier et/ou le tinkerer (avec des pièces en collaboration des deux par exemple)

- Pour les transactions commerciales majeures entre des villes plus éloignées, peut être un système de transport animé par MJ ou semi-automatisé, qu'il faudrait défendre en chemin et qui serait quand même dispendieux? C'est un peu vague, mais ça pourrait être intéressant et ça pourrait donner des occasions de PVP/brigandisme

**Comment by Eowymos** [comment]
Il y a un système qui s'en vient avec le système de bateau qui permet de vendre ses ressources contre des billets de ressource, un peu comme des chèques. Ce pourra être utilisé pour les projets sans problème.
