### ISSUE TITLE
.Decouvrir

### ISSUE THREAD

**Issue by Krashto** [Eowymos/TerraUo#276]
Ne fonctionne pas.

Testé sur un joueur que j'arrivais a DH, .decouvrir ne le revelait pas.

**Comment by Eowymos** [comment]
Il y a un jet à réussir. As-tu essayé plusieurs fois ?

**Comment by Krashto** [comment]
Je l'ai spammé une bonne dizaine de fois.

**Comment by MirageNebulix** [comment]
Avec 100 DH j'ai fnialement réussi a .decouvrir quelqu'un avec 30 hiding. Mais sinon a 80 hiding VS 100 DH, le .decouvrir ne semble pas fonctionner.

**Comment by animatrice-hanson** [comment]
Après plusieurs tests le .decouvrir fonctionne comme il se doit. On doit être à une case pour utiliser .decouvrir et comme Eow l'a spécifié, il y a un jet à réussir donc parfois il faut le faire plusieurs fois pour le réussir.
