### ISSUE TITLE
Armes de Jet Niveau 3 pour les Artisans

### ISSUE THREAD

**Issue by Mytrix87** [Eowymos/TerraUo#277]
Bonjour!

Simple suggestion comme ça, je crois que les artisans, en plus d'avoir leur protection 3 et arme capacité 3, pourrait également avoir Armes de jet au niveau 3. Cela permettrait à ceux-ci d'être utile en chasse de groupe, sans se mettre trop en danger puisqu'ils ne peuvent pas vraiment encaissé! Voilà!

**Comment by Eowymos** [comment]
Les armes de jet sont réservés pour certaines classes. Les artisans ont suffisamment d'outils pour se débrouiller en pve et pvp.
