### ISSUE TITLE
Incrément d'AR entre les minerais/alliages disproportionnés 

### ISSUE THREAD

**Issue by pmduguay** [Eowymos/TerraUo#278]
Salut!

Les forgerons ont commencé à faire des alliages, et je tiens à préciser pour commencer que c'est vraiment un bel ajout pour donner une seconde vie à toutes les mines. Bravo!

Minerais T3: Bloodirium | Herbrosite | Maritium | Muscovite | Mytheril | Phlogopite | Sombralir | Abyssium

Alliage T1: Biotite | Draconyr | Héliothrope | Heptazion | Océanis | Pyroxène
Alliage T2: Brazium | Lunérium | Marinar
Alliage T3: Teilium

Pour chaque alliage T1, on sait que ça prend déjà beaucoup de minerais T1-2-3, et pour chaque alliage T2, ça prend 2 alliages T1 et un minerais T3. Juste pour mettre en contexte, produire 84 lingots d'alliage T1, ça prend minimum 588 minerais, dont seulement 84 T3, alors que pour l'alliage T2, ça prend minimum 2352 minerais, dont 504 T3.

Donc, pour résumer:

Une plaque de minerais T3 prend 84 lingots = 100%
Une plaque d'alliage T1 prend 588 lingots (dont 84 T3) = 700%
Une plaque d'alliage T2 prend 2352 lingots (dont 504 T3) = 2800%

Maintenant, comparons les incréments en AR de chaque, toujours en prenant pour exemple la plaque:

Un morceau de plaque en minerais T3 exceptionnel donne 20, soit 140 au total = 100%
Un morceau de plaque en alliage T1 exceptionnel donne 22, soit 154 au total = 110%
Un morceau de plaque en alliage T2 exceptionnel donne 23, soit 161 au total = 115%

Je comprends que les AR ne peuvent pas être 700 et 2800% plus élevés que le minerais T3, mais il me semble que l'incrémentation entre les alliages est tout à fait disproportionné par rapport à l'effort immense que ça demande. Imaginez le travail que ça va demander d'avoir du Teillium? (calcul rapide: 26019% plus long que du minerais T3). 

Je termine en rappelant que je trouve ça génial comme idée, mais le _balancing_ me semble _off_. Je m'attendais au minimum à avoir un morceau de plaque en alliage T2 exceptionnel faire au moins 25 AR, soit un incrément de +2 entre le minerais T3 et l'alliage T1 et un incrément de +3 entre l'alliage T1 et T2.

Au plaisir et merci d'avoir battit tout ce beau système!

**Comment by karlsc** [comment]
Effectivement, +7 de AR entre alliage T1 et alliage T2 est vraiment petit, surtout que le AR a été fermement nerfé et que le nombre de minerais nécessaires pour une armure T2 est vraiment énorme.

**Comment by Ing240** [comment]
Je suis d'accord avec le point. Il faut que le résultat soit un peu plus en lien avec la difficulté de la production des pièces. On parle même pas ici le % de faire les lingots comme le teilium.

**Comment by Eowymos** [comment]
C'est un principe qui est appliqué sur plusieurs jeux. Plus tu montes en défense, plus c'est difficile de monter en défense. Chaque point d'AR est important, et je vous recommande d'utiliser les alliages. Je garde pour l'instant la montée linéaire. Merci de votre compréhension

**Comment by pmduguay** [comment]
Avec le Tellium qui vient de faire son apparition, on sait maintenant que ça donne +2 AR.

Donc, si je refais mon calcul:

Un morceau de plaque en minerais T3 exceptionnel donne 20, soit 140 au total = 100%
Un morceau de plaque en alliage T1 exceptionnel donne 22, soit 154 au total = 110%
Un morceau de plaque en alliage T2 exceptionnel donne 23, soit 161 au total = 115%
Un morceau de plaque en alliage T3 exceptionnel donne 25, soit 175 au total = 125%

Donc +10%, +5%, +10%.

Voilà, simplement pour terminer mon calcul pour les curieux! :)
