### ISSUE TITLE
.Sacrifice - Délais même si tu manques le spell (target too far aways)

### ISSUE THREAD

**Issue by ETGLap** [Eowymos/TerraUo#280]
Bonjour,
Je comprends que le skill fut 'nerf' mais je trouve un peu poche que le délais embarque même si tu manque ton coup. Le délais est vraiment long, comme une potion sinon plus. Oui d'ancien protecteur on abuser mais il devrait avoir un entre deux.

Au moins si l'on manque vue la personne est trop loin, laisser nous le réessayer et quand il fonctionne (heal) l'a le délais embarque. Sinon le sort est rendu pas très bon pour 9 AP dedans. 

Merci

**Comment by animatrice-hanson** [comment]
Corrigé pour la prochaine mise à jour !
