### ISSUE TITLE
.backstab

### ISSUE THREAD

**Issue by MBRND** [Eowymos/TerraUo#284]
.backstab semble être un buff que tu garde. Je pouvais enchainer les backstabb tant que je retournais hidé sans avoir a "recasté" la commande. Jusqu'a ce que je recoive le message que j'ai pris trop de temps.

.focusattack semble absolument rien faire sur les monstres. Je vais testé sur un joueur prochainement.

.deathstrike demande 12, jai pas encore la chance de testé a 12.

.kiattack demande 8, j'ai pas encore 8 non plus. J'update dès que j'ai des infos.

Backstab qui demande de la mana je trouve ca spécial. Ca ne devrai pas être de la stam a la place?

Le reste de la patch roublard semble bien fonctionner. Merci pour cette belle patch! J'ai hate a la refonte du déguisement!

**Comment by HoboKingCarpenter** [comment]
La raison pourquoi ca utilise du mana cest probablement parce que ces 4 "attaques" sont en fait des "spells" de Ninjitsu. 

Pour ce qui est de focus attack, Si les variables du spell de base ont pas été changé ca va donner un bonus au Degats et au "hit effects" (truc reliés aux Armes magiques donc Inexistant sur Terra ?) basé sur ton skill Ninjitsu (probablement un autre skill / aptitudes ici ?) 
Donc en gros, ca risque d'etre un genre de Backstab non hidé vu le bonus damage

**Comment by ElusivePanda** [comment]
Focusattack augmente les chances de toucher de ta prochaine attaque, il est très léger en cout de mana et permet d'éviter de rater une attaque importante comme Deathstrike ou Kiattack justement. Bref, c'est une assurance.

**Comment by MBRND** [comment]
Les problèmes mentionné plus haut semble déjà regler. Ceci-dit est-ce voulu qu'on puisse utiliser backstab avec d'autre weapons que la dague?

**Comment by animatrice-hanson** [comment]
C'est voulu !
