### ISSUE TITLE
Esprit de dragon utilise le mauvais AI

### ISSUE THREAD

**Issue by Mektor2** [Eowymos/TerraUo#285]
L'esprit du dragon est étiquetée comme un Guerrier-Mage sur la page des sorts. Il a d'ailleurs environ 100 magery/eval int.

Cependant, il ne lance aucun sort. Il fait juste attaquer physiquement.

Peut-être que son AI est mis à Mêlée au lieu de Guerrier-Mage (comme les monstres démons)?

**Comment by animatrice-hanson** [comment]
Est fixed pour la prochaine patch.
