### ISSUE TITLE
Connaissance : Sculpture

### ISSUE THREAD

**Issue by Nebelpfade666** [Eowymos/TerraUo#288]
Revoir comment on ramasse les roches.

**Comment by JasmineRoy** [comment]
+1
j'avais fait quelques suggestions la dessus sur #129

**Comment by Hebius06** [comment]
Rajout sur le sujet : 

1) les plus grosses statues nécessitent 250 roches (hors réduction de sagesse), pour une réussite de 15%  (hors boost d'intelligence) ce qui fait une moyenne de **1666 roches** pour une réussite. Sachant qu'il faut environ **6 secondes** pour ramasser entre 1 et 4 roches (soit **2,5 roches en moyenne**), cela nécessite **67 minutes** de farm de cailloux

2) les roches sont d'une seule couleur. la possibilité de récupérer diverses roches colorées (ou pouvoir peindre une création) serait un plus.

3) la possibilité de renommer ses créations serait appréciable.

4) un outil plus adapté d'une fronde serait justifié (pelle à argile, pioche a rochers, etc)

**Comment by animatrice-hanson** [comment]
Doublon avec https://github.com/Eowymos/TerraUo/issues/129. Les suggestions ici ont été ramenés sur l'autre suggestion pour regrouper le tout.
