### ISSUE TITLE
Sommelerie

### ISSUE THREAD

**Issue by Hebius06** [Eowymos/TerraUo#295]
Après 2 tests (car mes moyens ne sont pas infinis)

1 hydromel demande **50 houblons** (sucrés, elfique, etc) .
on récupère 2 houblons par graines plantée avec succès. Le taux de réussite d'une graine qui pousse (si non dépendant du skill)  est de 9% .  Cela représente donc **1875 po** d'achats de graine à planter.
on rajoute le malt (**9po**). Je compte le keg **(300 po)** en achat au sommelier
Si l'on rajoute le taux de succès de craft (dans mon cas **15%**), un tonneau d'hydromel revient, en moyenne à 13172 po

Dans le cadre d'une personne ayant **100 en cooking**, le tonneau reviendrait à **1976 po** (si taux de drop = 9%)

Toutefois, si le taux de "pousse des graines" est calculé sur la skill cooking, dans ce cas, on passe à 460 po le tonnelet pour une personne à 100 en skill cooking

Il n'est pas possible de renommer les bouteilles de vin, elles gardent l'appellation de leur raisin

Un tonnelet plein passe en **stone négatif** lorsqu'on remplit des fioles

le **bag of suger** demandé dans la recette des jus se nomme **liqueur de cacao** en réalité

Le **cacao** nécessaire pour faire les tonnelets sans alcool est **inexistant** visiblement

**Comment by animatrice-hanson** [comment]
La prochaine mise à jour contiendra plusieurs changements et corrections proposés pour la sommelerie !
