### ISSUE TITLE
Recycleur versus osselage

### ISSUE THREAD

**Issue by ETGLap** [Eowymos/TerraUo#300]
Le recycler ne semble pas fonctionner sur les armures fait avec les osselages (alliage) d'os. On essaie de récupérer l'armure Cendré et Colossale et n'y l'une n'y l'autre n'est recyclé.

**Comment by FlaminBear** [comment]
Est-ce qu'il y a un update pour ce bug? Je commence a être innondé d'armures a recycler :|

**Comment by animatrice-hanson** [comment]
Corrigé prochain patch !
