### ISSUE TITLE
.Transformation - Choix avec Drakan

### ISSUE THREAD

**Issue by ETGLap** [Eowymos/TerraUo#308]
Les choix de .transformation avec la race Drakan est le serpent, l'homme lézard et la grenouille.

L'homme lézard ne fonctionne pas, le skin est celui du serpent. Est-ce voulu ou possible de faire ne sorte que se soit un homme lézard?

Merci,
SselesS

**Comment by animatrice-hanson** [comment]
Corrigé, à venir pour la prochaine patch.
