### ISSUE TITLE
Lumberjacking influence encore le dégat de Sword

### ISSUE THREAD

**Issue by MBRND** [Eowymos/TerraUo#309]
Le titre dit tout.

Ca veux dire que les autres weapons ne peuvent pas être competitif dans un build optimisé versus l'épée.

Faudrai soit ajouté des "secondary skill" qui sinergise avec les autres armes et pas la sword.

J'ai pas testé Arms Lore, mais dans le temps c'était aussi quelquechose qui aidait le DMG. Je sera curieux de voir si c'est encore le cas sur Terra. Vue que beaucoup d'interactions entre les skills on été annulé.

Ca serai bien d'avoir ces info transparente.

**Comment by animatrice-hanson** [comment]
Après plusieurs tests, le lumberjacking n'influence pas le dégât de Sword mais plutôt Anatomy et Tactics. Si c'est toujours le cas, nous avons besoin de plus de détails pour reproduire le bug.
