### ISSUE TITLE
Fabrication de tonneaux alcoolisés

### ISSUE THREAD

**Issue by Hebius06** [Eowymos/TerraUo#313]
Petit retour sur le "brewing menu"

Pour les graines (achetables 3 po chez le marchand), il y a environ 18% de chances de réussite de sortir 2 houblons

Mead (hydromel) : 50 houblons soit 278 graines à acheter, donc 834 po , + le keg 300 po + le malt à 9 po, total de 1143 po
Ale (bière) : 50 houblons soit 278 graines à acheter, donc 834 po , + le keg 300 po + le barley (orge) pas en jeu visiblement, donc, création impossible
Cider (Cidre): 100 pommes soit 800 po + le keg 300 po + le sucre 3 po, total 1103 po

au lv 84, un joueur à 50% de chances de réussite un tonneau, 100% de chances au lv 94.

Pour simplifier :

1) taux d'apparition des houblons quand on plante des graines trop bas
2) objet manquant dans les menus des vendeurs ou en culture

**Comment by animatrice-hanson** [comment]
De gros changements et correctifs sont à venir pour la sommellerie. Prochaine mise à jour ces deux problèmes seront réglés.
