### ISSUE TITLE
.tauntall demande de la mana et non de la stamina

### ISSUE THREAD

**Issue by karlsc** [Eowymos/TerraUo#314]
Le .tauntall du PA Protecteur demande (à nouveau) de la mana au lieu de la stamina. Ça fonctionnait bien jusqu'à tout récemment.

**Comment by animatrice-hanson** [comment]
Fixed, seulement le message n'avait pas été changé ("Vous n'avez pas assez de mana..."). Le message sera fixed lors de la prochaine patch.
