### ISSUE TITLE
Les rôdeurs et les îles.

### ISSUE THREAD

**Issue by RiiemTerra** [Eowymos/TerraUo#315]
En ce moment, il est impossible pour un rôdeur d'embarquer ses pets sur un bateau à moins d'avoir un quai à une hauteur spécifique. Ceci pose problème puisque la force du rôdeur réside dans ses pets, mais il ne peut pas aller sur les îles, puisqu'il perdrait ceux-ci au moment où ils descendent du bâteau. 

Deux solutions possibles: 
1: Modifier le script du teleport de la planche pour que les pets suivent au moment du teleport.
2: Modifier les berges des îles au build sur Centred pour que la planche du bâteau arrive collée. (Ceci est plus de travail, mais peut être intéressant pour le facteur risque puisque les mobs pourraient suivre sur le bâteau.)

La solution #1 semble plus simple, mais je ne m'y connais pas. 

Merci beaucoup!

**Comment by Touka5** [comment]
Nous avons besoin de nos rôdeurs sur les îles 💪.

**Comment by MBRND** [comment]
Permettre le .shrink des pets?

**Comment by pocloutier87** [comment]
Un .shrink serait utile, autant pour delog d'urgence et pas perdre ses pets, que pour faire des choses comme ça facilement. À mettre avec un timer ou autre pour éviter des abus (pas faisable en combat, maximum 4, prends des pet slots pareil pour pas éviter le stable, etc.).

Je pense pas que le gold sink de 30g par stable soit vraiment game breaking. Ce serait un quality of life incroyable pour tout perso avec des pets.

**Comment by animatrice-hanson** [comment]
La solution #1 a été implanté et sera disponible dans la prochaine patch. Pour la suggestion du .shrink, elle se trouve ici : https://github.com/Eowymos/TerraUo/issues/343
