### ISSUE TITLE
Suggestion pour les nouveaux joueurs.

### ISSUE THREAD

**Issue by RiiemTerra** [Eowymos/TerraUo#316]
Afin d'améliorer la rétention des nouveaux joueurs, je suggère un système technique et rp à la fois pour créer une possibilité de rattrapage. 

Ceci prendrait la forme d'un système qui permettrait un mentorat par les classes 5.
La classe 5 pourrait venir avec un item qui te permet de "mentorer" un joueur sans classe. 

Pour restreindre l'abus: Le mentorat pourrait s'appliquer sur un seul personnage dont l'account ne contient aucun personnage ayant une classe 3 ou supérieure. Ceci permettrait au nouveaux joueurs d'obtenir une classe 3 plus rapidement, sur un seul de leur perso.

L'item permettant de mentorer donnerait l'xp plus rapidement pour atteindre le lvl nécessaire à la classe 3, dans le but de réduire l'écart démotivant entre le nouveau et la masse de joueur atteignant la classe 5.

Pour la notion rp: le joueur désirant être mentoré devrait trouver un mentor de la classe dont il souhaite se munir. Un nouveau désirant devenir Cavalier devrai trouver un Cavalier classe 5 s'il veut obtenir le système de mentorat.  Si c'est possible de le scripter ainsi: le boost d'xp pourrait être effectif alors qu'ils sont ensemble dans le même screen. Le mentor ne pourrait avoir qu'un seul mentoré à la fois. Ce qui donnerait exemple: 
Tu joues 10 heures avec ton mentor et ca te permet d'obtenir l'xp necessaire a ta classe.  Tu joues seul? Évolution normale. 

Le nombre d'heures est un exemple seulement. 

Voilà.

**Comment by animatrice-hanson** [comment]
Depuis la dernière patch, du level 0 à 50, les personnages grimpent plus rapidement.
