### ISSUE TITLE
BUG dans la création des armures d'os

### ISSUE THREAD

**Issue by GarukWyrmog** [Eowymos/TerraUo#317]
Depuis la MAJ avec le nouveau menu de craft, les skill nécessaire à la réalistion des armures augmente mécaniquement de 4 en 4.
Alors qu'avant en ayant 100 en tinkering on pouvait réaliser l'armure la plus lourde du jeu avec le meilleur ossement a environ 36% except maintenant c'est 0 et ca demande 120 de skill.
![bug craft armure d'os](https://user-images.githubusercontent.com/67527780/97508434-e21ca080-197f-11eb-8f5b-0e168308a7b9.png)

**Comment by animatrice-hanson** [comment]
Fixed depuis la dernière patch.
