### ISSUE TITLE
BUG - Carpentery : Planches pas reconnues

### ISSUE THREAD

**Issue by Johaniegagnon** [Eowymos/TerraUo#318]
Bonjour,

si on change d'essence de bois une fois dans le menu carpentry on ne peut plus revenir aux planches d'érables parce que le système ne reconnait plus les planches.

**Comment by animatrice-hanson** [comment]
Incapable de reproduire le bug sur le serveur test, tout semble bien fonctionner. Si c'est encore le cas, réouvrir un bug avec plus de détails
