### ISSUE TITLE
Création de shiruken

### ISSUE THREAD

**Issue by chuck144** [Eowymos/TerraUo#321]
Suite a la maj sur les menus crafts, l'option 'tout' des sirukens ne fonctionne plus, il les créer un a un. Je n'ai pas tester les autres.

**Comment by Richcoeur** [comment]
C'est assez chiant comme bug :P

**Comment by AnastasiaLogan** [comment]
Est-ce possible de regarder ça svp...Les acrobates nous en dépendons. Merci!

**Comment by animatrice-hanson** [comment]
Corrigé pour la prochaine patch!!
