### ISSUE TITLE
Refonte

### ISSUE THREAD

**Issue by Jobarco** [Eowymos/TerraUo#33]
On peut fondre le minerais d'or avec 50 de mining, mais on ne peut pas le refondre une fois qu'on a créé un objet avec. Par exemple, si j'ai du minérais, je peux le fondre. Mais si je fais un bouclier avec, je ne peux pas le refondre, le système me dit que je ne comprends rien à ce minerai.

**Comment by lefranco86** [comment]
J'ajouterais aussi que je peux refondre seulement quelques minerais du tiers 2 et pas les autres. Le volcanium et le sonne aucun problème, mais pas l'or. Je n'ai pas testé les autres encore..

**Comment by lefranco86** [comment]
J'ai finalement fait d'autres tests (pas tous encore...). Voici les résultats des minerais que je peux fondre : 
- Cuivre : non
- Chrystéliar : oui
- Durian : oui
- Argent : oui
- Fer : oui
- Volcanium : oui
- Acier : oui
- Lithiar : oui
- Étheryl : oui

**Comment by Jobarco** [comment]
J'ai tenté de refondre de l'agapite, sans succès! 

C'est vraiment un bug ultra tannant, quand on pense à la quantité de ressources perdues. :(

**Comment by GalvarCorbac** [comment]
Ca marche aussi avec le Durien

**Comment by Eowymos** [comment]
Un outil, le recycler sera implanté dans la prochaine patch. Vous allez recycler vos objets avec cet item
