### ISSUE TITLE
Crafting_Fletching_Arc_Acajou

### ISSUE THREAD

**Issue by Helldate** [Eowymos/TerraUo#333]
Il est présentement impossible de crafter des arcs en acajou.  Dans le menu crafting cela demande des buches mais dans le menu de sélection des types cela mentionne des planches.

**Comment by Helldate** [comment]
Après avoir retesté le tout le bug semble intermittent lorsque je commence a crafter les arcs en acajou cela fonctionne et après un certain temps je recois un message "Vous n'avez pas assez de buches dans votre sac" malgré que j'ai tous les mats.  Si je change l'essence pour l'érable cela me permet de recrafter à nouveau.

**Comment by animatrice-hanson** [comment]
Incapable de reproduire le problème, tout semble très bien fonctionner
