### ISSUE TITLE
Serpent des mers drop PEAU TERATHAN depuis l'update

### ISSUE THREAD

**Issue by ETGLap** [Eowymos/TerraUo#336]
Depuis l'update, le serpent des mers ne drop plus de cuir maritime mais bien du cuir terathan... est-ce normal? Car c'est à ma connaissance, le seul animal qui donnait du cuir maritime. 

![screenshot_2020-11-10_03-35-10](https://user-images.githubusercontent.com/67438590/98731012-14a89f00-236b-11eb-8c73-74c759fdb6d6.png)

**Comment by animatrice-hanson** [comment]
fixed
