### ISSUE TITLE
Taming et AutoBond

### ISSUE THREAD

**Issue by Xazkan** [Eowymos/TerraUo#34]
J'ai remarqué que depuis ce matin (2020-06-23) que lorsque je tame une créature elle est bond automatiquement.
Est-ce que c'est volontaire? Sinon, c'est un bug qui devrait être corrigé éventuellement.

Merci beaucoup!

**Comment by Krashto** [comment]
Est-ce que tu es rodeur et/ou druide?

**Comment by Xazkan** [comment]
Druide

**Comment by Eowymos** [comment]
C'est volontaire pour le moment, pour rôdeur et druide :) Affaire classée!
