### ISSUE TITLE
.assomer utilise la mana meme si on est encore dans le délai qu'on ne peut pas l'utiliser

### ISSUE THREAD

**Issue by MirageNebulix** [Eowymos/TerraUo#341]
Le titre dit tout!

.assomer utilise la mana meme si on est encore dans le délai qu'on ne peut pas l'utiliser, on a le message qu'on doit attendre pour utiliser ce coup sur cette cible mais le mana est quand même utilisé.

**Comment by animatrice-hanson** [comment]
Fix prochaine patch!
