### ISSUE TITLE
Marquer une description sur un livre d'étude est impossible

### ISSUE THREAD

**Issue by MirageNebulix** [Eowymos/TerraUo#344]
Depuis les changements faits qui avait enlevé le .renommer il est impossible de renommer les livres d'études qu'on crée. Même avec l'option de mettre une description. Impossible avec le tinker tool et la plume (outil de scribe) que ce soit avant ou après avoir mis une 'skill' sur le livre.

**Comment by animatrice-hanson** [comment]
Les descriptions sont en cours de développement du côté de l'équipe technique tel que spécifié lors d'une des dernières maj : 
"- Ajout d'une description possible sur les items suivants à l'aide du menu de craft (nouveau bouton en bas à droite) :
Potions
Armes et Armures (Menu Forgeron)
Armures d'os
Armes de Jet

Les autres système de craft ont également le bouton "Ajouter une description", mais pour le moment il n'est pas encore fonctionnel. À venir dans prochaines MAJ."

**Comment by animatrice-hanson** [comment]
Description sera présent pour pratiquement tous les objets pour la prochaine patch!
