### ISSUE TITLE
Lute fin pouvoir renommé

### ISSUE THREAD

**Issue by Invilforu** [Eowymos/TerraUo#346]
presentement il faut un lute fin pour chaque bout de musique composé. Ca serais bien de pouvoir renommé les lutes pour identifier les chansons attachés au Lute.

p.s. les trois dernieres notes noires du lute fin font planter la fenetre d'interface
p.s.2. les notea noires ne semble pas etre les bonne notes

**Comment by animatrice-hanson** [comment]
Les instruments pourront avoir une description comme tous les autres item à la prochaine mise à jour !
