### ISSUE TITLE
on ne peux pas secure des coffres dans le logis forestier

### ISSUE THREAD

**Issue by Koukcy** [Eowymos/TerraUo#347]
Impossible de "I wish to secure this" dans le logis forestier, cela nous demande d'etre dans notre maison alors que nous y sommes.
Nous devons alors lock down les contenant mais lorsqu'on fais cela le contenu ne peux plus bouger car il se lock down aussi.

**Comment by animatrice-hanson** [comment]
Dans le fonctionnement de base UO, seul le propriétaire du maison peut secure des conteneurs. Classifié comme suggestion et doublon avec https://github.com/Eowymos/TerraUo/issues/348
