### ISSUE TITLE
Summons ne scalent pas avec Int

### ISSUE THREAD

**Issue by Mektor2** [Eowymos/TerraUo#35]
Les summons ne semblent pas scaler avec l'intelligence.

J'ai essayé avec 20 intelligence et 95 pour Esprit animal, Earth Elemental et Air elemental et il n'y a aucune différence entre les créatures summonées, hormis le RNG de base. 

J'ai un souvenir clair qu'Eowymos ait dit que intelligence affectait tous les sorts qui avaient des chiffres, y compris les summons. Ça ne semble pas être le cas (à moins qu'on parle uniquement de la durée? Je n'ai pas vérifié ce point).

**Comment by Krashto** [comment]
Tu devrais vérifier la durée, et me revenir si elle ne change pas. Les summons sont deja suffisament puissant comme ça.

**Comment by Mektor2** [comment]
Je viens de tester avec Earth Elemental, Air Elemental et Créatures (cheval), et 20 int. La durée est exactement la même.

**Comment by Xazkan** [comment]
suite à la 2e classe, j'ai réussi à summon le Air Elemental et le Blade Spirit.
Ils durent à peine 15 secondes à 25 secondes. 
Le air elemental fait presque aucun sort et se bat au CaC.
Le blade spirit est incontrolable (Je connais le sort, je l'ai jamais aimé et ce n'est pas du chialage) mais ne fait quasiment pas de dégat.

Je veux ajouter que la classe d'Invocation est une classe très PvM/PvE et en PvP c'est pas mal moins bon. Alors que cette classe soit forte en chasse, selon moi c'est correcte.

Selon moi la durée est défaillante VS les invocations du Nécromancien. On compare.

Une solution possible, selon moi, c'est que si actuellement l'intel n'influence pas la puissance des invocations, elle pourrait simplement influencer la durée des invocations. Comme ça, on garde la force de cette classe purement et parfaitement PvM sans toucher aux dégats, résist, stats. etc des invocations.
Je pourrais aussi ajouter qu'une légère augmentation du temps de cast de Summon Creature, Esprit animal et l'élémental de terre pourrait nerf légèrement, ce qui serait comprenable si la durée des invocations est augmenté. Le temps d'invocation pour le air elemental et le blade spirit sont déjà plus long que les autres.

Merci

**Comment by Krashto** [comment]
Nous allons étudier le tout pour essayer de pousser un petit fix

**Comment by Mektor2** [comment]
https://uo-terra.forumactif.com/t2282-discussion-au-sujet-des-summons

**Comment by ElusivePanda** [comment]
Int ne scale pas avec la durée des sorts pour le moment, ce sera fix dans la prochaine maj.
