### ISSUE TITLE
Connaissances et métiers

### ISSUE THREAD

**Issue by Ehthanas** [Eowymos/TerraUo#36]
Bonjour , 

Je vien d'atteindre la première classe savant et je me suis appercu que j'avais déja 1 point de connaissace dans Peinture .
Comme j'ai commencé avec le métier Peintre , je me suis dis que c'est possiblement a cause de ca ? Sinon je ne suis que niveau 8
et je ne devrais pas pouvoir avoir 2 pts de connaissances.

Certain m'ont dis la meme chose aussi sur discord et d'autres tel que des forgerons que non .

**Comment by GokuTerra** [comment]
Si je me fie au code, ça ne semble pas être un bug, mais plutôt quelque chose qui est octroyé par la classe un de savant. Par contre, ce n'est pas reflété sur le site.

**Comment by ElusivePanda** [comment]
Est-ce qu'une décision à été prise sur ce sujet?
Edit suite à discussion avec Krashto: Savant ne devrait pas donner de point de PC gratuite.
