### ISSUE TITLE
Suggestion Classe Savant

### ISSUE THREAD

**Issue by L-PTerra** [Eowymos/TerraUo#362]
J'aimerais proposer une mise a jour de la classe Savant pour quelle soit selon moi aussi interessante que les deux autres.

Lorsque tu va forgeron tu dois monter Blacksmith et Carpentry puis tu reçois des PA de classe en métallurgie et en ébénisterie.

Lorsque tu ten va ingénieur tu monter tinkering et Tailoring et encore la tu reçois des PA de classe en Ingénieur et en couture.

je croit qu'il serait peut être intéressant pour le savant de lui retirer (genre Cartography qui na pas vrm d'utilité) et lui ajouter Alchemy ainsi que des PA de classe comme ''Métier secondaire''  un peu comme les deux autres classe artisan.

**Comment by animatrice-hanson** [comment]
La classe Savant connaîtra une amélioration pour la prochaine mise a jour !
