### ISSUE TITLE
Descriptif de sculptures, peintures ne suivent pas lorsque l'item est lock down

### ISSUE THREAD

**Issue by Richcoeur** [Eowymos/TerraUo#365]
Le descriptif n'est pas visible sur les sculptures et les peintures lorsque ces items sont lock down comme décorations. 

Merci :)

**Comment by animatrice-hanson** [comment]
Les peintures et sculptures qui ont été fait avant la mise a jour ne seront malheureusement jamais fonctionnels :( Par contre, les nouveaux que tu craft fonctionne : 
![image](https://user-images.githubusercontent.com/73963084/103177405-4e186980-4848-11eb-86ff-8e8901cd48c7.png)
