### ISSUE TITLE
.transformation des Mortanyss

### ISSUE THREAD

**Issue by Pastrami1987** [Eowymos/TerraUo#366]
Actuellement, le .transformation des Mortanyss nous permet de donner ces 3 apparences aux pet :
- Zombie
- Squelette
- Wisp

Le choix me semble particulier, voir même douteux.

Je propose de les changer pour quelque chose de plus cohérent, un peu plus démoniaque/créature/répugnant.
Voici mes suggestions : 
https://i68.servimg.com/u/f68/19/83/57/55/sans_t10.png

**Comment by Koukcy** [comment]
Selon le lore il serait peu probable qu’on envoie un frere (autre zombie ou squelette) combattre pour nous pour qu’il se fasse blesser Ainsi que le controller.  nous detestons egalement les sans âmes  et voulons nous en debarasser, il est donc peu probable que nous en voulions un avec nous toujours.  Je crois que la liste des bodyvalue est a revoir egalement.

**Comment by animatrice-hanson** [comment]
En effet, il semble peu probable qu'un aîné envoie un jeune frère se battre pour lui. Les transformations ont été revus pour les mortanyss pour quelque chose de plus crédible niveau RP. À venir prochaine maj.
