### ISSUE TITLE
Menu blacksmith - Haches et lances 

### ISSUE THREAD

**Issue by Jobarco** [Eowymos/TerraUo#37]
Les haches ne sont pas placées dans le bon ordre dans le menu crafting VS les skills requis.
De plus, dans les lances, le War Fork ( deuxieme lance ) demande 74.5 % de blacksmith au lieu de 21.

**Comment by Krashto** [comment]
Si tu as l'envie de nous dresser la liste en ordre, ça sauvera du temps a Eo

**Comment by Jobarco** [comment]
Haches

Two handed axe 21 Noctame 74.5
Couperaide 21
Battle axe 22.2
Executioner's axe 25
War axe 22.2
Axe 25
Double axe 25
Furagne 25
Duxtranche 22.2
Large battle axe 44.5
Morgrobe 31
Luminar 31
Tranchecorps 44.5
Ventmort 31
Viftranche 74.5


Ça c'est l'ordre actuel. Il faut juste changer les positions ou s'assurer qu'ils sont du bon niveau.
________________________________
De : Krashto <notifications@github.com>
Envoyé : 23 juin 2020 15:04
À : Eowymos/TerraUo <TerraUo@noreply.github.com>
Cc : Jobarco <micheljr.lachapelle@hotmail.com>; Author <author@noreply.github.com>
Objet : Re: [Eowymos/TerraUo] Menu blacksmith - Haches et lances (#37)


Si tu as l'envie de nous dresser la liste en ordre, ça sauvera du temps a Eo
