### ISSUE TITLE
Voler ou ne pas voler une rune d'ile?

### ISSUE THREAD

**Issue by ETGLap** [Eowymos/TerraUo#372]
Une rune d'ile, est-il un objet pouvant se faire volé ? Ou est-il considéré comme un objet interdit d'être volé.

On s'entend, il y aura du drama le jour que cela va arriver.

C'est arrivée avec les bateaux au départ, lorsqu'ils avaient une valeur de 250k+ et 40k+ de bois. Maintenant que les bateaux furent réduit en coût, il est toujours interdit de voler (à moins d'une entente avec ta victime si elle désire RP avec toi). 

La rune d'ile est 250k. Sa valeur et sa difficulté de farm devient-elle autant qu'un bateau d'ajourd'hui? se qui l'empêcherait d'être voler!

**Comment by Anticipateur** [comment]
Oui, c'est un _item_ comme les autres. Il y a différentes façons pour protéger son investissement.

Les objets qui sont "interdit de voler" possèdent la propriétés "Blessed".
