### ISSUE TITLE
[BUG] Ajouter à Zone de guérison à un spellbook ajoute également Mur de poison

### ISSUE THREAD

**Issue by Johaniegagnon** [Eowymos/TerraUo#376]
Bonjour,

lorsque le sort Zone de guérison (Médecine) est ajouté à un Spellbook, le sort Mur de poison (Nécromancie) s'ajoute automatiquement, ce qui souille les spellbooks des gentils..!

**Comment by Johaniegagnon** [comment]
Bonjour,

le sort Forme animale (Nature) ajoute également automatiquement Peau d'écorce (Nécromancie) au livre.

**Comment by animatrice-hanson** [comment]
Corrigé dans la prochaine maj !
