### ISSUE TITLE
Dagues capacités 4.

### ISSUE THREAD

**Issue by symphonynoose** [Eowymos/TerraUo#377]
J'ai un acheteur qui m'a dit que les dagues étaient bug. Il a capacité 3 en mêlée et est capable de porter une capacité 4. Elle a cependant les même dommage qu'une capacité 3.

A voir. j'ai eu l'air fou de lui vendre des 4 ! Alors quelles le sont pas !

**Comment by animatrice-hanson** [comment]
Est-ce un espion?
