### ISSUE TITLE
- Malaise - (Médecine)

### ISSUE THREAD

**Issue by Saaaaaaaaaaaaaaaaaareth-avec-18-a** [Eowymos/TerraUo#379]
Bonjour !

Le sortilège "Malaise" ne fonctionne pas correctement, il nécessite 2 en "Médecine" et ça dit que je n'ai pas assez en aptitude pour le lancer alors que j'ai 3 en Médecine sur mon personnage. 

![image](https://user-images.githubusercontent.com/75547138/103331062-69f85700-4a64-11eb-929e-4d0592233149.png)

Bonne journée !

**Comment by Anticipateur** [comment]
Corrigé à la prochaine MAJ.
