### ISSUE TITLE
Menu Blacksmith

### ISSUE THREAD

**Issue by lefranco86** [Eowymos/TerraUo#38]
Il manque le Bouclier lourd doré au menu.
Et je pense que ce serait intéressant de renommer l'alliage Telium pour Terrarium ou Terrium. :)

**Comment by Krashto** [comment]
L'alliage restera ainsi. Peut-être qu'eventuellement nous ajouterons de nouveau minerai. pour le bouclier, en effe,t il est manquant!

**Comment by pmduguay** [comment]
Les personnages peuvent commencer à porter la plaque doré et ce bug est encore effectif, je désirais juste le rappeler puisqu'il a été mis "Closed".
