### ISSUE TITLE
Bouclier Gardien actif même sans bouclier

### ISSUE THREAD

**Issue by MirageNebulix** [Eowymos/TerraUo#385]
Je ne sais pas si c'est voulu, mais une fois le bouclier gardien activé (il faut avoir le bouclier en main pour l'activer) on garde un bonus de AR même si on enlève le bouclier.

**Comment by pmduguay** [comment]
Il affiche encore l'AR mais le premier coup que tu vas recevoir sans bouclier va le désactiver. Ça été scripté ainsi pour ne pas avoir à refaire .boucliergardien chaque fois que tu te guéris avec des pansements.
