### ISSUE TITLE
Necromancie

### ISSUE THREAD

**Issue by Ripdream** [Eowymos/TerraUo#41]
80 int / magery 50/ eval intel 50 / nécromancie 7

Mauvais présage (niv 6) : Description du sort: Augmente la résistance magique de la cible.
-ne peux pas être lancé sur soi. 
- Lorsque lancé sur quelqu'un il agit comme un sort offensive ( war mode etc )
- Augmente la magic resist de 25% (Buff) 
- Retire la protection physique déja lancé
- dure 1 seconde et demi.

**Comment by Krashto** [comment]
Je vais revérifier l'effet du spell. Je connais celle de base, qui n'est pas du tout celle la. Peut-être que le descriptif du spell n'est pas bon. Normallement, Evil Omen pose un debuff sur la cible qui augmente le prochain sort offensif.

**Comment by Ripdream** [comment]
well, en ce moment je te confirme que sa augmente la magic resist de l'adversaire. Comme cité ci-haut mon adversaire gagnais 25% de magic resist temporairement.

**Comment by ElusivePanda** [comment]
Sur le serveur test Mauvais Présage avait cette fonction là, mais avec 12 Necro, 100% all skills, il durait environ 15 secondes et donnait 50% magic resist. Je crois que le sort à la bonne fonction, mais il faudrait effectivement qu'il dure plus longtemps et ne soit pas considéré comme un sort offensif.

**Comment by Ripdream** [comment]
J,ai quelque chose a ajouter

Curse weapon ne life leech pas.

**Comment by Hazlith** [comment]
Petite mise à jour : 
**90 INT - 50% Magery, 50% poison - 5 de nécromancie**

**Familier :** Le serpent semble avoir moins de vie que la chauve-souris, c'est voulu ?
**Peau de mort :** Semble durée indéfiniment, ou trop longtemps à mon avis
**Calamité :** Le sort demande d'avoir une arme d'équipée, selon la description, on devrait pouvoir voler de la vie avec des sorts aussi. Sinon, le vol de vie (si j'équipe une dague pour activer le sort) n'est pas super efficace. Surtout si on prend en considération qu'il dure que quelques secondes. 
**Mur de poison :** C'est voulu que la durée du sort soit aussi courte ? 

Merci

**Comment by ElusivePanda** [comment]
Calamité est un spell leech, mais tu dois avoir une arme équipée. Pour la durée du sort, tu peux caster avec ce weapon en main. La balance du sort est à revoir, mais il fonctionne.

**Comment by Hazlith** [comment]
Merci pour la rÃ©ponse ! 

ALEXANDRE MERCIER
 Designer graphique

 __ 

 www.alexandremercier.com 
 info@alexandremercier.com 

 -------Original Message-------

**Comment by NorNorr** [comment]
J'aimerais rajouter que Jet de poison niveau 5 ne monte pas magery apres 50% je suis stuck a 50% et j'ai aucun cap de reach

**Comment by Ripdream** [comment]
Serment de sang ne procure pas de reflexion de déja Physique !

**Comment by ElusivePanda** [comment]
Mauvais présage est maintenant un sort offensif, à vous de le découvrir IG, ce fix est live.
Le serpent a maintenant sa fonction propre, il touche, empoisonne et meurt aussitôt, ce fix est live.
Peau de mort corrigé dans le cadre d'un autre bug, dans une prochaine Maj.
Calamité à été balancée dans une maj précédente, ce fix est live.
Serment de sang à été fix dans une maj précédente, ce fix est live.

Si vous avez d'autre bug sur nécromancie, ouvrez un autre issue S.V.P. celui-ci est déjà trop chargé. 
Merci.
