### ISSUE TITLE
Intel vs dégat des sorts

### ISSUE THREAD

**Issue by SteinVeldeson** [Eowymos/TerraUo#47]
Je ne sais pas si ca peut compté comme un problème ou si c'est voulu ainsi, mais il me semble que la différence est assez minime sur le dégat que l'Intel donne sur les sorts. J'ai testé avec boule de glace, je fais 30 de dégat contre un ours brun a 50 Intel et 35 de dégat avec 80 Intel contre le même ours.

**Comment by ElusivePanda** [comment]
Intel scale belle et bien avec le dommage des sorts, il ne faut pas s'attendre à avoir du double dommage sur un sort de niveau intermédiaire toutefois.
