### ISSUE TITLE
Gump femme Mortanyss

### ISSUE THREAD

**Issue by ryder2** [Eowymos/TerraUo#48]
Sur l'ancien client, les gumps de femme Mortanyss apparaissent bien sur le paperdoll, sur le nouveau, nous sommes tous des hommes.

**Comment by MissIelenia** [comment]
Fonctionne avec l'ancien client, donc le problème est dans le nouveau client.

**Comment by Krashto** [comment]
est-ce toujours d'actualité, ou c'est regler depuis la derniere MAJ client? A savoir si je ferme ou pas

**Comment by ryder2** [comment]
Toujours d'actualité, ça n'a pas été réglé

**Comment by Ariakan1982** [comment]
Le tout est fixé
