### ISSUE TITLE
Pâtes

### ISSUE THREAD

**Issue by Amaihel** [Eowymos/TerraUo#50]
Les pâtes sont faites à partir de bol de farine. Toute fois, une fois crée, le bol disparait en même temps. Il serais bien que le bol nous soit rendu car il coute plus chère que la pate elle même au pnj (4po le bol vs 2po la pate)
Il faudrait aussi enlever la pate sucré du menu qui est craftable sans le menu et duquel le miel na pas été mis pour la créé.

**Comment by Amaihel** [comment]
Je relance un peu mon poste vue que sa fait un moment mais comme maintenant un peux manger sa serais chouette de pouvoir cuisiner nous même la pâte. Ne peut-on pas juste rajouter un bol au retour avec la pâte crée...?

Sinon en attendent, serait-il possible d’augmenter le nombre de pâtes sur les vendeurs s'il vous plait?

**Comment by JasmineRoy** [comment]
+1
sinon le bol pourrait être craftable par les bricoleurs, peut-être?
même avoir un nombre de use si nécessaire ?

**Comment by animatrice-hanson** [comment]
La pâte sucrée ne prend plus de miel.
Le bol a été ajouté au menu du bricoleur.
À venir prochaine maj !
