### ISSUE TITLE
Chaussures et vetement de cuirs

### ISSUE THREAD

**Issue by Amaihel** [Eowymos/TerraUo#55]
Les sandale ne ce teigne pas
Impossible d'utiliser d'autre cuir pour fabriquer des vêtements demandant du cuir
Jupette de cuir demande du cuir alors qu'il est marquer tissu pour la fabrication

**Comment by Amaihel** [comment]
J'ai fait une jupe de cuir en cuir maritime hier et il ne prend pas la couleur

**Comment by animatrice-hanson** [comment]
˜˜Les sandale ne ce teigne pas˜˜
˜˜Impossible d'utiliser d'autre cuir pour fabriquer des vêtements demandant du cuir˜˜
Jupette de cuir demande du cuir alors qu'il est marquer tissu pour la fabrication

**Comment by animatrice-hanson** [comment]
Tout sera en place pour la prochaine patch.
