### ISSUE TITLE
Délai de changement de classe

### ISSUE THREAD

**Issue by ElusivePanda** [Eowymos/TerraUo#57]
Le délai entre les changements de classe n'est pas fonctionnelle.

Repro step:
1) Perdre sa classe en baissant un skill et tomber à "Aucune"
2) Monter ses skills pour atteindre les pré-requis de classe 2.
3) Lire le livre de classe 1, sans délai.
4) Lire le livre de classe 2, sans délai.
5) Constater dans le .fiche que la classe 2 est active avec tous les PAs et avantages.

Expected result:
La lecture du livre de classe 1 est possible et donne accès à la classe (si la dernière lecture est > 7 jours).
La lecture du livre de classe 2 n'est pas possible avant un délai de 7 jours.

**Comment by Mektor2** [comment]
Il me semble que si on perd les skills en lien avec une classe 2+, on devrait retomber à la classe inférieure, non?

I.e. un Ensorceleur qui baisse Magery à 49.9 retombe Apprenti.

**Comment by ElusivePanda** [comment]
Effectivement Mektor, mais mon cas test n'est pas classe 2 => classe 1 => classe 2. Il est de perte toute ses classes jusqu'à aucune et remonter classe 2.

**Comment by GokuTerra** [comment]
Pour résoudre ce problème, il faudrait mettre un délais lorsqu'on passe de zéro classe à classe un. Présentement, ce n'est pas le cas.  C'est coder comme ça. Présentement, si tu passes de zéro classe à classe un, le délais n'est pas mis, donc tu peux ensuite passer de classe un à classe deux. Par contre, tu ne pourras pas passer de classe deux à classe trois avant que le délais soit atteint. Je peux faire en sorte que le délais soit mis même si on passe de zéro classe à classe un.

**Comment by GokuTerra** [comment]
Après en avoir discuté avec Eo, j'ai mis un délai lorsqu'on passe de zéro classe à classe un.
