### ISSUE TITLE
Vendeur de chevaux mauvais inventaire (Tyrimar du moins)

### ISSUE THREAD

**Issue by Purps32** [Eowymos/TerraUo#59]
J'ai tenté d'acheter un cheval gris(argent) ce matin, le 3e en inventaire et après l'avoir acheté il était pas gris, il était beige, comme le 2e en inventaire (ou celui qui s'apprivoise sur le terrain aussi). 
Je ne sais pas si ce sont tous les vendeurs qui ont les mauvaises couleurs, mais il faudrait vérifier. Je sais que le noir est noir. 
Je ne sais pas si le plus jaune est vraiment jaune (le 4e en inventaire).

**Comment by Ariakan1982** [comment]
Fixé ! :)
