### ISSUE TITLE
Hide & DH

### ISSUE THREAD

**Issue by Bsx-the-Wise** [Eowymos/TerraUo#60]
Je crois que le calcul a été inversé.
Car avec 30% de Hide, je me fais detecter par 0 de DH.
Mais avec 56% et puis à presque 60%, impossible de DH quelqu'un qui a 45% de hidding.

**Comment by Zxithedead** [comment]
Je peux confirmer que je n'arrive pas a DH quelqu'un avec 7%, et quelqu'un d'autre avec 15% de moins que moi. Je n'ai pas tester a l'inverse par contre.

**Comment by Krashto** [comment]
Je vais reverifier, la formule est bien ce que nous voulons
