### ISSUE TITLE
Poison et antidote

### ISSUE THREAD

**Issue by DorianDeBeauffort** [Eowymos/TerraUo#61]
Bon voila le point bien simple, les ticks de poison sont trop rapide comme une mitraillette. Je me souviens que sur zyx tu avais le temps de faire un bandage ou un sort d'antidote quand ca te disait que tu es empoisonné. La en ce moment tu mange tout les tics en 1 a 2 secondes, rendu la le sort antidote sert a rien et soigner par bandage encore moins.

Voila !

**Comment by Krashto** [comment]
Nous allons ajuster le tout, car en effet, il y a bel et bien un probleme avec ça.
