### ISSUE TITLE
Alchimie

### ISSUE THREAD

**Issue by Hebius06** [Eowymos/TerraUo#63]
Retour sur les potions : 

_ Antidote ne sert pas, il n'y a pas le temps (ou presque) de soigner un poison vu la rapidité des tics. **Même probleme que Cure, sera traité en même temps**

_ Délai entre 2 utilisation de potions trop important ( 5 secondes pour explosion, 23 pour les autres potions)

_Dégâts de la potion incendiaire pas assez élevés par rapport à  son coût de fabrication et délai trop long (30 seconde entre 2 jets). **À Revoir**

**_Une potion remplace l'autre. En buvant une potion de force par exemple, on perd le bonus de la potion d'intelligence précédente** (Ne sera pas toucher, c'est volontaire)

_ Boire 1 potions de buff après une autre génère un message "You must wait 10seconcds before using another potion." Le délai réel est proche des 23 secondes **Message à corriger**

**Comment by Adalrick** [comment]
_Une fois stackées, les potions ne peuvent pas être destackées

**Comment by ElusivePanda** [comment]
Normalement fix dans la dernière Maj, laissez un commentaire si bug est toujours présent.
