### ISSUE TITLE
Boule de feu trop faible

### ISSUE THREAD

**Issue by pocloutier87** [Eowymos/TerraUo#64]
51 magery. 51 eval intel. 95 Intel. 

Boule de feu niveau 6 fait entre 16 et 22 sur un morlask. 

Par comparaison abeilles niveau 1 fait 18 chaque fois. Poison mineur niveau 2 fait 24 chaque fois (3×8). Un autre joueur avec boule de glace niveau 5 fait entre le double et le triple selon mes rolls vs les siens (je n'ai pas ses stats mais il ne peut avoir plus de 90 intel et est même niveau de classe que moi, donc a valider)

Le fizzle semble haut mais ça peut être voulu. Je ne peux pas valider le scaling non plus mais overall c'est très faible pour niveau 6 puisque lancer abeilles niveau 1 est l'équivalent statique, moins coûteux et sans fizzle.

**Comment by Krashto** [comment]
Nous comptons prochainement dresser une liste de chacun des spells et ainsi revoir le scaling des différents spells vs leur ancetre
