### ISSUE TITLE
Familiar Death Adder

### ISSUE THREAD

**Issue by pocloutier87** [Eowymos/TerraUo#66]
J'ai pu l'invoquer avec 50 magery (même si le message disait 50 necromancy) mais il a présentement -- points de vie selon animal lore et en pratique, c'est 1 hp pour le tuer.

Ses stats semblent bien meilleurs que les autres dans la liste sinon (Str dex int). Selon la force voulu, vérifier sa demande en nombre de familiers.

**Comment by Krashto** [comment]
Je te refere au post sur fireball
