### ISSUE TITLE
Scaling poison (sorts)

### ISSUE THREAD

**Issue by pocloutier87** [Eowymos/TerraUo#67]
Poison mineur fait 3x8 dégâts depuis que je l'ai ( 35 magery j'en ai maintenant 51) mais ça semblait voulu comme spell niveau 2. 50 poisoning ne rajoute pas de tic et c'est voulu je crois.

Par contre poison niveau 4 fait aussi 8 de dégât par tick mais les dégâts ne semblent pas augmenter avec magery/intel/capacité magique. Un 4e tick est apparu dans les 30 de poisoning, donc 4x8 total ça semble marcher de ce côté. 

Valider le tout quand ce sera rework pour antidote/cure/bandages ?

**Comment by Krashto** [comment]
Même chose, je met ca dans le meme lot que fireball
