### ISSUE TITLE
le sort explosion

### ISSUE THREAD

**Issue by DorianDeBeauffort** [Eowymos/TerraUo#70]
Lorsque l'on cast le sort, il se passe 2 secondes avant qu'il ne s'active apres avoir cliqué sur la cible, donc la cible a le temps de se pousser loi, pas très pratique pour un sort de zone qui fait moins de dégat.

**Comment by Krashto** [comment]
Explosion est un sort single target, et il a toujours fonctionné de la sorte. Le projectile est hyper lent, mais il peut être utiliser en combo avec d'autre spell pour faire un mass burst de dégat en meme temps
