### ISSUE TITLE
Dissipation de mur: Permet d’annuler les sorts d’adjuration; les sorts d'adjuration ont tous été retirés

### ISSUE THREAD

**Issue by MaasUO** [Eowymos/TerraUo#72]

**Comment by Krashto** [comment]
Fonctionne sur gate travel + Poison wall

**Comment by MaasUO** [comment]
> Fonctionne sur gate travel + Poison wall

Donc ça résume bien toute l’inutilité de la chose.

**Comment by ElusivePanda** [comment]
Maas, je suis convaincu que tu peux voir le potentiel de dispel UNE des deux entrées de la gate. C'est un des plus grand classique de UO.

"Eh? Elle mène où cette gate qui vient de spawner devant la banque de Citria?"

**Comment by MaasUO** [comment]
Si tu fais tes devoirs tu vas te rendre compte que les Gate Travel seront excessivement rares, et donc l'utilisation de ta technique extrêmement situationnelle. Si ça arrive une fois que ça sert dans l'histoire du shard je serai le premier étonné.

**Comment by ElusivePanda** [comment]
C'est vrai que c'est underwhelming, même si garder l'option serait nice. As-tu une idée à proposer comme sort lvl 4 ?

**Comment by animatrice-hanson** [comment]
Si une suggestion est faite pour remplacer ce sort, l'équipe se penchera dessus en temps et lieu, pour le moment il y a d'autres priorités.
