### ISSUE TITLE
XP requis au dela du niveau 100

### ISSUE THREAD

**Issue by Krashto** [Eowymos/TerraUo#73]
Je le note avant de l'oublier

![image](https://user-images.githubusercontent.com/67296022/85926025-65ab7100-b86a-11ea-9ead-b043c7e53056.png)
![image](https://user-images.githubusercontent.com/67296022/85926030-74922380-b86a-11ea-8d1d-bb4c2705122e.png)

Le niveau 149 recommence l'XP necessaire

**Comment by animatrice-hanson** [comment]
Fixed !
