### ISSUE TITLE
Crafting des appats de peches

### ISSUE THREAD

**Issue by Ehthanas** [Eowymos/TerraUo#75]
Dans le menu thinkering des appats de peche .

Il est possible de crafter des appats pour truite , mais tous les autres requiert aussi des écailles de truite et un ligot de fer.
Cependant en essayant de crafter un appat de doré , morue etc ... Ca dis qu'il n'y a pas assez d'écailles pour se faire , meme si j'ai les dit écailles . Je suppose que ce devrait etres les écailles du meme types de poisson qui devrait etre affiché ?

**Comment by tordinforgefeu** [comment]
Juste un erreur sur l'écriture. Si tu as des écailles de morues et dorés, tu pourras créer des appats de chacun.

**Comment by GokuTerra** [comment]
Devrait être réglé à la prochaine mise à jour.
