### ISSUE TITLE
Teinture Noire

### ISSUE THREAD

**Issue by Zxithedead** [Eowymos/TerraUo#77]
Avec 2 points en teinture, j'arrive pas a utiliser la teinture Noire du niveau 1. Toute les autres teintures ont l'air de fonctionner. 

Ça me dit que je n'ai pas assez de point en teinture.

**Comment by Krashto** [comment]
Nous travaillons sur le prochain systeme de teinture, je vais fermer le sujet, il sera regler en meme temps que l'implantation du futur systeme!
