### ISSUE TITLE
Récupération matériaux tailoring / tinkering

### ISSUE THREAD

**Issue by GarukWyrmog** [Eowymos/TerraUo#78]
Lorsque l'on créé un morceau d'armure en cuir on peu récupérer un peu de cuir en le re-découpant (si on cherche a faire de l’exceptionnel par exemple)

Par contre impossible de faire cela avec les armures en cuir cloutées ni avec les armures d'ossements.

**Comment by Eowymos** [comment]
Ajout du Recycleur en jeu. Vous pourrez recycler vos créations (Retrait du Resmelt de blacksmithy, pour n'avoir d'un seul système en place). Sera en vente chez les NPCs
