### ISSUE TITLE
Spell : Protection

### ISSUE THREAD

**Issue by Bsx-the-Wise** [Eowymos/TerraUo#81]
Perte d'AR, plus de 30% avec 26 d'AR.
Perte de MR, -20% resisting spell.
Pour empêcher un fizzle sur 10 ou 15.
Si Concentration/Connaissance accrue permet d'éviter de fizzle, certaines classes sont mieux pourvues que d'autres.
Et l'investissement de PA rendrait le Thamaturge bancal, contrairement à d'autres classes.

Soit il faut revoir la classe, soit les spells.

Bref à l'heure actuelle, le perso ne vaut même pas un demi joueur en PvP et n'est qu'une classe PvE.

**Comment by ElusivePanda** [comment]
Protection à été revu depuis, si le sort est toujours en problème, refaire un commentaire et je vais réouvrir.
Merci.
