### ISSUE TITLE
Spawn de minerais aléatoire depuis la MAJ du 28/06

### ISSUE THREAD

**Issue by JasmineRoy** [Eowymos/TerraUo#82]
Sur un bord de montagne près de Najar, ou il n'y avait avant aucun minerais autre que le fer, le spawn est visiblement redevenu aléatoire. J'ai testé un moment, au départ j'avais du volcanium et j'ai cru qu'un spawn avait été ajouté, mais après j'ai eu d'autres spawn de cuivre bronze, de durian et un mini peu de sonne sur exactement le même pan de mur.

**Comment by Invilforu** [comment]
les montagnes de durian, pop du sonne aussi
la mine de sonne pop de l'or des fois
la montagne de jolinar pop du cuivre et bronze

**Comment by Krashto** [comment]
Pourquoi l'endroit que je test ne pose jamais probleme :( ahah on va checker ca
