### ISSUE TITLE
.chuchotter / .secret

### ISSUE THREAD

**Issue by Gendryl** [Eowymos/TerraUo#86]
Après avoir fais quelques tests, il semblerait que le texte des commandes apparaît uniquement si l'on n'utilise pas d'espaces.

exemple : 

.chuchoter Ceci est un test (ne fonctionne pas)
.chuchoter CeciEstUnTest (fonctionne)

**Comment by MBRND** [comment]
il faut utiliser les "" pour les espaces.
Ex: .secret "Ceci est un test"
