### ISSUE TITLE
Armes de jets non viable

### ISSUE THREAD

**Issue by Hermne** [Eowymos/TerraUo#87]
Plusieurs problèmes avec les armes de jet en ce moment. :)

1. **Coût de fabrication et prérequis beaucoup beaucoup trop élevé.**
(si cette task est faite ce sera encore pire: https://github.com/Eowymos/TerraUo/issues/27)

- Aucun moyen de créer une "batch" de projectiles de jet comme les flèches. 100 haches de jet = 100 clicks = usure de l'outil infiniment plus rapide + temps

- Le coût des projectiles pour les arcs et arbalètes est fixe quelque soit le niveau de l'arme. 
1 flèche / 1 carreau = 1 buche + 3 plumes
Prérequis d'aptitude: 0
Prérequis de skill: moins de 35.
Avec un arc il est aisé d'être complètement autonome pour faire son consommable.

Là avec le coût en buche actuel d'un shuriken (5) il faudrait **5000** buches pour 1000 shuriken ET un artisan (ou un investissement lourd en PA)
Prérequis d'aptitude en fabrication d'arc dès le javelot (arme niveau 3)
Prérequis de bowcraft élevé.

**Proposition:** le coût de fabrication des projectiles de jet doit être rationnalisé. Si l'acrobate doit aller voir un artisan à chaque chasse pour miner 5000 lingots et produire 1000 projectiles c'est impossible en terme de gameplay, ça en fait la classe la plus coûteuse du jeu (le mage pouvant aller voir un npc pour ses regs).
Hache de jet 1 buche
Javelot 2 buches
Etoile 1 lingot
Shuriken 2 lingots
Retirer le prérequis d'aptitude
Ne pas retirer le prérequis de skill en bowcraft pour toujours avoir quelque chose de plus compliqué à faire qu'une flèche (rien que les lingots rendent ça plus compliqué en terme de prérequis de classe).
Un acrobate est déjà dans l'incapacité d'obtenir seul son arme, comme les gants sont fait par un couturier.

Créer des gants de jet différents au même titre que les armes pour les niveaux 2 3 4 5.
Ainsi cela fera une arme à vendre par le couturier au fur et à mesure.

 2. **Dégâts buggés.**
Gants de jet normal + hache de jet (2) vs Tarkarc normal (2) et flèches
2 de dégâts pour les haches de jet sur un chevreuil.
20++ pour l'arc.

**Proposition:**
Faire en sorte que la portée soit inférieure à l'arc ou l'arbalète mais les dégâts **ou** la vitesse un peu supérieurs à l'arbalète.
En somme une arme à DPS supérieur mais moins pratique pour kite.
Une arme à 6 tiles par exemple qui ferait un 40 quand un arc de même niveau fait un 30. C'est perdre 4 tiles de kite pour gagner du punch (vu que ce boost de dégats se réplique sur les critz).

En gros l'arc serait le sniper.
L'arbalète la carabine
L'arme de jet le shotgun.

**Comment by SholShandir** [comment]
Javelot capacité 3 et hache de jet capacité 2 font exactement le meme dégats (25-26 avec 95 de force)

Je devine que le dégat est lier au gants et non au projectile. 

Le double shot du coup critique semble pas marcher sur le javelot, mais sur la hache oui.

**Comment by chuck144** [comment]
Voir autre proposition ici : https://uo-terra.forumactif.com/t2442-suggestion-pour-les-armes-de-lancer

**Comment by Krashto** [comment]
Les armes de jets seront retouché, elles ont été oublier lorsque nous avons refait le calcul des dégats. 

Pour ce qui est de la "nécéssité" a demander a un artisan pour le craft de ses armes de jet, je ne vois pas pourquoi.
La classe possède suffisament de mining et de lumberjack pour aisément s'auto suffir.

le fer n'est pas long à ramasser avec suffisament de force.

**Comment by Hermne** [comment]
C'est totalement déséquilibré en coût de ressources par rapport à un arc ou une arbalète.

La force je ne vois pas cela comme un argument, cela contraindrait à orienter son build sur un attribut et rendre non viable tout acrobate sans force élevée. Pour une classe orientée critz je trouve ça moyen.
J'ai 50 en force, faire des flèches est déjà long mais avec un coût de 5 pour 1 ca va juste être impossible de faire des armes à projectile sans y passer des heures.
Je pourrais faire le test et chronométrer mais faire 1000 haches de lancé ça va clairement me prendre beaucoup beaucoup plus de temps que de faire 1000 flèches. Avec un coût qui va monter avec mon niveau d'arme contrairement à tous les archers et rangers.
Ca me semble totalement inéquitable vu qu'il n'y a aucun avantage en contrepartie. 

L'autre problème c'est que si une flèche peut être fait par n'importe quel noob pour aider, ça n'est pas le cas des projectiles d'armes de jet qui demandent des PA en bowcraft. 

Ca fait beaucoup de défauts pour quelque chose qui n'a aucun avantage par rapport à un arc ou une arbalète. :)

**Comment by Hermne** [comment]
Nous n'avons pas tous des builds "force" ou une tendance à swap les attributs à la volée selon le besoin immédiat mais soit.. pas ma décision.
Rien que pour les haches de jet ça me prend plus de 2X le temps pour faire un même nombre de haches de jet que de flèches. J'imagine que ça tiens aussi de pas pouvoir les faire en batch et de n'avoir que le prérequis de classe en lumberjack.

Mining 15% à la 3ème classe je doute très très fort que ce soit auto suffisant vu que ça ne permettra même pas de fondre des lingots de manière fiable mais je n'ai pas encore essayé... Je verrais bien j'imagine ou je changerais de classe si ça ne me va pas.
