### ISSUE TITLE
Aassassina fait moin de dégat qu'un coup de dague standard.

### ISSUE THREAD

**Issue by MBRND** [Eowymos/TerraUo#88]
Testé avec le 2 d'assassina de base de écorcheur, en étant stealh, dans le dos de la victime. J'ai fait moin de 20 de dégats. La dague d'écorcheur a ce niveau fait environ 23-27 avec 90 de STR.

Expected results: Avoir un bonus de dégats basé sur le weapon plustot qu'un dégat linéaire selon le niveau d'assassina.

On ne devrait jamais faire moin mal qu'un coup blanc avec assassina. Le calcule devrait être un % bonus a une attaque standard pour une seul attaque au début.

Même a 8 d'assassina les dégats sont encore ridiculement inutile versus simplement attaquer la cible.

J'en convient que les dégats d'assassina on été changer pour un "ambush" a la World of warcraft. Dans l'états actuel malheureusement même a haut niveau assassina n'est pas plus alléchant que simplement attaquer la cible normalement.

**Comment by Purps32** [comment]
À 8PA en assassinat et ça enlève 20% de la vie. Une lance ou rapière en stealth fait plus mal.

**Comment by Krashto** [comment]
20% de vie, un coup blanc plus mal?

J'ai plus de 300 de vie, avec mon armure, personne me fait au dessus de 40 de dégat.

**Comment by MBRND** [comment]
Mon **opinion** sur la philosphie de ce que Assassina devrait-être:
Est-ce que c'est un dégat flat? ou vraiment un % de vie? A 12 PA, dans une situation optimal ca devrai faire 100% des hp, voir même dans une situation sub-optimale. 8 Pa+ Devrait assurément faire 100% de dégats dans une situation optimal; Stealth, dans le dos, pas de gorget.

Il y a déja beaucoup d'options pour contrer un assassina. DH, gorget, (passivement le manque possible de stealth/hiding de l'attaquant) Pour ce rendre a l'option de faire un assassina il y a beaucoups qui peu déja manqué. Si c'est pas plus payant qu'un coup blanc, ou a peine plus payant c'est une gimmick.

Ceci-dit si c'est une gimmick, ca sert a rien de la surveiller et fermer la classe a une sélection de joueurs étant donner qu'il y a actuellement des options beaucoups plus viable pour jouer le "assassin-like" en PVP dans la simple optimisation de son kit PVP en général.

La réussite de l'assassinat devrai ce décidé avant que le combat commence. Si malheureusement l'assassin ce rend a ca victime, le combat devrait-être essentiellement déja gagné pour celui-ci.

**Comment by Eowymos** [comment]
Retour du one shot à la prochaine maj :)
