### ISSUE TITLE
Quantité de cuir requis

### ISSUE THREAD

**Issue by Jobarco** [Eowymos/TerraUo#94]
Quand je veux me faire une armure, si j'ai le montant exact de cuir dans mon sac, je ne peux pas crafter l'objet. J'ai besoin absolument d'un cuir de plus. 

Merci.

**Comment by HoboKingCarpenter** [comment]
Tu as moins de 50 Sagesse parce que ca affecte le Nombre de ressources minimum requises pour les crafts.

**Comment by Krashto** [comment]
Comme mentionné plus haut, sagesse affecte la consommation de materiel lors de craft.

**Comment by Jobarco** [comment]
Non, mais si ça demande 6, que j'ai 6 dans mon sac, je devrais pouvoir crafter mon item ... Non ??
________________________________
De : Krashto <notifications@github.com>
Envoyé : 29 juin 2020 13:56
À : Eowymos/TerraUo <TerraUo@noreply.github.com>
Cc : Jobarco <micheljr.lachapelle@hotmail.com>; Author <author@noreply.github.com>
Objet : Re: [Eowymos/TerraUo] Quantité de cuir requis (#94)


Closed #94<https://github.com/Eowymos/TerraUo/issues/94>.
