### ISSUE TITLE
Peaux et os animaux

### ISSUE THREAD

**Issue by tordinforgefeu** [Eowymos/TerraUo#98]
Je viens de tuer 4 lapins et 3 cerfs.

Chacun donne 1 peau et 1 os. Quand je les stack dans mon sac, ils disparaissent. Donc au final, je n'ai récupéré qu'un os et une peau.

**Comment by tordinforgefeu** [comment]
A noter que j'avais le minimum de force, dex et consti

**Comment by Amaihel** [comment]
le minimum? tu veux dire 25 ou 50?

**Comment by tordinforgefeu** [comment]
20-25 je crois

**Comment by chuck144** [comment]
J'ai remarquer aussi que le Sniss Mage donne os et cuir normal.
